$axure.loadCurrentPage({
  "url":"出售详情页.html",
  "generationDate":new Date(1432237664741.48),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0750433ee3a0488d9f874f9652d8997f",
    "type":"Axure:Page",
    "name":"出售详情页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"651f1944cf384764b19a8aff03311a79",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":106,
              "height":548}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"428e12b5071b4fd493c3099196f45532",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":106,
                  "height":548}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 卖时间",
                      "target":{
                        "targetType":"page",
                        "url":"卖时间.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/发起购买请求页/u2.png"}},
{
          "id":"0d26b06df13c45cca42b1cf8a06dfb0e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":0},
            "size":{
              "width":216,
              "height":548}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88dc219ee3bd45c7a6808c464e8a828d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":106,
                  "y":0},
                "size":{
                  "width":216,
                  "height":548}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/出售详情页/u2.jpg"}},
{
          "id":"eb651a3e905e475d80c2e2cbb9a75d5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":158,
              "y":10},
            "size":{
              "width":112,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd1643c2350648ba87451f350156d274",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":158,
                  "y":10},
                "size":{
                  "width":112,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0275acebec434a8d938a877afad3aadf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":147,
              "y":181},
            "size":{
              "width":139,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e72aa77c1674c47a639f067386bf174",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":147,
                  "y":181},
                "size":{
                  "width":139,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93ee4a5d3aee49608d137f05dc5414e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":140,
              "y":205},
            "size":{
              "width":146,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d3a807b9af94be98faafdd89adeb4e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":205},
                "size":{
                  "width":146,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ffda3b02aaa4ef4b18f60502deecd61",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":140,
              "y":310},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce92cc4aeda64b15a6e209617c8d82eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":310},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d82672a4ca8e49b0abadfb22e4a6675b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":126,
              "y":264},
            "size":{
              "width":184,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4100e7f64ad5474daf9352e95b3691e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":126,
                  "y":264},
                "size":{
                  "width":184,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80013b9cd2d94a73aa8319a7e12f1ecc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"72px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCBC9CA,
              "opacity":1},
            "location":{
              "x":137,
              "y":361},
            "size":{
              "width":132,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efcc67dc48d34191817b59a17bb0c8b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"72px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCBC9CA,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":361},
                "size":{
                  "width":132,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af8ae9e377ca45cd8bb1504cba662457",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":263,
              "y":401},
            "size":{
              "width":27,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ab6752788644b97b9683c5fe02d2bed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":263,
                  "y":401},
                "size":{
                  "width":27,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3529be1874024d68938e25d9d64ad046",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":443},
            "size":{
              "width":216,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"079c72b798734f78be98c8de9ed92264",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":106,
                  "y":443},
                "size":{
                  "width":216,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起购买请求页/u16.png"}},
{
          "id":"34e07ca00754422a85ae2f2021b29599",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":498},
            "size":{
              "width":216,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d9280104db44a5eaa1bbf9cb41f7f0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":106,
                  "y":498},
                "size":{
                  "width":216,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起购买请求页/u16.png"}},
{
          "id":"c69bbbe8f8dd430f880dea40d2dbb84a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":109,
              "y":444},
            "size":{
              "width":210,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e14cc570b7b456a91ea167352846383",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":109,
                  "y":444},
                "size":{
                  "width":210,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 确认售出页",
                      "target":{
                        "targetType":"page",
                        "url":"确认售出页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d23765edf5674b779fb3933e2c5cf2a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":109,
              "y":499},
            "size":{
              "width":210,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b18621e06324713b9c546d273b95883",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":109,
                  "y":499},
                "size":{
                  "width":210,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 发起出售请求页",
                      "target":{
                        "targetType":"page",
                        "url":"发起出售请求页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4ee9555810f4661b01e1a65f0cbc88d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":140,
              "y":330},
            "size":{
              "width":166,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acff0a79895244d58e14808395d0d261",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":330},
                "size":{
                  "width":166,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "651f1944cf384764b19a8aff03311a79":{
      "scriptId":"u0"},
    "428e12b5071b4fd493c3099196f45532":{
      "scriptId":"u1"},
    "0d26b06df13c45cca42b1cf8a06dfb0e":{
      "scriptId":"u2"},
    "88dc219ee3bd45c7a6808c464e8a828d":{
      "scriptId":"u3"},
    "eb651a3e905e475d80c2e2cbb9a75d5f":{
      "scriptId":"u4"},
    "cd1643c2350648ba87451f350156d274":{
      "scriptId":"u5"},
    "0275acebec434a8d938a877afad3aadf":{
      "scriptId":"u6"},
    "9e72aa77c1674c47a639f067386bf174":{
      "scriptId":"u7"},
    "93ee4a5d3aee49608d137f05dc5414e1":{
      "scriptId":"u8"},
    "2d3a807b9af94be98faafdd89adeb4e8":{
      "scriptId":"u9"},
    "8ffda3b02aaa4ef4b18f60502deecd61":{
      "scriptId":"u10"},
    "ce92cc4aeda64b15a6e209617c8d82eb":{
      "scriptId":"u11"},
    "d82672a4ca8e49b0abadfb22e4a6675b":{
      "scriptId":"u12"},
    "4100e7f64ad5474daf9352e95b3691e0":{
      "scriptId":"u13"},
    "80013b9cd2d94a73aa8319a7e12f1ecc":{
      "scriptId":"u14"},
    "efcc67dc48d34191817b59a17bb0c8b0":{
      "scriptId":"u15"},
    "af8ae9e377ca45cd8bb1504cba662457":{
      "scriptId":"u16"},
    "1ab6752788644b97b9683c5fe02d2bed":{
      "scriptId":"u17"},
    "3529be1874024d68938e25d9d64ad046":{
      "scriptId":"u18"},
    "079c72b798734f78be98c8de9ed92264":{
      "scriptId":"u19"},
    "34e07ca00754422a85ae2f2021b29599":{
      "scriptId":"u20"},
    "3d9280104db44a5eaa1bbf9cb41f7f0b":{
      "scriptId":"u21"},
    "c69bbbe8f8dd430f880dea40d2dbb84a":{
      "scriptId":"u22"},
    "6e14cc570b7b456a91ea167352846383":{
      "scriptId":"u23"},
    "d23765edf5674b779fb3933e2c5cf2a6":{
      "scriptId":"u24"},
    "9b18621e06324713b9c546d273b95883":{
      "scriptId":"u25"},
    "b4ee9555810f4661b01e1a65f0cbc88d":{
      "scriptId":"u26"},
    "acff0a79895244d58e14808395d0d261":{
      "scriptId":"u27"}}});