$axure.loadCurrentPage({
  "url":"出售详情页.html",
  "generationDate":new Date(1432921474425.17),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c6ff7140c12140c7b74b03f6dd5e4637",
    "type":"Axure:Page",
    "name":"出售详情页",
    "notes":{
      "默认":"<p><span>1.价格输入框限制1~999.</span></p><p><span>2.15点以后 ，出售时间从第二开始计算。</span></p>"},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dbca6329069d41dfa9fa1245eae7c700",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":106,
              "height":548}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae87117ebf0043afb586df5df4ece257",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":106,
                  "height":548}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 买时间",
                      "target":{
                        "targetType":"page",
                        "url":"买时间.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/出售详情页/u0.png"}},
{
          "id":"6949b8d72d284419b3e5bf367de7b89d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":0},
            "size":{
              "width":216,
              "height":548}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b8323ab1bb140efb09618188113d109",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":106,
                  "y":0},
                "size":{
                  "width":216,
                  "height":548}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/出售详情页/u2.jpg"}},
{
          "id":"0d9b717e44fa44d79467b88d15b63ff8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":158,
              "y":10},
            "size":{
              "width":112,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e8e0f5db8bf4fea97f41202cdd05817",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":158,
                  "y":10},
                "size":{
                  "width":112,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b432ce15adef4aefb5c6481694f6f596",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":147,
              "y":181},
            "size":{
              "width":139,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76b182958e1a41768e826d4a4020f653",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":147,
                  "y":181},
                "size":{
                  "width":139,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"572af36d58a745e2a3fc1d6a1276710a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":140,
              "y":205},
            "size":{
              "width":146,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66fc5efa7b03467389e243bfdac82561",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":205},
                "size":{
                  "width":146,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"67974e2e57e543feb6698b6556d8610c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":140,
              "y":310},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7bb73752b8e483fa047db5ac31c6b01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":310},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00e19dc2c8834cc3a00d9483e59b4bfe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":126,
              "y":264},
            "size":{
              "width":184,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0c95a780d8142c8af442fd5c10b86af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":126,
                  "y":264},
                "size":{
                  "width":184,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b68878ddc00473b8381a1b4d6540793",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"72px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCBC9CA,
              "opacity":1},
            "location":{
              "x":137,
              "y":361},
            "size":{
              "width":132,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ee0ee3e261e47c695a054e2da496598",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"72px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCBC9CA,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":361},
                "size":{
                  "width":132,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"47a75bde965f4ce49e51cdc1dd450fda",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":263,
              "y":401},
            "size":{
              "width":27,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55abb58eceb64699bf780cd6b3de45f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":263,
                  "y":401},
                "size":{
                  "width":27,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c153dffcab654c0ba68ea08acde4edd3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":443},
            "size":{
              "width":216,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4accc556ea5c4086b0633aa877f34ca0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":106,
                  "y":443},
                "size":{
                  "width":216,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/出售详情页/u18.png"}},
{
          "id":"f1368acfdeea4ab8983239018f4152c6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":498},
            "size":{
              "width":216,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29eb1575459f461fb5de39961618e1fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":106,
                  "y":498},
                "size":{
                  "width":216,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/出售详情页/u18.png"}},
{
          "id":"43feab8c75aa4caba9e3e2b5e99f7fe4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":109,
              "y":444},
            "size":{
              "width":210,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1e5e0779ed1477a8ed855c9b33bd177",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":109,
                  "y":444},
                "size":{
                  "width":210,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 支付页面",
                      "target":{
                        "targetType":"page",
                        "url":"支付页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ff662573b944cc4ba6837f1f370b712",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":109,
              "y":499},
            "size":{
              "width":210,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"453a274faf8f4448b0bfb85ca2f7590e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":109,
                  "y":499},
                "size":{
                  "width":210,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 买时间",
                      "target":{
                        "targetType":"page",
                        "url":"买时间.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4869545f9a7e4616b8ad518de7dc093c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":140,
              "y":330},
            "size":{
              "width":166,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d67c5b5911684688b1d5cb12e94b57fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":330},
                "size":{
                  "width":166,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "dbca6329069d41dfa9fa1245eae7c700":{
      "scriptId":"u0"},
    "ae87117ebf0043afb586df5df4ece257":{
      "scriptId":"u1"},
    "6949b8d72d284419b3e5bf367de7b89d":{
      "scriptId":"u2"},
    "2b8323ab1bb140efb09618188113d109":{
      "scriptId":"u3"},
    "0d9b717e44fa44d79467b88d15b63ff8":{
      "scriptId":"u4"},
    "8e8e0f5db8bf4fea97f41202cdd05817":{
      "scriptId":"u5"},
    "b432ce15adef4aefb5c6481694f6f596":{
      "scriptId":"u6"},
    "76b182958e1a41768e826d4a4020f653":{
      "scriptId":"u7"},
    "572af36d58a745e2a3fc1d6a1276710a":{
      "scriptId":"u8"},
    "66fc5efa7b03467389e243bfdac82561":{
      "scriptId":"u9"},
    "67974e2e57e543feb6698b6556d8610c":{
      "scriptId":"u10"},
    "d7bb73752b8e483fa047db5ac31c6b01":{
      "scriptId":"u11"},
    "00e19dc2c8834cc3a00d9483e59b4bfe":{
      "scriptId":"u12"},
    "c0c95a780d8142c8af442fd5c10b86af":{
      "scriptId":"u13"},
    "0b68878ddc00473b8381a1b4d6540793":{
      "scriptId":"u14"},
    "9ee0ee3e261e47c695a054e2da496598":{
      "scriptId":"u15"},
    "47a75bde965f4ce49e51cdc1dd450fda":{
      "scriptId":"u16"},
    "55abb58eceb64699bf780cd6b3de45f6":{
      "scriptId":"u17"},
    "c153dffcab654c0ba68ea08acde4edd3":{
      "scriptId":"u18"},
    "4accc556ea5c4086b0633aa877f34ca0":{
      "scriptId":"u19"},
    "f1368acfdeea4ab8983239018f4152c6":{
      "scriptId":"u20"},
    "29eb1575459f461fb5de39961618e1fe":{
      "scriptId":"u21"},
    "43feab8c75aa4caba9e3e2b5e99f7fe4":{
      "scriptId":"u22"},
    "f1e5e0779ed1477a8ed855c9b33bd177":{
      "scriptId":"u23"},
    "5ff662573b944cc4ba6837f1f370b712":{
      "scriptId":"u24"},
    "453a274faf8f4448b0bfb85ca2f7590e":{
      "scriptId":"u25"},
    "4869545f9a7e4616b8ad518de7dc093c":{
      "scriptId":"u26"},
    "d67c5b5911684688b1d5cb12e94b57fc":{
      "scriptId":"u27"}}});