$axure.loadCurrentPage({
  "url":"通知页面.html",
  "generationDate":new Date(1432237665999.56),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0cd7882cee2e416e8d0a1f803fcb5c19",
    "type":"Axure:Page",
    "name":"通知页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"52b1dd882aa04604acd2002a5d0342db",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"761ca04a2f2e47409a9e1aef0a6e2f8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户详情页（交易中）/u2.png"}},
{
          "id":"fdda71db18064d7481fab8ae92c6006c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":44},
            "size":{
              "width":320,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81948ab74ac142e3b8942e59be38a356",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":44},
                "size":{
                  "width":320,
                  "height":106}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户详情页（交易中）/u4.png"}},
{
          "id":"005a99a6ec76427abf1c85351784de12",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":272,
              "y":5},
            "size":{
              "width":43,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0174b887f17b47b7948ba5cb853a8310",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":272,
                  "y":5},
                "size":{
                  "width":43,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 买卖时间 向下滑动 500 毫秒,<br>(Image) 向下滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["e7121de1e03b477bbc9ca963d6cb0301"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}},
{
                          "objectPath":["9cf00ab1fc0e4c768ee23fd4c0bcef79"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d60624073a64b30b4f158a9a0c7fc96",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":8,
              "y":4},
            "size":{
              "width":44,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"009d36d1058b4bd7833685976f1a97d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":8,
                  "y":4},
                "size":{
                  "width":44,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 左侧边栏",
                      "target":{
                        "targetType":"page",
                        "url":"左侧边栏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3378973ba42458981751b06a571fdc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":122,
              "y":5},
            "size":{
              "width":76,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7277d83b8d054700a565cc34507d8e3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":122,
                  "y":5},
                "size":{
                  "width":76,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0676fbbd17c34a07a659befb2fdba86d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":159},
            "size":{
              "width":61,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fe90b5febde43b5b84da0260aecc3b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":159},
                "size":{
                  "width":61,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商户信息介绍",
                      "target":{
                        "targetType":"page",
                        "url":"商户信息介绍.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商户详情页（交易中）/u12.png"}},
{
          "id":"fcc1ec4e5a3f4dbca78c6709fd2b32fd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":92,
              "y":159},
            "size":{
              "width":61,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23a9be86645241d7bff49a58927270dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":92,
                  "y":159},
                "size":{
                  "width":61,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商户详情页（交易中）",
                      "target":{
                        "targetType":"page",
                        "url":"商户详情页（交易中）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商户详情页（交易中）/u14.png"}},
{
          "id":"c6f86cafc03f461380efcf5388ec9f87",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":159},
            "size":{
              "width":61,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"871adcfd7b0c4bc0a9d59f0639dde856",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":159},
                "size":{
                  "width":61,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 通知页面",
                      "target":{
                        "targetType":"page",
                        "url":"通知页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商户详情页（交易中）/u16.png"}},
{
          "id":"3e6318e535724d0bba22d3706b454790",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":259,
              "y":159},
            "size":{
              "width":61,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53d07e8765a347acaf988f965c54af7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":259,
                  "y":159},
                "size":{
                  "width":61,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课程页面",
                      "target":{
                        "targetType":"page",
                        "url":"课程页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商户详情页（交易中）/u18.png"}},
{
          "id":"d26c58be7d2d4217b3435df0cfcf60d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":130,
              "y":60},
            "size":{
              "width":160,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fe19b89da3d407280d1614da7bccac7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":130,
                  "y":60},
                "size":{
                  "width":160,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7258da4075647eab3ac521b97f51e58",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":146,
              "y":105},
            "size":{
              "width":160,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac2b72a40f7c42abb8f61cc2a72ec120",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":146,
                  "y":105},
                "size":{
                  "width":160,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85904f98ac9e4e96939a8d4dbf4b7cbb",
          "label":"ButtonBigSecondary",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontSize":"18px",
            "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
            "opacity":"0.6",
            "location":{
              "x":190,
              "y":44},
            "size":{
              "width":130,
              "height":76},
            "visible":false,
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cba065f4f47483ea7f1a668b483e3e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"18px",
                "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
                "opacity":"0.6",
                "location":{
                  "x":190,
                  "y":44},
                "size":{
                  "width":130,
                  "height":76},
                "visible":false,
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/buttonbigsecondary_u34.png"}},
{
          "id":"e7121de1e03b477bbc9ca963d6cb0301",
          "label":"买卖时间",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":190,
              "y":44},
            "size":{
              "width":130,
              "height":76},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"8b81ed46162b4b0481d7eb6f824fcdda",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"9cf00ab1fc0e4c768ee23fd4c0bcef79",
                  "label":"",
                  "parentDynamicPanel":"e7121de1e03b477bbc9ca963d6cb0301",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":130,
                      "height":76}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3b3f084433a546c992599be6dff798f3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e7121de1e03b477bbc9ca963d6cb0301",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":130,
                          "height":76}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/买时间/u37.png"}},
{
                  "id":"aac892930579432e8aaaeec89dc1fa55",
                  "label":"",
                  "parentDynamicPanel":"e7121de1e03b477bbc9ca963d6cb0301",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0",
                    "location":{
                      "x":0,
                      "y":1},
                    "size":{
                      "width":130,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2df36dedcc774062a9734234885c5f44",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e7121de1e03b477bbc9ca963d6cb0301",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0",
                        "location":{
                          "x":0,
                          "y":1},
                        "size":{
                          "width":130,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 发起出售请求页",
                              "target":{
                                "targetType":"page",
                                "url":"发起出售请求页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"80d9549c7b7c41dd84070d39abd1dc08",
                  "label":"",
                  "parentDynamicPanel":"e7121de1e03b477bbc9ca963d6cb0301",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0",
                    "location":{
                      "x":0,
                      "y":41},
                    "size":{
                      "width":130,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4770ef27f2154bedb12c5a4c1d4d8959",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e7121de1e03b477bbc9ca963d6cb0301",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0",
                        "location":{
                          "x":0,
                          "y":41},
                        "size":{
                          "width":130,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 发起购买请求页",
                              "target":{
                                "targetType":"page",
                                "url":"发起购买请求页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"82327232a7604ca8a6f8ef36c9481cca",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":147},
            "size":{
              "width":312,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户详情页（交易中）/u33_line.png"}},
{
          "id":"cf052e2375b44b0283bd6953aecacbe4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":227},
            "size":{
              "width":312,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户详情页（交易中）/u33_line.png"}},
{
          "id":"3299cd03f9fa46819312be9999dd49a4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":233},
            "size":{
              "width":320,
              "height":328}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fcb67e9510d45778a048fe2fa96f25e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":233},
                "size":{
                  "width":320,
                  "height":328}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通知页面/u33.png"}},
{
          "id":"0ffcea05c2da40c7aaea2963d7221f5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":13,
              "y":233},
            "size":{
              "width":36,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24c2d6fa06c643f1af635ee25bc585c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":13,
                  "y":233},
                "size":{
                  "width":36,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae90d10041a5442a9f2e79ae9d0f9173",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF67C7BB,
              "opacity":1},
            "location":{
              "x":14,
              "y":263},
            "size":{
              "width":300,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34e0bd0541a7483ba7214c83e97424ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF67C7BB,
                  "opacity":1},
                "location":{
                  "x":14,
                  "y":263},
                "size":{
                  "width":300,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20e9609e497447fab948033659b3ebee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF67C7BB,
              "opacity":1},
            "location":{
              "x":14,
              "y":340},
            "size":{
              "width":300,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c676125351444c9baf324e236d6b3ec8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF67C7BB,
                  "opacity":1},
                "location":{
                  "x":14,
                  "y":340},
                "size":{
                  "width":300,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3f25c64aedeb4d268bb8157b2456153b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF67C7BB,
              "opacity":1},
            "location":{
              "x":14,
              "y":417},
            "size":{
              "width":300,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d29970f8f104b428a850fae5d5d1467",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF67C7BB,
                  "opacity":1},
                "location":{
                  "x":14,
                  "y":417},
                "size":{
                  "width":300,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08ad1860d0e94df089cc49146ae444ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF67C7BB,
              "opacity":1},
            "location":{
              "x":14,
              "y":494},
            "size":{
              "width":300,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1214a982cfaf4832a7cabe930ce39e91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF67C7BB,
                  "opacity":1},
                "location":{
                  "x":14,
                  "y":494},
                "size":{
                  "width":300,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "52b1dd882aa04604acd2002a5d0342db":{
      "scriptId":"u0"},
    "761ca04a2f2e47409a9e1aef0a6e2f8d":{
      "scriptId":"u1"},
    "fdda71db18064d7481fab8ae92c6006c":{
      "scriptId":"u2"},
    "81948ab74ac142e3b8942e59be38a356":{
      "scriptId":"u3"},
    "005a99a6ec76427abf1c85351784de12":{
      "scriptId":"u4"},
    "0174b887f17b47b7948ba5cb853a8310":{
      "scriptId":"u5"},
    "5d60624073a64b30b4f158a9a0c7fc96":{
      "scriptId":"u6"},
    "009d36d1058b4bd7833685976f1a97d0":{
      "scriptId":"u7"},
    "b3378973ba42458981751b06a571fdc7":{
      "scriptId":"u8"},
    "7277d83b8d054700a565cc34507d8e3e":{
      "scriptId":"u9"},
    "0676fbbd17c34a07a659befb2fdba86d":{
      "scriptId":"u10"},
    "3fe90b5febde43b5b84da0260aecc3b3":{
      "scriptId":"u11"},
    "fcc1ec4e5a3f4dbca78c6709fd2b32fd":{
      "scriptId":"u12"},
    "23a9be86645241d7bff49a58927270dd":{
      "scriptId":"u13"},
    "c6f86cafc03f461380efcf5388ec9f87":{
      "scriptId":"u14"},
    "871adcfd7b0c4bc0a9d59f0639dde856":{
      "scriptId":"u15"},
    "3e6318e535724d0bba22d3706b454790":{
      "scriptId":"u16"},
    "53d07e8765a347acaf988f965c54af7b":{
      "scriptId":"u17"},
    "d26c58be7d2d4217b3435df0cfcf60d3":{
      "scriptId":"u18"},
    "3fe19b89da3d407280d1614da7bccac7":{
      "scriptId":"u19"},
    "a7258da4075647eab3ac521b97f51e58":{
      "scriptId":"u20"},
    "ac2b72a40f7c42abb8f61cc2a72ec120":{
      "scriptId":"u21"},
    "85904f98ac9e4e96939a8d4dbf4b7cbb":{
      "scriptId":"u22"},
    "5cba065f4f47483ea7f1a668b483e3e4":{
      "scriptId":"u23"},
    "e7121de1e03b477bbc9ca963d6cb0301":{
      "scriptId":"u24"},
    "9cf00ab1fc0e4c768ee23fd4c0bcef79":{
      "scriptId":"u25"},
    "3b3f084433a546c992599be6dff798f3":{
      "scriptId":"u26"},
    "aac892930579432e8aaaeec89dc1fa55":{
      "scriptId":"u27"},
    "2df36dedcc774062a9734234885c5f44":{
      "scriptId":"u28"},
    "80d9549c7b7c41dd84070d39abd1dc08":{
      "scriptId":"u29"},
    "4770ef27f2154bedb12c5a4c1d4d8959":{
      "scriptId":"u30"},
    "82327232a7604ca8a6f8ef36c9481cca":{
      "scriptId":"u31"},
    "cf052e2375b44b0283bd6953aecacbe4":{
      "scriptId":"u32"},
    "3299cd03f9fa46819312be9999dd49a4":{
      "scriptId":"u33"},
    "0fcb67e9510d45778a048fe2fa96f25e":{
      "scriptId":"u34"},
    "0ffcea05c2da40c7aaea2963d7221f5f":{
      "scriptId":"u35"},
    "24c2d6fa06c643f1af635ee25bc585c4":{
      "scriptId":"u36"},
    "ae90d10041a5442a9f2e79ae9d0f9173":{
      "scriptId":"u37"},
    "34e0bd0541a7483ba7214c83e97424ef":{
      "scriptId":"u38"},
    "20e9609e497447fab948033659b3ebee":{
      "scriptId":"u39"},
    "c676125351444c9baf324e236d6b3ec8":{
      "scriptId":"u40"},
    "3f25c64aedeb4d268bb8157b2456153b":{
      "scriptId":"u41"},
    "8d29970f8f104b428a850fae5d5d1467":{
      "scriptId":"u42"},
    "08ad1860d0e94df089cc49146ae444ba":{
      "scriptId":"u43"},
    "1214a982cfaf4832a7cabe930ce39e91":{
      "scriptId":"u44"}}});