$axure.loadCurrentPage({
  "url":"通知页面.html",
  "generationDate":new Date(1430762529751.62),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0cd7882cee2e416e8d0a1f803fcb5c19",
    "type":"Axure:Page",
    "name":"通知页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"80d70167bae84037b2514d51efcd1bde",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":319,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e996c51ff06d41719b6d95ebd6359829",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":319,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通知页面/u0.png"}},
{
          "id":"a96d9f76cf734840aede807237b14ac1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":37},
            "size":{
              "width":22,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbf96ab02ac04062b06787fb1e2e7c2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":37},
                "size":{
                  "width":22,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 左侧边栏",
                      "target":{
                        "targetType":"page",
                        "url":"左侧边栏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/左侧边栏/u2.png"}},
{
          "id":"a760d1a6fae2480cac366ea4a5ea3d2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":269,
              "y":26},
            "size":{
              "width":43,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d92f3c5296a9406c869eac1c6a118149",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":269,
                  "y":26},
                "size":{
                  "width":43,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 买卖时间 向下滑动 500 毫秒,<br>(Image) 向下滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["ffbaaa171a53457e85c3def0c563d391"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}},
{
                          "objectPath":["f4bd0081da594cf78d00f9894321752f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f4a2c6f5ba645c689e7c4dec51aefc3",
          "label":"ButtonBigSecondary",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontSize":"18px",
            "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
            "opacity":"0.6",
            "location":{
              "x":188,
              "y":65},
            "size":{
              "width":130,
              "height":76},
            "visible":false,
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2510e33bd9c4496b3ca9597388a84f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"18px",
                "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
                "opacity":"0.6",
                "location":{
                  "x":188,
                  "y":65},
                "size":{
                  "width":130,
                  "height":76},
                "visible":false,
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/buttonbigsecondary_u6.png"}},
{
          "id":"ffbaaa171a53457e85c3def0c563d391",
          "label":"买卖时间",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":188,
              "y":65},
            "size":{
              "width":130,
              "height":76},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"222fef922ef641448702615a2d769fe5",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f4bd0081da594cf78d00f9894321752f",
                  "label":"",
                  "parentDynamicPanel":"ffbaaa171a53457e85c3def0c563d391",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":130,
                      "height":76}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d0e0bc3c50b84febb54be3130ea195b0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ffbaaa171a53457e85c3def0c563d391",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":130,
                          "height":76}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/买时间/u9.png"}},
{
                  "id":"8ec08be45c264d3d8e60cc5f7b25a957",
                  "label":"",
                  "parentDynamicPanel":"ffbaaa171a53457e85c3def0c563d391",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0",
                    "location":{
                      "x":0,
                      "y":1},
                    "size":{
                      "width":130,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"86910583bb374e44a2b6d86f753031ac",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ffbaaa171a53457e85c3def0c563d391",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0",
                        "location":{
                          "x":0,
                          "y":1},
                        "size":{
                          "width":130,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 发起出售请求页",
                              "target":{
                                "targetType":"page",
                                "url":"发起出售请求页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"71235149cc924541b12be8775afc1e0e",
                  "label":"",
                  "parentDynamicPanel":"ffbaaa171a53457e85c3def0c563d391",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0",
                    "location":{
                      "x":0,
                      "y":41},
                    "size":{
                      "width":130,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ab74408552ab43f0aa591a4c51a84a5d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ffbaaa171a53457e85c3def0c563d391",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0",
                        "location":{
                          "x":0,
                          "y":41},
                        "size":{
                          "width":130,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 发起购买请求页",
                              "target":{
                                "targetType":"page",
                                "url":"发起购买请求页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"717cf287ff0d4e19b6fbb2be5c68d689",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":198},
            "size":{
              "width":61,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eeaa40dfae1a4ef98a3056dec9856c39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":198},
                "size":{
                  "width":61,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商户信息介绍",
                      "target":{
                        "targetType":"page",
                        "url":"商户信息介绍.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商户详情页（交易中）/u19.png"}},
{
          "id":"2dfbe09ef8064d9c92ee370be80fe236",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":89,
              "y":197},
            "size":{
              "width":61,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91d7cc9be65c451eac4471cfc195ad38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":89,
                  "y":197},
                "size":{
                  "width":61,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商户详情页（交易中）",
                      "target":{
                        "targetType":"page",
                        "url":"商户详情页（交易中）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商户详情页（交易中）/u21.png"}},
{
          "id":"0c14dcf4120945beb1335c4ebcab8fa0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":164,
              "y":197},
            "size":{
              "width":60,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c88f5f5eee5c47e18b96e720a2f4e06f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":164,
                  "y":197},
                "size":{
                  "width":60,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 通知页面",
                      "target":{
                        "targetType":"page",
                        "url":"通知页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89681df98ad249bf902d60a54406a800",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":237,
              "y":197},
            "size":{
              "width":61,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"301f1b00bbaf4b24ada6d45988c54561",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":237,
                  "y":197},
                "size":{
                  "width":61,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课程页面",
                      "target":{
                        "targetType":"page",
                        "url":"课程页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商户详情页（交易中）/u25.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "80d70167bae84037b2514d51efcd1bde":{
      "scriptId":"u0"},
    "e996c51ff06d41719b6d95ebd6359829":{
      "scriptId":"u1"},
    "a96d9f76cf734840aede807237b14ac1":{
      "scriptId":"u2"},
    "bbf96ab02ac04062b06787fb1e2e7c2c":{
      "scriptId":"u3"},
    "a760d1a6fae2480cac366ea4a5ea3d2d":{
      "scriptId":"u4"},
    "d92f3c5296a9406c869eac1c6a118149":{
      "scriptId":"u5"},
    "9f4a2c6f5ba645c689e7c4dec51aefc3":{
      "scriptId":"u6"},
    "d2510e33bd9c4496b3ca9597388a84f2":{
      "scriptId":"u7"},
    "ffbaaa171a53457e85c3def0c563d391":{
      "scriptId":"u8"},
    "f4bd0081da594cf78d00f9894321752f":{
      "scriptId":"u9"},
    "d0e0bc3c50b84febb54be3130ea195b0":{
      "scriptId":"u10"},
    "8ec08be45c264d3d8e60cc5f7b25a957":{
      "scriptId":"u11"},
    "86910583bb374e44a2b6d86f753031ac":{
      "scriptId":"u12"},
    "71235149cc924541b12be8775afc1e0e":{
      "scriptId":"u13"},
    "ab74408552ab43f0aa591a4c51a84a5d":{
      "scriptId":"u14"},
    "717cf287ff0d4e19b6fbb2be5c68d689":{
      "scriptId":"u15"},
    "eeaa40dfae1a4ef98a3056dec9856c39":{
      "scriptId":"u16"},
    "2dfbe09ef8064d9c92ee370be80fe236":{
      "scriptId":"u17"},
    "91d7cc9be65c451eac4471cfc195ad38":{
      "scriptId":"u18"},
    "0c14dcf4120945beb1335c4ebcab8fa0":{
      "scriptId":"u19"},
    "c88f5f5eee5c47e18b96e720a2f4e06f":{
      "scriptId":"u20"},
    "89681df98ad249bf902d60a54406a800":{
      "scriptId":"u21"},
    "301f1b00bbaf4b24ada6d45988c54561":{
      "scriptId":"u22"}}});