$axure.loadCurrentPage({
  "url":"健身机构.html",
  "generationDate":new Date(1430762529236.59),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e8a7bf326e864c38b4efe740c718fede",
    "type":"Axure:Page",
    "name":"健身机构",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4ef068768cac42eba3e1b9321bd62af1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"399f39aa17ab40e297c7c8b543ebc6fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健身机构/u0.png"}},
{
          "id":"7622abc5206a44fb9fee3d59102cc461",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":22,
              "y":193},
            "size":{
              "width":76,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d928d52253a436992e792b95d804894",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":22,
                  "y":193},
                "size":{
                  "width":76,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 品牌介绍页",
                      "target":{
                        "targetType":"page",
                        "url":"品牌介绍页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4539ab1bfc6d4186b2b583b99dd7ce13",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":122,
              "y":193},
            "size":{
              "width":76,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e72322dbe3224f82a7b60e1d17c36bd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":122,
                  "y":193},
                "size":{
                  "width":76,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 品牌介绍页",
                      "target":{
                        "targetType":"page",
                        "url":"品牌介绍页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d2ecfc25e30b426e99f40abe1548e3b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":224,
              "y":193},
            "size":{
              "width":76,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe7f6f7a2a504a5091ab0ca358cd99be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":224,
                  "y":193},
                "size":{
                  "width":76,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商户详情页（交易中）",
                      "target":{
                        "targetType":"page",
                        "url":"商户详情页（交易中）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d32250596e8a42c090c23a24273ef0bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":21,
              "y":284},
            "size":{
              "width":76,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ff691589cf34d3ca7bf4fc68f7f586c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":21,
                  "y":284},
                "size":{
                  "width":76,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 品牌介绍页",
                      "target":{
                        "targetType":"page",
                        "url":"品牌介绍页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4fc3cad424fd4ca88da62972b8307e61",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":121,
              "y":284},
            "size":{
              "width":76,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07bb4f8dae064640aff1e05299fcbcf6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":121,
                  "y":284},
                "size":{
                  "width":76,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 品牌介绍页",
                      "target":{
                        "targetType":"page",
                        "url":"品牌介绍页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f46102dbc204c3b8b04722e71dc1e8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":223,
              "y":284},
            "size":{
              "width":76,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c5d1ab2dee94f3a92a17c144f19fa2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":223,
                  "y":284},
                "size":{
                  "width":76,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 品牌介绍页",
                      "target":{
                        "targetType":"page",
                        "url":"品牌介绍页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d75c53729b14023ac3288c11bd1ce66",
          "label":"ButtonBigSecondary",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontSize":"18px",
            "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
            "opacity":"0.6",
            "location":{
              "x":224,
              "y":98},
            "size":{
              "width":87,
              "height":102},
            "visible":false,
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52a8b9e2c90444678b3abc885108553c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"18px",
                "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
                "opacity":"0.6",
                "location":{
                  "x":224,
                  "y":98},
                "size":{
                  "width":87,
                  "height":102},
                "visible":false,
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索页_切换城市/buttonbigsecondary_u2.png"}},
{
          "id":"7cf3f858e1b1466ba7af22dd2581ba8e",
          "label":"健身机构_区域列表",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":224,
              "y":98},
            "size":{
              "width":87,
              "height":102},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"2e644c076d46418bbf1960670c4f5bae",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"72db0a1b066245a0bb72ed9a1422084a",
                  "label":"",
                  "parentDynamicPanel":"7cf3f858e1b1466ba7af22dd2581ba8e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":87,
                      "height":102}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cb2397378ee64cee9e4327679abed3b4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7cf3f858e1b1466ba7af22dd2581ba8e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":87,
                          "height":102}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 健身机构_区域列表,<br>(Image)",
                              "objectsToFades":[{
                                  "objectPath":["7cf3f858e1b1466ba7af22dd2581ba8e"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["72db0a1b066245a0bb72ed9a1422084a"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/搜索页_切换城市/u5.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"0121db15a3144da3a65ab4b5c3d429d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":0,
              "y":71},
            "size":{
              "width":310,
              "height":27},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25ed64cd668641f5982f6efa8028e369",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":0,
                  "y":71},
                "size":{
                  "width":310,
                  "height":27},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 健身机构_区域列表 向下滑动 500 毫秒,<br>(Image) 向下滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["7cf3f858e1b1466ba7af22dd2581ba8e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}},
{
                          "objectPath":["72db0a1b066245a0bb72ed9a1422084a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f8b3a88b150e4e3b8d09577543a9075a",
          "label":"ButtonBigSecondary",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontSize":"18px",
            "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
            "opacity":"0.6",
            "location":{
              "x":224,
              "y":133},
            "size":{
              "width":87,
              "height":102},
            "visible":false,
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c59e9cc820a488e9b77c6f98ecda5d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"18px",
                "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
                "opacity":"0.6",
                "location":{
                  "x":224,
                  "y":133},
                "size":{
                  "width":87,
                  "height":102},
                "visible":false,
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索页_切换城市/buttonbigsecondary_u2.png"}},
{
          "id":"b7c806ce75044433a4c3a9798d42ed6a",
          "label":"健身机构_选择品牌",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":224,
              "y":133},
            "size":{
              "width":87,
              "height":102},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"4e7f42c151e34e419bebebcf55392182",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"cc911b00f1ea460fb023dced77ad9e47",
                  "label":"",
                  "parentDynamicPanel":"b7c806ce75044433a4c3a9798d42ed6a",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":87,
                      "height":102}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9a0a6ffbe9b249e1a80e910ba6f6cefe",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b7c806ce75044433a4c3a9798d42ed6a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":87,
                          "height":102}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 (Image),<br>健身机构_选择品牌",
                              "objectsToFades":[{
                                  "objectPath":["cc911b00f1ea460fb023dced77ad9e47"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["b7c806ce75044433a4c3a9798d42ed6a"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/健身机构/u24.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"480ffccd3913438fac00b2fb13330d76",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":2,
              "y":106},
            "size":{
              "width":208,
              "height":27},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9116ccad40f42478e615c2bdf836a78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":2,
                  "y":106},
                "size":{
                  "width":208,
                  "height":27},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 健身机构_选择品牌 向下滑动 500 毫秒,<br>(Image) 向下滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["b7c806ce75044433a4c3a9798d42ed6a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}},
{
                          "objectPath":["cc911b00f1ea460fb023dced77ad9e47"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef64a00666e3413f8885aa18a7bdf6a8",
          "label":"ButtonBigSecondary",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontSize":"18px",
            "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
            "opacity":"0.6",
            "location":{
              "x":224,
              "y":168},
            "size":{
              "width":87,
              "height":102},
            "visible":false,
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4772d2ae91c84f96939488cbceba217a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"18px",
                "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
                "opacity":"0.6",
                "location":{
                  "x":224,
                  "y":168},
                "size":{
                  "width":87,
                  "height":102},
                "visible":false,
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索页_切换城市/buttonbigsecondary_u2.png"}},
{
          "id":"9515893632aa4389bee88783eb78234e",
          "label":"健身机构_选择门店",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":224,
              "y":168},
            "size":{
              "width":87,
              "height":102},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"6e371f4174b14525b42b542092894837",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6519738b6a3e42788088f4917c5017c2",
                  "label":"",
                  "parentDynamicPanel":"9515893632aa4389bee88783eb78234e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":87,
                      "height":102}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5813c6cb9162496e9eace4efc17925ae",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9515893632aa4389bee88783eb78234e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":87,
                          "height":102}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 健身机构_选择门店,<br>(Image)",
                              "objectsToFades":[{
                                  "objectPath":["9515893632aa4389bee88783eb78234e"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["6519738b6a3e42788088f4917c5017c2"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/健身机构/u31.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"9be8480aa8bd410d8fde4115ecd1b443",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":10,
              "y":801},
            "size":{
              "width":310,
              "height":27},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2f843b40e7847538109ec3f30c1571e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":10,
                  "y":801},
                "size":{
                  "width":310,
                  "height":27},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 健身机构_选择门店 向下滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["9515893632aa4389bee88783eb78234e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5bf18680b2a47bc99b4e9c20ad44cb2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":6,
              "y":141},
            "size":{
              "width":208,
              "height":27},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58c5accec08f4398a3db1d134a0f7970",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":6,
                  "y":141},
                "size":{
                  "width":208,
                  "height":27},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (Image),<br>健身机构_选择门店 向下滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["6519738b6a3e42788088f4917c5017c2"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["9515893632aa4389bee88783eb78234e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a20a46f666314e0ea5f534fbb00f227f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":37},
            "size":{
              "width":22,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a1ea5648b164ad2970a4d0b5b9bbcb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":37},
                "size":{
                  "width":22,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 左侧边栏",
                      "target":{
                        "targetType":"page",
                        "url":"左侧边栏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/左侧边栏/u2.png"}},
{
          "id":"a73a44c17dc54e35a02d8f9227e857a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":277,
              "y":26},
            "size":{
              "width":43,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"318926e8a452484d85a59358df7cb6cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":277,
                  "y":26},
                "size":{
                  "width":43,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 品牌介绍页",
                      "target":{
                        "targetType":"page",
                        "url":"品牌介绍页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c733a24ab5c54b279418ae9a4ba3109a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":16,
              "y":370},
            "size":{
              "width":76,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9b9d2b912564a58847046793e5f69be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":16,
                  "y":370},
                "size":{
                  "width":76,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 品牌介绍页",
                      "target":{
                        "targetType":"page",
                        "url":"品牌介绍页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65fb7845a00143e49073e0886b46128a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":116,
              "y":370},
            "size":{
              "width":76,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f679838ac254986bc9521bb73ff4fd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":116,
                  "y":370},
                "size":{
                  "width":76,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 品牌介绍页",
                      "target":{
                        "targetType":"page",
                        "url":"品牌介绍页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3c9324fef604706a5ee60657250e965",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":218,
              "y":370},
            "size":{
              "width":76,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0897a8f975a44e4c882f4a673b8ac73d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":218,
                  "y":370},
                "size":{
                  "width":76,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 品牌介绍页",
                      "target":{
                        "targetType":"page",
                        "url":"品牌介绍页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be1a6c246458459e9e4f11245037118f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":20,
              "y":460},
            "size":{
              "width":76,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e2809fa41b14cbd9fba1142bd535c3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":20,
                  "y":460},
                "size":{
                  "width":76,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 品牌介绍页",
                      "target":{
                        "targetType":"page",
                        "url":"品牌介绍页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89020348f443413aa45fc1bdcbd4c32e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":120,
              "y":460},
            "size":{
              "width":76,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4334fdfedcb415996d1d22c1bf1d710",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":120,
                  "y":460},
                "size":{
                  "width":76,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 品牌介绍页",
                      "target":{
                        "targetType":"page",
                        "url":"品牌介绍页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bdb8c86188df4d21a3907cb103995910",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":222,
              "y":460},
            "size":{
              "width":76,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae211a644d8e481ba55f75c86ef12bb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":222,
                  "y":460},
                "size":{
                  "width":76,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 品牌介绍页",
                      "target":{
                        "targetType":"page",
                        "url":"品牌介绍页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "4ef068768cac42eba3e1b9321bd62af1":{
      "scriptId":"u0"},
    "399f39aa17ab40e297c7c8b543ebc6fd":{
      "scriptId":"u1"},
    "7622abc5206a44fb9fee3d59102cc461":{
      "scriptId":"u2"},
    "1d928d52253a436992e792b95d804894":{
      "scriptId":"u3"},
    "4539ab1bfc6d4186b2b583b99dd7ce13":{
      "scriptId":"u4"},
    "e72322dbe3224f82a7b60e1d17c36bd4":{
      "scriptId":"u5"},
    "d2ecfc25e30b426e99f40abe1548e3b8":{
      "scriptId":"u6"},
    "fe7f6f7a2a504a5091ab0ca358cd99be":{
      "scriptId":"u7"},
    "d32250596e8a42c090c23a24273ef0bd":{
      "scriptId":"u8"},
    "6ff691589cf34d3ca7bf4fc68f7f586c":{
      "scriptId":"u9"},
    "4fc3cad424fd4ca88da62972b8307e61":{
      "scriptId":"u10"},
    "07bb4f8dae064640aff1e05299fcbcf6":{
      "scriptId":"u11"},
    "6f46102dbc204c3b8b04722e71dc1e8a":{
      "scriptId":"u12"},
    "7c5d1ab2dee94f3a92a17c144f19fa2a":{
      "scriptId":"u13"},
    "7d75c53729b14023ac3288c11bd1ce66":{
      "scriptId":"u14"},
    "52a8b9e2c90444678b3abc885108553c":{
      "scriptId":"u15"},
    "7cf3f858e1b1466ba7af22dd2581ba8e":{
      "scriptId":"u16"},
    "72db0a1b066245a0bb72ed9a1422084a":{
      "scriptId":"u17"},
    "cb2397378ee64cee9e4327679abed3b4":{
      "scriptId":"u18"},
    "0121db15a3144da3a65ab4b5c3d429d3":{
      "scriptId":"u19"},
    "25ed64cd668641f5982f6efa8028e369":{
      "scriptId":"u20"},
    "f8b3a88b150e4e3b8d09577543a9075a":{
      "scriptId":"u21"},
    "7c59e9cc820a488e9b77c6f98ecda5d2":{
      "scriptId":"u22"},
    "b7c806ce75044433a4c3a9798d42ed6a":{
      "scriptId":"u23"},
    "cc911b00f1ea460fb023dced77ad9e47":{
      "scriptId":"u24"},
    "9a0a6ffbe9b249e1a80e910ba6f6cefe":{
      "scriptId":"u25"},
    "480ffccd3913438fac00b2fb13330d76":{
      "scriptId":"u26"},
    "a9116ccad40f42478e615c2bdf836a78":{
      "scriptId":"u27"},
    "ef64a00666e3413f8885aa18a7bdf6a8":{
      "scriptId":"u28"},
    "4772d2ae91c84f96939488cbceba217a":{
      "scriptId":"u29"},
    "9515893632aa4389bee88783eb78234e":{
      "scriptId":"u30"},
    "6519738b6a3e42788088f4917c5017c2":{
      "scriptId":"u31"},
    "5813c6cb9162496e9eace4efc17925ae":{
      "scriptId":"u32"},
    "9be8480aa8bd410d8fde4115ecd1b443":{
      "scriptId":"u33"},
    "c2f843b40e7847538109ec3f30c1571e":{
      "scriptId":"u34"},
    "d5bf18680b2a47bc99b4e9c20ad44cb2":{
      "scriptId":"u35"},
    "58c5accec08f4398a3db1d134a0f7970":{
      "scriptId":"u36"},
    "a20a46f666314e0ea5f534fbb00f227f":{
      "scriptId":"u37"},
    "5a1ea5648b164ad2970a4d0b5b9bbcb8":{
      "scriptId":"u38"},
    "a73a44c17dc54e35a02d8f9227e857a7":{
      "scriptId":"u39"},
    "318926e8a452484d85a59358df7cb6cd":{
      "scriptId":"u40"},
    "c733a24ab5c54b279418ae9a4ba3109a":{
      "scriptId":"u41"},
    "e9b9d2b912564a58847046793e5f69be":{
      "scriptId":"u42"},
    "65fb7845a00143e49073e0886b46128a":{
      "scriptId":"u43"},
    "0f679838ac254986bc9521bb73ff4fd2":{
      "scriptId":"u44"},
    "f3c9324fef604706a5ee60657250e965":{
      "scriptId":"u45"},
    "0897a8f975a44e4c882f4a673b8ac73d":{
      "scriptId":"u46"},
    "be1a6c246458459e9e4f11245037118f":{
      "scriptId":"u47"},
    "1e2809fa41b14cbd9fba1142bd535c3a":{
      "scriptId":"u48"},
    "89020348f443413aa45fc1bdcbd4c32e":{
      "scriptId":"u49"},
    "c4334fdfedcb415996d1d22c1bf1d710":{
      "scriptId":"u50"},
    "bdb8c86188df4d21a3907cb103995910":{
      "scriptId":"u51"},
    "ae211a644d8e481ba55f75c86ef12bb0":{
      "scriptId":"u52"}}});