$axure.loadCurrentPage({
  "url":"关注的商户详情.html",
  "generationDate":new Date(1432847390871.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8476788a273a49a2a38f532a3bd1da9a",
    "type":"Axure:Page",
    "name":"关注的商户详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e3a4547046ce40f491c9ebfe8cc3ca47",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":103,
              "y":0},
            "size":{
              "width":208,
              "height":548}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bb716e42ab6446195016d9993678fc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":103,
                  "y":0},
                "size":{
                  "width":208,
                  "height":548}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的劲态（默认关注）",
                      "target":{
                        "targetType":"page",
                        "url":"我的劲态（默认关注）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/品牌介绍页/u0.jpg"}},
{
          "id":"eba8d2f51509420093d1177b2225379c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6FCEB6,
              "opacity":1},
            "location":{
              "x":116,
              "y":154},
            "size":{
              "width":180,
              "height":166}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27bc4fa097af4b728ca2dcdf7a6be88f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6FCEB6,
                  "opacity":1},
                "location":{
                  "x":116,
                  "y":154},
                "size":{
                  "width":180,
                  "height":166}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的劲态（默认关注）",
                      "target":{
                        "targetType":"page",
                        "url":"我的劲态（默认关注）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"410a028471004c87a903f420f776183f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF78914},
            "location":{
              "x":107,
              "y":488},
            "size":{
              "width":200,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48f711d6ecf54c719a8520c6bc9faa25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF78914},
                "location":{
                  "x":107,
                  "y":488},
                "size":{
                  "width":200,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商户详情页（交易中）",
                      "target":{
                        "targetType":"page",
                        "url":"商户详情页（交易中）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/品牌介绍页/u4.png"}},
{
          "id":"d5debda00092428ba5b9de2356c7b32d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":168,
              "y":19},
            "size":{
              "width":76,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"498276a8d6034b0d839ccdb282c4be08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":168,
                  "y":19},
                "size":{
                  "width":76,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ab1f0438f574e89987aaf741968926b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":180,
              "y":111},
            "size":{
              "width":124,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3932e41c8c114f0aa108bbf5fdf1560b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":180,
                  "y":111},
                "size":{
                  "width":124,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"725fb14a70ec4b90895dcb8b2199efa1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6FCEB6,
              "opacity":1},
            "location":{
              "x":163,
              "y":64},
            "size":{
              "width":155,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b778b2727eda424ab20d3581a2e39786",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6FCEB6,
                  "opacity":1},
                "location":{
                  "x":163,
                  "y":64},
                "size":{
                  "width":155,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ddc8b07144a4978922c4b4a6f84f6af",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":104,
              "height":548}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"662fe47c0b3742acb6ad07ba66f3d588",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":104,
                  "height":548}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的劲态（默认关注）",
                      "target":{
                        "targetType":"page",
                        "url":"我的劲态（默认关注）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/通知详情/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "e3a4547046ce40f491c9ebfe8cc3ca47":{
      "scriptId":"u0"},
    "3bb716e42ab6446195016d9993678fc5":{
      "scriptId":"u1"},
    "eba8d2f51509420093d1177b2225379c":{
      "scriptId":"u2"},
    "27bc4fa097af4b728ca2dcdf7a6be88f":{
      "scriptId":"u3"},
    "410a028471004c87a903f420f776183f":{
      "scriptId":"u4"},
    "48f711d6ecf54c719a8520c6bc9faa25":{
      "scriptId":"u5"},
    "d5debda00092428ba5b9de2356c7b32d":{
      "scriptId":"u6"},
    "498276a8d6034b0d839ccdb282c4be08":{
      "scriptId":"u7"},
    "7ab1f0438f574e89987aaf741968926b":{
      "scriptId":"u8"},
    "3932e41c8c114f0aa108bbf5fdf1560b":{
      "scriptId":"u9"},
    "725fb14a70ec4b90895dcb8b2199efa1":{
      "scriptId":"u10"},
    "b778b2727eda424ab20d3581a2e39786":{
      "scriptId":"u11"},
    "0ddc8b07144a4978922c4b4a6f84f6af":{
      "scriptId":"u12"},
    "662fe47c0b3742acb6ad07ba66f3d588":{
      "scriptId":"u13"}}});