$axure.loadCurrentPage({
  "url":"品牌介绍页.html",
  "generationDate":new Date(1432921475525.24),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4cfae8fae3d44b4f8513453ccd9ec05f",
    "type":"Axure:Page",
    "name":"品牌介绍页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"650d51671a0d4d3a8702c35efa23e64d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":103,
              "y":0},
            "size":{
              "width":208,
              "height":548}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e102376c06240519781f997f19147d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":103,
                  "y":0},
                "size":{
                  "width":208,
                  "height":548}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 健身机构",
                      "target":{
                        "targetType":"page",
                        "url":"健身机构.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/品牌介绍页/u0.jpg"}},
{
          "id":"59520357ec4f46719ead85ae9550d270",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6FCEB6,
              "opacity":1},
            "location":{
              "x":116,
              "y":154},
            "size":{
              "width":180,
              "height":166}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb7cfe0a6ea3482e8ab7c166c8fd96d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6FCEB6,
                  "opacity":1},
                "location":{
                  "x":116,
                  "y":154},
                "size":{
                  "width":180,
                  "height":166}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 健身机构",
                      "target":{
                        "targetType":"page",
                        "url":"健身机构.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a059230ac7342deae635b5477ed1442",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF78914},
            "location":{
              "x":107,
              "y":488},
            "size":{
              "width":200,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"381a806053b74e2797507e00209e71c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF78914},
                "location":{
                  "x":107,
                  "y":488},
                "size":{
                  "width":200,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商户详情页（交易中）",
                      "target":{
                        "targetType":"page",
                        "url":"商户详情页（交易中）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/品牌介绍页/u4.png"}},
{
          "id":"e8cdba4cc61f40e4bdfe6711823040f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":168,
              "y":19},
            "size":{
              "width":76,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b052dca5293449f92376911bd5a9e3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":168,
                  "y":19},
                "size":{
                  "width":76,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b459ecf69d0487484377678f323a086",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":180,
              "y":111},
            "size":{
              "width":124,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01a96fa0a2d54945b9711afb92cb90b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":180,
                  "y":111},
                "size":{
                  "width":124,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1306197340a41f8890644f4946512d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6FCEB6,
              "opacity":1},
            "location":{
              "x":163,
              "y":64},
            "size":{
              "width":155,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20951709833f4e179c4037b55340c80a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6FCEB6,
                  "opacity":1},
                "location":{
                  "x":163,
                  "y":64},
                "size":{
                  "width":155,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"816f71a913114f498b1ba4decfdb62a6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":103,
              "height":548}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6be78823abe34e319b622385363a60e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":103,
                  "height":548}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 健身机构",
                      "target":{
                        "targetType":"page",
                        "url":"健身机构.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/品牌介绍页/u12.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "650d51671a0d4d3a8702c35efa23e64d":{
      "scriptId":"u0"},
    "1e102376c06240519781f997f19147d5":{
      "scriptId":"u1"},
    "59520357ec4f46719ead85ae9550d270":{
      "scriptId":"u2"},
    "bb7cfe0a6ea3482e8ab7c166c8fd96d6":{
      "scriptId":"u3"},
    "0a059230ac7342deae635b5477ed1442":{
      "scriptId":"u4"},
    "381a806053b74e2797507e00209e71c1":{
      "scriptId":"u5"},
    "e8cdba4cc61f40e4bdfe6711823040f8":{
      "scriptId":"u6"},
    "6b052dca5293449f92376911bd5a9e3d":{
      "scriptId":"u7"},
    "5b459ecf69d0487484377678f323a086":{
      "scriptId":"u8"},
    "01a96fa0a2d54945b9711afb92cb90b1":{
      "scriptId":"u9"},
    "a1306197340a41f8890644f4946512d6":{
      "scriptId":"u10"},
    "20951709833f4e179c4037b55340c80a":{
      "scriptId":"u11"},
    "816f71a913114f498b1ba4decfdb62a6":{
      "scriptId":"u12"},
    "6be78823abe34e319b622385363a60e5":{
      "scriptId":"u13"}}});