$axure.loadCurrentPage({
  "url":"登录页面.html",
  "generationDate":new Date(1429794604661.95),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4839f526b9e44957877e2ba81131cd6b",
    "type":"Axure:Page",
    "name":"登录页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onClick":{
        "description":"OnClick",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"linkWindow",
                "description":"在 当前窗口 打开 链接",
                "target":{
                  "targetType":"page",
                  "includeVariables":true},
                "linkType":"current"}]}]}},
    "diagram":{
      "objects":[{
          "id":"85ac0b0414d94f298503416816df8056",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bb079647e2a415195d3eb1b9194af99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录页面/u0.png"}},
{
          "id":"2b446f5ab8ff49dd8c1e74c8575579d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "opacity":"0",
            "location":{
              "x":21,
              "y":264},
            "size":{
              "width":279,
              "height":39},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84e0aab92c7a4f678e75382c842e2dc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "opacity":"0",
                "location":{
                  "x":21,
                  "y":264},
                "size":{
                  "width":279,
                  "height":39},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff273884f2c74a829178e77446af45aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "opacity":"0",
            "location":{
              "x":8,
              "y":31},
            "size":{
              "width":72,
              "height":39},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6aa8001163043e2981ab6b0d5e7af87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "opacity":"0",
                "location":{
                  "x":8,
                  "y":31},
                "size":{
                  "width":72,
                  "height":39},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b668f04dfc4486386b89ffc80bcceba",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":462},
            "size":{
              "width":56,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dab116a536094a44bcbd22021c1ec5d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":462},
                "size":{
                  "width":56,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 微信登录",
                      "target":{
                        "targetType":"page",
                        "url":"微信登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录页面/u6.png"}},
{
          "id":"aac29bd1edb44811a73049a233595be7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":133,
              "y":463},
            "size":{
              "width":55,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3506c9f43c5b4a3788b09890268ccdfa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":133,
                  "y":463},
                "size":{
                  "width":55,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 微信登录",
                      "target":{
                        "targetType":"page",
                        "url":"微信登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录页面/u8.png"}},
{
          "id":"eab265afcc83438e917808a82772408c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":224,
              "y":462},
            "size":{
              "width":55,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a536f184a34474195a2c2532f0648db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":224,
                  "y":462},
                "size":{
                  "width":55,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 微信登录",
                      "target":{
                        "targetType":"page",
                        "url":"微信登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录页面/u10.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "85ac0b0414d94f298503416816df8056":{
      "scriptId":"u0"},
    "2bb079647e2a415195d3eb1b9194af99":{
      "scriptId":"u1"},
    "2b446f5ab8ff49dd8c1e74c8575579d2":{
      "scriptId":"u2"},
    "84e0aab92c7a4f678e75382c842e2dc6":{
      "scriptId":"u3"},
    "ff273884f2c74a829178e77446af45aa":{
      "scriptId":"u4"},
    "b6aa8001163043e2981ab6b0d5e7af87":{
      "scriptId":"u5"},
    "1b668f04dfc4486386b89ffc80bcceba":{
      "scriptId":"u6"},
    "dab116a536094a44bcbd22021c1ec5d7":{
      "scriptId":"u7"},
    "aac29bd1edb44811a73049a233595be7":{
      "scriptId":"u8"},
    "3506c9f43c5b4a3788b09890268ccdfa":{
      "scriptId":"u9"},
    "eab265afcc83438e917808a82772408c":{
      "scriptId":"u10"},
    "7a536f184a34474195a2c2532f0648db":{
      "scriptId":"u11"}}});