$axure.loadCurrentPage({
  "url":"首页.html",
  "generationDate":new Date(1432921473771.14),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8ac5ab7776704ada83176f61f88343ab",
    "type":"Axure:Page",
    "name":"首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onClick":{
        "description":"OnClick",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"linkWindow",
                "description":"在 当前窗口 打开 【我的】页面（新注册）",
                "target":{
                  "targetType":"page",
                  "url":"【我的】页面（新注册）.html",
                  "includeVariables":true},
                "linkType":"current"}]}]}},
    "diagram":{
      "objects":[{
          "id":"47937aeda7c9418c8cfbf0bc9ced2027",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":548}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79fa3a35e6f64b56a14a650d7a8bd9a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":548}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"d8652893767049beac248a371b557bc5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1463f6e6dc2d4289b7584ba80a502438",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"31f5e7d6d8764e639bc015753d027ccd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":40,
              "y":242},
            "size":{
              "width":39,
              "height":37},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"532df9c4106b4fbb91fd82da9445fcca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":40,
                  "y":242},
                "size":{
                  "width":39,
                  "height":37},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 地图导航页",
                      "target":{
                        "targetType":"page",
                        "url":"地图导航页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00449c80f5c04a5eac1ea93c84c7ef0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":85,
              "y":242},
            "size":{
              "width":124,
              "height":37},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afde0094e51d4192b08971609549b371",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":85,
                  "y":242},
                "size":{
                  "width":124,
                  "height":37},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商户详情页（交易中）",
                      "target":{
                        "targetType":"page",
                        "url":"商户详情页（交易中）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dafb99c7a537407190621fc787bcbcf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":121,
              "y":4},
            "size":{
              "width":73,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"641be347ff0440cc9f0adb686e0c5581",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":121,
                  "y":4},
                "size":{
                  "width":73,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c8da1789412b4dc2ae20a3e58668853c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":6,
              "y":5},
            "size":{
              "width":44,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74ee95df6ef242d1a6dc591ebbe18a08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":6,
                  "y":5},
                "size":{
                  "width":44,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 左侧边栏",
                      "target":{
                        "targetType":"page",
                        "url":"左侧边栏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a056038890ac4225af890411c5566549",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":276,
              "y":5},
            "size":{
              "width":44,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"591dd25e3fdc43e68361afcd389bfd20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":276,
                  "y":5},
                "size":{
                  "width":44,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 搜索页&amp;切换城市",
                      "target":{
                        "targetType":"page",
                        "url":"搜索页_切换城市.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0010eb0e350468faa26cc18b4761283",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":139,
              "y":31},
            "size":{
              "width":42,
              "height":9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10b5c0c590cf453caca6e2c9366d4d99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":139,
                  "y":31},
                "size":{
                  "width":42,
                  "height":9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u14.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "47937aeda7c9418c8cfbf0bc9ced2027":{
      "scriptId":"u0"},
    "79fa3a35e6f64b56a14a650d7a8bd9a5":{
      "scriptId":"u1"},
    "d8652893767049beac248a371b557bc5":{
      "scriptId":"u2"},
    "1463f6e6dc2d4289b7584ba80a502438":{
      "scriptId":"u3"},
    "31f5e7d6d8764e639bc015753d027ccd":{
      "scriptId":"u4"},
    "532df9c4106b4fbb91fd82da9445fcca":{
      "scriptId":"u5"},
    "00449c80f5c04a5eac1ea93c84c7ef0b":{
      "scriptId":"u6"},
    "afde0094e51d4192b08971609549b371":{
      "scriptId":"u7"},
    "dafb99c7a537407190621fc787bcbcf4":{
      "scriptId":"u8"},
    "641be347ff0440cc9f0adb686e0c5581":{
      "scriptId":"u9"},
    "c8da1789412b4dc2ae20a3e58668853c":{
      "scriptId":"u10"},
    "74ee95df6ef242d1a6dc591ebbe18a08":{
      "scriptId":"u11"},
    "a056038890ac4225af890411c5566549":{
      "scriptId":"u12"},
    "591dd25e3fdc43e68361afcd389bfd20":{
      "scriptId":"u13"},
    "f0010eb0e350468faa26cc18b4761283":{
      "scriptId":"u14"},
    "10b5c0c590cf453caca6e2c9366d4d99":{
      "scriptId":"u15"}}});