$axure.loadCurrentPage({
  "url":"首页.html",
  "generationDate":new Date(1430845023426.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8ac5ab7776704ada83176f61f88343ab",
    "type":"Axure:Page",
    "name":"首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onClick":{
        "description":"OnClick",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"linkWindow",
                "description":"在 当前窗口 打开 【我的】页面（新注册）",
                "target":{
                  "targetType":"page",
                  "url":"【我的】页面（新注册）.html",
                  "includeVariables":true},
                "linkType":"current"}]}]}},
    "diagram":{
      "objects":[{
          "id":"ccb7416c5cbe415084dc9311a0441f11",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"799a30ddafaf4a14939e598a442108c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"13578f64d51f4e1abc13c046a15a1388",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":289,
              "y":35},
            "size":{
              "width":16,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e419afe412c1461ab9b802f7c0bb020b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":289,
                  "y":35},
                "size":{
                  "width":16,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 搜索页&amp;切换城市",
                      "target":{
                        "targetType":"page",
                        "url":"搜索页_切换城市.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"31f5e7d6d8764e639bc015753d027ccd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":41,
              "y":262},
            "size":{
              "width":39,
              "height":37},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"532df9c4106b4fbb91fd82da9445fcca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":41,
                  "y":262},
                "size":{
                  "width":39,
                  "height":37},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 地图导航页",
                      "target":{
                        "targetType":"page",
                        "url":"地图导航页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00449c80f5c04a5eac1ea93c84c7ef0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":86,
              "y":262},
            "size":{
              "width":124,
              "height":37},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afde0094e51d4192b08971609549b371",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":86,
                  "y":262},
                "size":{
                  "width":124,
                  "height":37},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商户详情页（交易中）",
                      "target":{
                        "targetType":"page",
                        "url":"商户详情页（交易中）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a893ffabeac4dd8855f10a0a235b0c2",
          "label":"边栏切换按钮",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":36},
            "size":{
              "width":22,
              "height":12}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"9854e36cb29c4e149814ed88b8d90926",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"9f1facc24f4642f38d8d07eac11a8c6b",
                  "label":"",
                  "parentDynamicPanel":"4a893ffabeac4dd8855f10a0a235b0c2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":22,
                      "height":12}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"595cd194005a4f969b5f2847a636d0cc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4a893ffabeac4dd8855f10a0a235b0c2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":22,
                          "height":12}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 边栏切换按钮,<br>(Image)",
                              "objectsToFades":[{
                                  "objectPath":["4a893ffabeac4dd8855f10a0a235b0c2"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["9f1facc24f4642f38d8d07eac11a8c6b"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/左侧边栏/u2.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "ccb7416c5cbe415084dc9311a0441f11":{
      "scriptId":"u0"},
    "799a30ddafaf4a14939e598a442108c4":{
      "scriptId":"u1"},
    "13578f64d51f4e1abc13c046a15a1388":{
      "scriptId":"u2"},
    "e419afe412c1461ab9b802f7c0bb020b":{
      "scriptId":"u3"},
    "31f5e7d6d8764e639bc015753d027ccd":{
      "scriptId":"u4"},
    "532df9c4106b4fbb91fd82da9445fcca":{
      "scriptId":"u5"},
    "00449c80f5c04a5eac1ea93c84c7ef0b":{
      "scriptId":"u6"},
    "afde0094e51d4192b08971609549b371":{
      "scriptId":"u7"},
    "4a893ffabeac4dd8855f10a0a235b0c2":{
      "scriptId":"u8"},
    "9f1facc24f4642f38d8d07eac11a8c6b":{
      "scriptId":"u9"},
    "595cd194005a4f969b5f2847a636d0cc":{
      "scriptId":"u10"}}});