$axure.loadCurrentPage({
  "url":"帮助.html",
  "generationDate":new Date(1432237668527.7),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f32f2de3484d4822a08f2bfdfbf53753",
    "type":"Axure:Page",
    "name":"帮助",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"aa8d180cf024429e888add6dca2dd837",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":112},
            "size":{
              "width":267,
              "height":142}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d8ade4af4f345ce95fa10e88e6a1b3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":112},
                "size":{
                  "width":267,
                  "height":142}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动页/u15.png"}},
{
          "id":"bcb3eb8441be49b49d10fc5eba9d2f65",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":121},
            "size":{
              "width":249,
              "height":126}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a8c18caaf624333aada3f8220bbd19b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":121},
                "size":{
                  "width":249,
                  "height":126}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2d09b3ffb5143958770f9be809b070c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":540}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79f66bed2d9147188b02feb48f669efb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":540}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u0.png"}},
{
          "id":"74aa8c3b0c9544ffaae390375f20491c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a3335812b0e4b6aa84a5bb955d7ad8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/意见反馈/u0.png"}},
{
          "id":"78d112ccc7974e2c9544cd1d7193ee9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "location":{
              "x":125,
              "y":12},
            "size":{
              "width":70,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4940d81ac18540c488f58b54f18dfa41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "location":{
                  "x":125,
                  "y":12},
                "size":{
                  "width":70,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5c8e07a14234334a8af199970c04807",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":3},
            "size":{
              "width":45,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c3d0536d37b4d3f8297158a167e1b0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":4,
                  "y":3},
                "size":{
                  "width":45,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设置",
                      "target":{
                        "targetType":"page",
                        "url":"设置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/意见反馈/u4.png"}},
{
          "id":"bfa6be3fe3f34cd5b13a4368b8c6450a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":44},
            "size":{
              "width":320,
              "height":496}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a29334e2a57c4826a2b64aea3265ca5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":44},
                "size":{
                  "width":320,
                  "height":496}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/意见反馈/u8.jpg"}},
{
          "id":"bbd523b57b5c401682c97d4094b66f67",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF19A79C,
              "opacity":1},
            "location":{
              "x":9,
              "y":110},
            "size":{
              "width":302,
              "height":300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5349e7bc35a2461b8a29a2959d9c7f99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF19A79C,
                  "opacity":1},
                "location":{
                  "x":9,
                  "y":110},
                "size":{
                  "width":302,
                  "height":300}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "aa8d180cf024429e888add6dca2dd837":{
      "scriptId":"u0"},
    "0d8ade4af4f345ce95fa10e88e6a1b3f":{
      "scriptId":"u1"},
    "bcb3eb8441be49b49d10fc5eba9d2f65":{
      "scriptId":"u2"},
    "8a8c18caaf624333aada3f8220bbd19b":{
      "scriptId":"u3"},
    "b2d09b3ffb5143958770f9be809b070c":{
      "scriptId":"u4"},
    "79f66bed2d9147188b02feb48f669efb":{
      "scriptId":"u5"},
    "74aa8c3b0c9544ffaae390375f20491c":{
      "scriptId":"u6"},
    "3a3335812b0e4b6aa84a5bb955d7ad8f":{
      "scriptId":"u7"},
    "78d112ccc7974e2c9544cd1d7193ee9a":{
      "scriptId":"u8"},
    "4940d81ac18540c488f58b54f18dfa41":{
      "scriptId":"u9"},
    "d5c8e07a14234334a8af199970c04807":{
      "scriptId":"u10"},
    "4c3d0536d37b4d3f8297158a167e1b0a":{
      "scriptId":"u11"},
    "bfa6be3fe3f34cd5b13a4368b8c6450a":{
      "scriptId":"u12"},
    "a29334e2a57c4826a2b64aea3265ca5d":{
      "scriptId":"u13"},
    "bbd523b57b5c401682c97d4094b66f67":{
      "scriptId":"u14"},
    "5349e7bc35a2461b8a29a2959d9c7f99":{
      "scriptId":"u15"}}});