$axure.loadCurrentPage({
  "url":"回应详情页面.html",
  "generationDate":new Date(1432237664542.47),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3be23d1354874b0990c7777ca0fcea81",
    "type":"Axure:Page",
    "name":"回应详情页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9709d35991b04514b8673c0c30836c70",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":-20},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0abf712d46843bb81b3069ade94d579",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":-20},
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/回应详情页面/u0.png"}},
{
          "id":"01a50086416a4445af63b5b1d3b4ea05",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":112,
              "y":460},
            "size":{
              "width":200,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75d1af43041941828c7cdae55f14b50f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":112,
                  "y":460},
                "size":{
                  "width":200,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 回应弹框,<br>(Image)",
                      "objectsToFades":[{
                          "objectPath":["1d562193e883413e9f8a013dff87bce1"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["5363579aadad4056b77717adcc199fdc"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d562193e883413e9f8a013dff87bce1",
          "label":"回应弹框",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":177.5},
            "size":{
              "width":268,
              "height":173}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"ea20ff001bb84095be51e3764906ed5b",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5363579aadad4056b77717adcc199fdc",
                  "label":"",
                  "parentDynamicPanel":"1d562193e883413e9f8a013dff87bce1",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":false,
                  "style":{
                    "size":{
                      "width":268,
                      "height":173},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d077fc50f01a4a518e23c6ae5db66246",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1d562193e883413e9f8a013dff87bce1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "size":{
                          "width":268,
                          "height":173},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 卖时间",
                              "target":{
                                "targetType":"page",
                                "url":"卖时间.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/回应详情页面/u5.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "9709d35991b04514b8673c0c30836c70":{
      "scriptId":"u0"},
    "b0abf712d46843bb81b3069ade94d579":{
      "scriptId":"u1"},
    "01a50086416a4445af63b5b1d3b4ea05":{
      "scriptId":"u2"},
    "75d1af43041941828c7cdae55f14b50f":{
      "scriptId":"u3"},
    "1d562193e883413e9f8a013dff87bce1":{
      "scriptId":"u4"},
    "5363579aadad4056b77717adcc199fdc":{
      "scriptId":"u5"},
    "d077fc50f01a4a518e23c6ae5db66246":{
      "scriptId":"u6"}}});