$axure.loadCurrentPage({
  "url":"评价页面.html",
  "generationDate":new Date(1432847389570.32),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"92c5bd9aacd4490194fc9d4f758cebe7",
    "type":"Axure:Page",
    "name":"评价页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bcfc4e0127e3470a8fd747e024422f07",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a091024afb6400a91b182f29f0c6898",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户详情页（交易中）/u2.png"}},
{
          "id":"99117beedda345bcaa62b1237ebe2a3a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":44},
            "size":{
              "width":320,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94667614e9c549399497c703ba20f1c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":44},
                "size":{
                  "width":320,
                  "height":106}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户详情页（交易中）/u4.png"}},
{
          "id":"d474a80fe17a4daca66bef47832458c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":8,
              "y":4},
            "size":{
              "width":44,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"942baa0fbff348ba898f7f70d013aca0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":8,
                  "y":4},
                "size":{
                  "width":44,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 左侧边栏",
                      "target":{
                        "targetType":"page",
                        "url":"左侧边栏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d43f27104f3a498aadd12f4400114276",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":122,
              "y":5},
            "size":{
              "width":76,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08a97ddd195b4d16a0f52089bfe34ad0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":122,
                  "y":5},
                "size":{
                  "width":76,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20f83a9c278240738e8c525d97cac2ea",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":159},
            "size":{
              "width":61,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9907fcea60e4f969a3e7c5b0e876f43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":159},
                "size":{
                  "width":61,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 通知页面",
                      "target":{
                        "targetType":"page",
                        "url":"通知页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商户详情页（交易中）/u14.png"}},
{
          "id":"2a7349ccc6394b24a114ec62c2b03b24",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":98,
              "y":159},
            "size":{
              "width":61,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dea3de2b86a04de189a99bf4867f02f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":98,
                  "y":159},
                "size":{
                  "width":61,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课程页面",
                      "target":{
                        "targetType":"page",
                        "url":"课程页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商户详情页（交易中）/u16.png"}},
{
          "id":"637cc8fc8859474abaa44a0d003f80b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":130,
              "y":60},
            "size":{
              "width":160,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d179aadb9e843b392fbd039c034107c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":130,
                  "y":60},
                "size":{
                  "width":160,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"634c07453d1647599d04ac59e56be522",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":146,
              "y":105},
            "size":{
              "width":160,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d15a421e75ea490abcbfdd59815876c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":146,
                  "y":105},
                "size":{
                  "width":160,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6314397e9cb4493d9130d26370e29d03",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":147},
            "size":{
              "width":312,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户详情页（交易中）/u22_line.png"}},
{
          "id":"9aa96daade7c49edad6310987b28aa3f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":227},
            "size":{
              "width":312,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户详情页（交易中）/u22_line.png"}},
{
          "id":"b09a135f2ac34e26a617b77f8308503a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":177,
              "y":159},
            "size":{
              "width":61,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d487c79998e14595b7eb0306ec856d7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":177,
                  "y":159},
                "size":{
                  "width":61,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 促销优惠信息",
                      "target":{
                        "targetType":"page",
                        "url":"促销优惠信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/促销优惠信息/u18.png"}},
{
          "id":"f98453a9d32e4b8185615a1944f118a9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":254,
              "y":159},
            "size":{
              "width":61,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3db9f92295c43acb40f9b031d8c8f23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":254,
                  "y":159},
                "size":{
                  "width":61,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 评价页面",
                      "target":{
                        "targetType":"page",
                        "url":"评价页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/促销优惠信息/u20.png"}},
{
          "id":"f999d9a91cba491ab696a874a2a24029",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":243},
            "size":{
              "width":320,
              "height":285}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b38f87074dd43dab2aba3ae8c35ee4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":243},
                "size":{
                  "width":320,
                  "height":285}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价页面/u22.png"}},
{
          "id":"55b7efaa0f034c31a58a8871c07f2c60",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":19,
              "y":243},
            "size":{
              "width":74,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30fe8f530f9c417eb8d9f365173022d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":19,
                  "y":243},
                "size":{
                  "width":74,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"428e7351a5594af2bee01d487ff2b988",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "location":{
              "x":85,
              "y":281},
            "size":{
              "width":153,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bcfe9140987435090d22cb2f79f854f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "location":{
                  "x":85,
                  "y":281},
                "size":{
                  "width":153,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ae0cf3069784fc5864312c1b605136a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":85,
              "y":372},
            "size":{
              "width":140,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de314fa3b5ef49a5a96e35c75237a3e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":85,
                  "y":372},
                "size":{
                  "width":140,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d76eb3df627d4fc19628aafb80472685",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":85,
              "y":457},
            "size":{
              "width":140,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4591555f88b44dae9ebe99dd79f005d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":85,
                  "y":457},
                "size":{
                  "width":140,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b922323d76041549d864bbb48ebec2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":85,
              "y":302},
            "size":{
              "width":221,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95a76bf0a06e44da8c92d54c122856b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":85,
                  "y":302},
                "size":{
                  "width":221,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 评价详情",
                      "target":{
                        "targetType":"page",
                        "url":"评价详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7cd18732553c4107bdc09c3f0c527e80",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":85,
              "y":392},
            "size":{
              "width":221,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f07dde4877443c394ea96aae444f27a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":85,
                  "y":392},
                "size":{
                  "width":221,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 评价详情",
                      "target":{
                        "targetType":"page",
                        "url":"评价详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"acd028afc51b4adeb3146cb62d45b5f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":85,
              "y":480},
            "size":{
              "width":221,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9d833891fca4822a65b0229fa9052d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":85,
                  "y":480},
                "size":{
                  "width":221,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 评价详情",
                      "target":{
                        "targetType":"page",
                        "url":"评价详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f09d53bebc74949adbde4f60d2dfe23",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":303,
              "y":312},
            "size":{
              "width":12,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"582b9b1ab84d400d88cc93f5fb96e14a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":303,
                  "y":312},
                "size":{
                  "width":12,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价页面/u38.png"}},
{
          "id":"572c1cf2f17d4f85b4827342658e0484",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":303,
              "y":404},
            "size":{
              "width":12,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"034b588eb5034c0caef433c893a3c393",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":303,
                  "y":404},
                "size":{
                  "width":12,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价页面/u38.png"}},
{
          "id":"ee3a07d4c84448eab13962ca211dc55d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":303,
              "y":491},
            "size":{
              "width":12,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fcb46cd9bc74e0285a903213297002c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":303,
                  "y":491},
                "size":{
                  "width":12,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价页面/u38.png"}},
{
          "id":"0d1d2f7544194f40a400f6f7744125a2",
          "label":"ButtonBigSecondary",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontSize":"18px",
            "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
            "opacity":"0.6",
            "location":{
              "x":192,
              "y":44},
            "size":{
              "width":130,
              "height":76},
            "visible":false,
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9555b7b035674c33a42c5e5e5edf02b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"18px",
                "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
                "opacity":"0.6",
                "location":{
                  "x":192,
                  "y":44},
                "size":{
                  "width":130,
                  "height":76},
                "visible":false,
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/buttonbigsecondary_u58.png"}},
{
          "id":"4baa2f3a2d8c43ccbb9ab0530ef7b45c",
          "label":"买卖时间",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":192,
              "y":44},
            "size":{
              "width":130,
              "height":76},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"dbb32e9cbe4e4095bcafba5439f64e6f",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e2c735d1f1084a7796a6367317e49225",
                  "label":"",
                  "parentDynamicPanel":"4baa2f3a2d8c43ccbb9ab0530ef7b45c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":130,
                      "height":76}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e589cbe0486c42f78162dd8824719b87",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4baa2f3a2d8c43ccbb9ab0530ef7b45c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":130,
                          "height":76}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/买时间/u61.png"}},
{
                  "id":"f60aa6f7f66f4d6ead195d8423a93bdf",
                  "label":"",
                  "parentDynamicPanel":"4baa2f3a2d8c43ccbb9ab0530ef7b45c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0",
                    "location":{
                      "x":0,
                      "y":1},
                    "size":{
                      "width":130,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7f5fa82bbf8a4dddabad52bc0dd7019a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4baa2f3a2d8c43ccbb9ab0530ef7b45c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0",
                        "location":{
                          "x":0,
                          "y":1},
                        "size":{
                          "width":130,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 发布出售信息",
                              "target":{
                                "targetType":"page",
                                "url":"发布出售信息.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"57501b32f09f466eb6c5542e2c6b23a1",
                  "label":"",
                  "parentDynamicPanel":"4baa2f3a2d8c43ccbb9ab0530ef7b45c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0",
                    "location":{
                      "x":0,
                      "y":41},
                    "size":{
                      "width":130,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7b72ef536cfe4f858ef56f3ead71f2ba",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4baa2f3a2d8c43ccbb9ab0530ef7b45c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0",
                        "location":{
                          "x":0,
                          "y":41},
                        "size":{
                          "width":130,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 发布求购信息",
                              "target":{
                                "targetType":"page",
                                "url":"发布求购信息.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"235e22cdc68a4c6abdaf606472303410",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":272,
              "y":5},
            "size":{
              "width":43,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"076f1fa2d0e84fa699cbce6c1babc1d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":272,
                  "y":5},
                "size":{
                  "width":43,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (Image) 向下滑动 500 毫秒,<br>买卖时间 向下滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["e2c735d1f1084a7796a6367317e49225"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}},
{
                          "objectPath":["4baa2f3a2d8c43ccbb9ab0530ef7b45c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "bcfc4e0127e3470a8fd747e024422f07":{
      "scriptId":"u0"},
    "8a091024afb6400a91b182f29f0c6898":{
      "scriptId":"u1"},
    "99117beedda345bcaa62b1237ebe2a3a":{
      "scriptId":"u2"},
    "94667614e9c549399497c703ba20f1c7":{
      "scriptId":"u3"},
    "d474a80fe17a4daca66bef47832458c9":{
      "scriptId":"u4"},
    "942baa0fbff348ba898f7f70d013aca0":{
      "scriptId":"u5"},
    "d43f27104f3a498aadd12f4400114276":{
      "scriptId":"u6"},
    "08a97ddd195b4d16a0f52089bfe34ad0":{
      "scriptId":"u7"},
    "20f83a9c278240738e8c525d97cac2ea":{
      "scriptId":"u8"},
    "c9907fcea60e4f969a3e7c5b0e876f43":{
      "scriptId":"u9"},
    "2a7349ccc6394b24a114ec62c2b03b24":{
      "scriptId":"u10"},
    "dea3de2b86a04de189a99bf4867f02f6":{
      "scriptId":"u11"},
    "637cc8fc8859474abaa44a0d003f80b4":{
      "scriptId":"u12"},
    "5d179aadb9e843b392fbd039c034107c":{
      "scriptId":"u13"},
    "634c07453d1647599d04ac59e56be522":{
      "scriptId":"u14"},
    "d15a421e75ea490abcbfdd59815876c8":{
      "scriptId":"u15"},
    "6314397e9cb4493d9130d26370e29d03":{
      "scriptId":"u16"},
    "9aa96daade7c49edad6310987b28aa3f":{
      "scriptId":"u17"},
    "b09a135f2ac34e26a617b77f8308503a":{
      "scriptId":"u18"},
    "d487c79998e14595b7eb0306ec856d7b":{
      "scriptId":"u19"},
    "f98453a9d32e4b8185615a1944f118a9":{
      "scriptId":"u20"},
    "f3db9f92295c43acb40f9b031d8c8f23":{
      "scriptId":"u21"},
    "f999d9a91cba491ab696a874a2a24029":{
      "scriptId":"u22"},
    "6b38f87074dd43dab2aba3ae8c35ee4f":{
      "scriptId":"u23"},
    "55b7efaa0f034c31a58a8871c07f2c60":{
      "scriptId":"u24"},
    "30fe8f530f9c417eb8d9f365173022d5":{
      "scriptId":"u25"},
    "428e7351a5594af2bee01d487ff2b988":{
      "scriptId":"u26"},
    "5bcfe9140987435090d22cb2f79f854f":{
      "scriptId":"u27"},
    "8ae0cf3069784fc5864312c1b605136a":{
      "scriptId":"u28"},
    "de314fa3b5ef49a5a96e35c75237a3e6":{
      "scriptId":"u29"},
    "d76eb3df627d4fc19628aafb80472685":{
      "scriptId":"u30"},
    "4591555f88b44dae9ebe99dd79f005d2":{
      "scriptId":"u31"},
    "6b922323d76041549d864bbb48ebec2f":{
      "scriptId":"u32"},
    "95a76bf0a06e44da8c92d54c122856b5":{
      "scriptId":"u33"},
    "7cd18732553c4107bdc09c3f0c527e80":{
      "scriptId":"u34"},
    "5f07dde4877443c394ea96aae444f27a":{
      "scriptId":"u35"},
    "acd028afc51b4adeb3146cb62d45b5f8":{
      "scriptId":"u36"},
    "f9d833891fca4822a65b0229fa9052d9":{
      "scriptId":"u37"},
    "1f09d53bebc74949adbde4f60d2dfe23":{
      "scriptId":"u38"},
    "582b9b1ab84d400d88cc93f5fb96e14a":{
      "scriptId":"u39"},
    "572c1cf2f17d4f85b4827342658e0484":{
      "scriptId":"u40"},
    "034b588eb5034c0caef433c893a3c393":{
      "scriptId":"u41"},
    "ee3a07d4c84448eab13962ca211dc55d":{
      "scriptId":"u42"},
    "0fcb46cd9bc74e0285a903213297002c":{
      "scriptId":"u43"},
    "0d1d2f7544194f40a400f6f7744125a2":{
      "scriptId":"u44"},
    "9555b7b035674c33a42c5e5e5edf02b7":{
      "scriptId":"u45"},
    "4baa2f3a2d8c43ccbb9ab0530ef7b45c":{
      "scriptId":"u46"},
    "e2c735d1f1084a7796a6367317e49225":{
      "scriptId":"u47"},
    "e589cbe0486c42f78162dd8824719b87":{
      "scriptId":"u48"},
    "f60aa6f7f66f4d6ead195d8423a93bdf":{
      "scriptId":"u49"},
    "7f5fa82bbf8a4dddabad52bc0dd7019a":{
      "scriptId":"u50"},
    "57501b32f09f466eb6c5542e2c6b23a1":{
      "scriptId":"u51"},
    "7b72ef536cfe4f858ef56f3ead71f2ba":{
      "scriptId":"u52"},
    "235e22cdc68a4c6abdaf606472303410":{
      "scriptId":"u53"},
    "076f1fa2d0e84fa699cbce6c1babc1d6":{
      "scriptId":"u54"}}});