$axure.loadCurrentPage({
  "url":"关于劲态.html",
  "generationDate":new Date(1429794607785.13),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4fc5f678bffc4b0f9563a185b4a7b1d4",
    "type":"Axure:Page",
    "name":"关于劲态",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b2531ef8aa3940c1975e69f1d20fb04b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":800}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df6595d7fe00466ba67622adc1b58aa3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":800}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u0.png"}},
{
          "id":"69196cdbaa1943bd929875eea48aa035",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":-39},
            "size":{
              "width":320,
              "height":841}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd133343005148daa3c4d06742f22ad9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":-39},
                "size":{
                  "width":320,
                  "height":841}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关于劲态/u2.png"}},
{
          "id":"dca84538b7074f15857ac7cf8b012cf8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76942e22a5764ff8b377dd7245836182",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/意见反馈/u6.png"}},
{
          "id":"f02607e941174a528c33218e80e1d472",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "location":{
              "x":125,
              "y":12},
            "size":{
              "width":70,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7c2d685dbfc42bbbc230801e8725050",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "location":{
                  "x":125,
                  "y":12},
                "size":{
                  "width":70,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"52951be02b4d423eb87d47efebd3cd70",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":3},
            "size":{
              "width":45,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83836970f9224a3f918581d29e310de6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":4,
                  "y":3},
                "size":{
                  "width":45,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设置",
                      "target":{
                        "targetType":"page",
                        "url":"设置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/意见反馈/u10.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "b2531ef8aa3940c1975e69f1d20fb04b":{
      "scriptId":"u0"},
    "df6595d7fe00466ba67622adc1b58aa3":{
      "scriptId":"u1"},
    "69196cdbaa1943bd929875eea48aa035":{
      "scriptId":"u2"},
    "dd133343005148daa3c4d06742f22ad9":{
      "scriptId":"u3"},
    "dca84538b7074f15857ac7cf8b012cf8":{
      "scriptId":"u4"},
    "76942e22a5764ff8b377dd7245836182":{
      "scriptId":"u5"},
    "f02607e941174a528c33218e80e1d472":{
      "scriptId":"u6"},
    "b7c2d685dbfc42bbbc230801e8725050":{
      "scriptId":"u7"},
    "52951be02b4d423eb87d47efebd3cd70":{
      "scriptId":"u8"},
    "83836970f9224a3f918581d29e310de6":{
      "scriptId":"u9"}}});