$axure.loadCurrentPage({
  "url":"消息详情.html",
  "generationDate":new Date(1432847391321.42),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"21e45c13a49248bf843e093c4b730ccb",
    "type":"Axure:Page",
    "name":"消息详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"96a7b7e662af43ef9cc527a6355357a1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":104,
              "height":548}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"426be81fbb1d4b8a8d1319e265aa377b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":104,
                  "height":548}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的消息（已读）",
                      "target":{
                        "targetType":"page",
                        "url":"我的消息（已读）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/通知详情/u0.png"}},
{
          "id":"db3c607d33474966898c0603523ce053",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":103,
              "y":0},
            "size":{
              "width":208,
              "height":548}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58626d8398f042be865206c8b4673569",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":103,
                  "y":0},
                "size":{
                  "width":208,
                  "height":548}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的消息（已读）",
                      "target":{
                        "targetType":"page",
                        "url":"我的消息（已读）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/通知详情/u2.jpg"}},
{
          "id":"3aedfaaf9f9b4367a6d02bfc930a4385",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":117,
              "y":66},
            "size":{
              "width":180,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7539beed64ca457cbb97f7789d8f5752",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":117,
                  "y":66},
                "size":{
                  "width":180,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的消息（已读）",
                      "target":{
                        "targetType":"page",
                        "url":"我的消息（已读）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae7168315ba44c58abaa361f689b733f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":168,
              "y":19},
            "size":{
              "width":76,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cf4059fb22b44e7b41052281fd6978a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":168,
                  "y":19},
                "size":{
                  "width":76,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "96a7b7e662af43ef9cc527a6355357a1":{
      "scriptId":"u0"},
    "426be81fbb1d4b8a8d1319e265aa377b":{
      "scriptId":"u1"},
    "db3c607d33474966898c0603523ce053":{
      "scriptId":"u2"},
    "58626d8398f042be865206c8b4673569":{
      "scriptId":"u3"},
    "3aedfaaf9f9b4367a6d02bfc930a4385":{
      "scriptId":"u4"},
    "7539beed64ca457cbb97f7789d8f5752":{
      "scriptId":"u5"},
    "ae7168315ba44c58abaa361f689b733f":{
      "scriptId":"u6"},
    "9cf4059fb22b44e7b41052281fd6978a":{
      "scriptId":"u7"}}});