$axure.loadCurrentPage({
  "url":"启动页.html",
  "generationDate":new Date(1432847386038.12),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7da7386929cb43aab65dac33490096c6",
    "type":"Axure:Page",
    "name":"启动页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onClick":{
        "description":"OnClick",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"linkWindow",
                "description":"在 当前窗口 打开 首页",
                "target":{
                  "targetType":"page",
                  "url":"首页.html",
                  "includeVariables":true},
                "linkType":"current"}]}]}},
    "diagram":{
      "objects":[{
          "id":"64a05db1e6654cd98891b6ec363e4cd3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":548}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a195396f32c4cfbba2b605c266e2661",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":548}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动页/u0.jpg"}},
{
          "id":"82c087c7d8f140afa43b2d01d45eb8c7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":-8},
            "size":{
              "width":320,
              "height":420}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c86dedcd152e420cb2a247a0616ad48f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":-8},
                "size":{
                  "width":320,
                  "height":420}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动页/u2.png"}},
{
          "id":"eff2f989d5c14a35becba7a26d8397f7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":463},
            "size":{
              "width":141,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"576a74c693474eefa49a4d6565e93b8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":12,
                  "y":463},
                "size":{
                  "width":141,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动页/u4.png"}},
{
          "id":"6da121c9a7d74207935e6ff7b9e08571",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":409},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb638d3edd484c1286b4290664211acc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":409},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动页/u6.png"}},
{
          "id":"7cc8ae2cc6fa48b9a0c30305fff5ece4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":162,
              "y":463},
            "size":{
              "width":141,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5eeac160c97435abba1a864be489662",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":162,
                  "y":463},
                "size":{
                  "width":141,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动页/u8.png"}},
{
          "id":"a3f3d9ff5b2f4ee1bd424364da389bc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":54,
              "y":472},
            "size":{
              "width":58,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"228d41a93be1458f8d7a27f1eaa043f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":54,
                  "y":472},
                "size":{
                  "width":58,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录页面",
                      "target":{
                        "targetType":"page",
                        "url":"登录页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a33cf3dc237a4902b8b250da940e6ef9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":204,
              "y":472},
            "size":{
              "width":58,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2217608028343358585f63a54db1c52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":204,
                  "y":472},
                "size":{
                  "width":58,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 注册页面",
                      "target":{
                        "targetType":"page",
                        "url":"注册页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c2bfb9a2b7643699c2ab8a2ed04ea31",
          "label":"启动页弹框",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":24,
              "y":205},
            "size":{
              "width":266,
              "height":139}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"a3794155ebb24d93951ce2bb279043cc",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"fc81c8ea81654fcbbf9550b2057aa5cd",
                  "label":"",
                  "parentDynamicPanel":"8c2bfb9a2b7643699c2ab8a2ed04ea31",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-1,
                      "y":-3},
                    "size":{
                      "width":267,
                      "height":142}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d304bcea0c774f53a3bb08e24707e5e7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8c2bfb9a2b7643699c2ab8a2ed04ea31",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-1,
                          "y":-3},
                        "size":{
                          "width":267,
                          "height":142}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/启动页/u15.png"}},
{
                  "id":"46e9757ddf7a42cb83aa7c85b58de661",
                  "label":"",
                  "parentDynamicPanel":"8c2bfb9a2b7643699c2ab8a2ed04ea31",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":9,
                      "y":20},
                    "size":{
                      "width":249,
                      "height":115}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"26d46a8f1f034dffa186e072d4698fb0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8c2bfb9a2b7643699c2ab8a2ed04ea31",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":9,
                          "y":20},
                        "size":{
                          "width":249,
                          "height":115}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 启动页弹框,<br>(Image),<br>(形状),<br>当前部件",
                              "objectsToFades":[{
                                  "objectPath":["8c2bfb9a2b7643699c2ab8a2ed04ea31"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["fc81c8ea81654fcbbf9550b2057aa5cd"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["46e9757ddf7a42cb83aa7c85b58de661"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["46e9757ddf7a42cb83aa7c85b58de661"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "64a05db1e6654cd98891b6ec363e4cd3":{
      "scriptId":"u0"},
    "9a195396f32c4cfbba2b605c266e2661":{
      "scriptId":"u1"},
    "82c087c7d8f140afa43b2d01d45eb8c7":{
      "scriptId":"u2"},
    "c86dedcd152e420cb2a247a0616ad48f":{
      "scriptId":"u3"},
    "eff2f989d5c14a35becba7a26d8397f7":{
      "scriptId":"u4"},
    "576a74c693474eefa49a4d6565e93b8c":{
      "scriptId":"u5"},
    "6da121c9a7d74207935e6ff7b9e08571":{
      "scriptId":"u6"},
    "bb638d3edd484c1286b4290664211acc":{
      "scriptId":"u7"},
    "7cc8ae2cc6fa48b9a0c30305fff5ece4":{
      "scriptId":"u8"},
    "c5eeac160c97435abba1a864be489662":{
      "scriptId":"u9"},
    "a3f3d9ff5b2f4ee1bd424364da389bc8":{
      "scriptId":"u10"},
    "228d41a93be1458f8d7a27f1eaa043f2":{
      "scriptId":"u11"},
    "a33cf3dc237a4902b8b250da940e6ef9":{
      "scriptId":"u12"},
    "c2217608028343358585f63a54db1c52":{
      "scriptId":"u13"},
    "8c2bfb9a2b7643699c2ab8a2ed04ea31":{
      "scriptId":"u14"},
    "fc81c8ea81654fcbbf9550b2057aa5cd":{
      "scriptId":"u15"},
    "d304bcea0c774f53a3bb08e24707e5e7":{
      "scriptId":"u16"},
    "46e9757ddf7a42cb83aa7c85b58de661":{
      "scriptId":"u17"},
    "26d46a8f1f034dffa186e072d4698fb0":{
      "scriptId":"u18"}}});