$axure.loadCurrentPage({
  "url":"启动页.html",
  "generationDate":new Date(1430762527845.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7da7386929cb43aab65dac33490096c6",
    "type":"Axure:Page",
    "name":"启动页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onClick":{
        "description":"OnClick",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"linkWindow",
                "description":"在 当前窗口 打开 首页",
                "target":{
                  "targetType":"page",
                  "url":"首页.html",
                  "includeVariables":true},
                "linkType":"current"}]}]}},
    "diagram":{
      "objects":[{
          "id":"e2b4483941d844ab93fb42f8dbedc6e4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":548}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cefc177c8ed45ca9ac9761b515e5e94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":548}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动页/u0.png"}},
{
          "id":"386b912a843f454ca71f559adc7a70e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "opacity":"0",
            "location":{
              "x":17,
              "y":482},
            "size":{
              "width":139,
              "height":39},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2237894ca5fd45bfa953f06cd9a00f0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "opacity":"0",
                "location":{
                  "x":17,
                  "y":482},
                "size":{
                  "width":139,
                  "height":39},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录页面",
                      "target":{
                        "targetType":"page",
                        "url":"登录页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f786a8265294996a79d5f866f69f8e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "opacity":"0",
            "location":{
              "x":90,
              "y":436},
            "size":{
              "width":139,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a7aa5fd423b4c6db9c4d15dc043d3ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "opacity":"0",
                "location":{
                  "x":90,
                  "y":436},
                "size":{
                  "width":139,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9142225733642a6934dd3e084d2d17e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "opacity":"0",
            "location":{
              "x":166,
              "y":482},
            "size":{
              "width":139,
              "height":39},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9257c47468af4f1f83ba7b6f19d4b712",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "opacity":"0",
                "location":{
                  "x":166,
                  "y":482},
                "size":{
                  "width":139,
                  "height":39},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 注册页面",
                      "target":{
                        "targetType":"page",
                        "url":"注册页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c2bfb9a2b7643699c2ab8a2ed04ea31",
          "label":"启动页弹框",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":120},
            "size":{
              "width":266,
              "height":139}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"a3794155ebb24d93951ce2bb279043cc",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"589a1614e50d481287d07311fd21c918",
                  "label":"",
                  "parentDynamicPanel":"8c2bfb9a2b7643699c2ab8a2ed04ea31",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":266,
                      "height":139}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ec8efc42be274719a98e7373c68f9f0f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8c2bfb9a2b7643699c2ab8a2ed04ea31",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":266,
                          "height":139}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 启动页弹框,<br>隐藏 (Image) 淡入淡出 500 毫秒",
                              "objectsToFades":[{
                                  "objectPath":["8c2bfb9a2b7643699c2ab8a2ed04ea31"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["589a1614e50d481287d07311fd21c918"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"fade",
                                      "duration":500,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/启动页/u9.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "e2b4483941d844ab93fb42f8dbedc6e4":{
      "scriptId":"u0"},
    "6cefc177c8ed45ca9ac9761b515e5e94":{
      "scriptId":"u1"},
    "386b912a843f454ca71f559adc7a70e2":{
      "scriptId":"u2"},
    "2237894ca5fd45bfa953f06cd9a00f0d":{
      "scriptId":"u3"},
    "8f786a8265294996a79d5f866f69f8e7":{
      "scriptId":"u4"},
    "4a7aa5fd423b4c6db9c4d15dc043d3ec":{
      "scriptId":"u5"},
    "d9142225733642a6934dd3e084d2d17e":{
      "scriptId":"u6"},
    "9257c47468af4f1f83ba7b6f19d4b712":{
      "scriptId":"u7"},
    "8c2bfb9a2b7643699c2ab8a2ed04ea31":{
      "scriptId":"u8"},
    "589a1614e50d481287d07311fd21c918":{
      "scriptId":"u9"},
    "ec8efc42be274719a98e7373c68f9f0f":{
      "scriptId":"u10"}}});