$axure.loadCurrentPage({
  "url":"求购详情页.html",
  "generationDate":new Date(1432847387915.22),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3be23d1354874b0990c7777ca0fcea81",
    "type":"Axure:Page",
    "name":"求购详情页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9709d35991b04514b8673c0c30836c70",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":-20},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0abf712d46843bb81b3069ade94d579",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":-20},
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 卖时间",
                      "target":{
                        "targetType":"page",
                        "url":"卖时间.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/求购详情页/u0.png"}},
{
          "id":"01a50086416a4445af63b5b1d3b4ea05",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":112,
              "y":460},
            "size":{
              "width":200,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75d1af43041941828c7cdae55f14b50f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":112,
                  "y":460},
                "size":{
                  "width":200,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 回应确认",
                      "target":{
                        "targetType":"page",
                        "url":"回应确认.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28e8d5697bae4971b1a023f77086666c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF252A3E},
            "location":{
              "x":123,
              "y":2},
            "size":{
              "width":178,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF252A3E}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7af06701c7fb401685bd5cf9ae2f0be2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF252A3E},
                "location":{
                  "x":123,
                  "y":2},
                "size":{
                  "width":178,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF252A3E}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/求购详情页/u4.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "9709d35991b04514b8673c0c30836c70":{
      "scriptId":"u0"},
    "b0abf712d46843bb81b3069ade94d579":{
      "scriptId":"u1"},
    "01a50086416a4445af63b5b1d3b4ea05":{
      "scriptId":"u2"},
    "75d1af43041941828c7cdae55f14b50f":{
      "scriptId":"u3"},
    "28e8d5697bae4971b1a023f77086666c":{
      "scriptId":"u4"},
    "7af06701c7fb401685bd5cf9ae2f0be2":{
      "scriptId":"u5"}}});