$axure.loadCurrentPage({
  "url":"我的评价（持卡人评价我）.html",
  "generationDate":new Date(1430762530406.66),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9f78d60902404942afcaeba286785e99",
    "type":"Axure:Page",
    "name":"我的评价（持卡人评价我）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"92e12523504849308e2c7f0d1f93e1d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70af33cc3fe547899ec30e3c70c2dc90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的评价（持卡人评价我）/u0.png"}},
{
          "id":"f7224360d853454091b119bbc92b90b6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":38},
            "size":{
              "width":22,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1ecad83aa01413cb4f0644d5bc51d10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":38},
                "size":{
                  "width":22,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 左侧边栏",
                      "target":{
                        "targetType":"page",
                        "url":"左侧边栏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/左侧边栏/u2.png"}},
{
          "id":"ffc1a57d7ae24da2bc4cfdb95ec6742b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":277,
              "y":26},
            "size":{
              "width":43,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9ac7fe0012448569fa015497e9aa81d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":277,
                  "y":26},
                "size":{
                  "width":43,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的健身数据",
                      "target":{
                        "targetType":"page",
                        "url":"我的健身数据.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33a9aeecaef64beab742080991d89d4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":241,
              "y":254},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c21ae329c0a14d67ab3215df52755e31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":241,
                  "y":254},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的评价（持卡人评价我）",
                      "target":{
                        "targetType":"page",
                        "url":"我的评价（持卡人评价我）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed4718d0f6ff4921bc41036968c53348",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":168,
              "y":254},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a037b7f3c5724306a32a88cbf35a3b90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":168,
                  "y":254},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的交易",
                      "target":{
                        "targetType":"page",
                        "url":"我的交易.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21a2469e7b8a43219a3a44b786db7022",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":94,
              "y":254},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e9c8428ecbf499eaaa7c02026fdb282",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":94,
                  "y":254},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 关注的商户详情",
                      "target":{
                        "targetType":"page",
                        "url":"关注的商户详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df1577387e514321a16cfb4a61c211b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":20,
              "y":254},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"132395eea16a46288ddf3e1795f3c659",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":20,
                  "y":254},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的消息（未读）",
                      "target":{
                        "targetType":"page",
                        "url":"我的消息（未读）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a42f050cf5cf4aa0b56efae9d49e1c9e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":324},
            "size":{
              "width":320,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6e5d16e6f2b41dcbd6b4fcd042c3f15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":324},
                "size":{
                  "width":320,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的评价（持卡人评价我）/u14.png"}},
{
          "id":"46271dd2c4964b01abbeac45db68a924",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":39,
              "y":332},
            "size":{
              "width":120,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cbfc0796f714a36b7a8d3544424684d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":39,
                  "y":332},
                "size":{
                  "width":120,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的评价（商户评价我）",
                      "target":{
                        "targetType":"page",
                        "url":"我的评价（商户评价我）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "92e12523504849308e2c7f0d1f93e1d4":{
      "scriptId":"u0"},
    "70af33cc3fe547899ec30e3c70c2dc90":{
      "scriptId":"u1"},
    "f7224360d853454091b119bbc92b90b6":{
      "scriptId":"u2"},
    "f1ecad83aa01413cb4f0644d5bc51d10":{
      "scriptId":"u3"},
    "ffc1a57d7ae24da2bc4cfdb95ec6742b":{
      "scriptId":"u4"},
    "c9ac7fe0012448569fa015497e9aa81d":{
      "scriptId":"u5"},
    "33a9aeecaef64beab742080991d89d4e":{
      "scriptId":"u6"},
    "c21ae329c0a14d67ab3215df52755e31":{
      "scriptId":"u7"},
    "ed4718d0f6ff4921bc41036968c53348":{
      "scriptId":"u8"},
    "a037b7f3c5724306a32a88cbf35a3b90":{
      "scriptId":"u9"},
    "21a2469e7b8a43219a3a44b786db7022":{
      "scriptId":"u10"},
    "5e9c8428ecbf499eaaa7c02026fdb282":{
      "scriptId":"u11"},
    "df1577387e514321a16cfb4a61c211b4":{
      "scriptId":"u12"},
    "132395eea16a46288ddf3e1795f3c659":{
      "scriptId":"u13"},
    "a42f050cf5cf4aa0b56efae9d49e1c9e":{
      "scriptId":"u14"},
    "e6e5d16e6f2b41dcbd6b4fcd042c3f15":{
      "scriptId":"u15"},
    "46271dd2c4964b01abbeac45db68a924":{
      "scriptId":"u16"},
    "9cbfc0796f714a36b7a8d3544424684d":{
      "scriptId":"u17"}}});