$axure.loadCurrentPage({
  "url":"确认售出页.html",
  "generationDate":new Date(1432847388144.24),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c4081039ccde4b859c11ebbc6e7a67fb",
    "type":"Axure:Page",
    "name":"确认售出页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"64e5a359a8584e698e602bff413d9790",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":548}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcb7c6c8c0264da8b2c199e112b1e66a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":548}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 付款说明",
                      "target":{
                        "targetType":"page",
                        "url":"付款说明.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/确认售出页/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "64e5a359a8584e698e602bff413d9790":{
      "scriptId":"u0"},
    "dcb7c6c8c0264da8b2c199e112b1e66a":{
      "scriptId":"u1"}}});