$axure.loadCurrentPage({
  "url":"我的劲态（二维码）.html",
  "generationDate":new Date(1432921477649.36),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5f94413608f64413a70807e7516be86c",
    "type":"Axure:Page",
    "name":"我的劲态（二维码）",
    "notes":{
      "默认":"<p><span>1.会员卡信息只对持卡人可见。持卡人可以看到卡下面的交易信息，不同的卡不同的交易信息。</span></p><p><span>2.非持卡人只能看到交易记录。</span></p><p><span>3.添加会员卡</span><span>入口</span><span>：一是通过会员手机号码自动关联填充，二是用户手动添加</span><span>相关字段</span><span>。</span></p><p><span>&nbsp;</span></p>"},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"903a38b12354490982fee2fa34b4f5bc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":-20},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79dd8d6241cb4a488f4bfa788a0e59ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":-20},
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的劲态（二维码）/u0.png"}},
{
          "id":"10f61e91d2e04468804ab5dbefa0e468",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":276,
              "y":4},
            "size":{
              "width":43,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"042992cfb513456cb6b2e453c261ec20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":276,
                  "y":4},
                "size":{
                  "width":43,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的健身数据",
                      "target":{
                        "targetType":"page",
                        "url":"我的健身数据.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d667c4bd93464e9c93af2e7580e5dd6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":240,
              "y":232},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aff0108cc480481484ea40043fd31d97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":240,
                  "y":232},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的评价（持卡人评价我）",
                      "target":{
                        "targetType":"page",
                        "url":"我的评价（持卡人评价我）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9869b801b93b45bfb1ced792dcadb21a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":167,
              "y":232},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cae3d5d7b4014145b6399d6fda93be93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":167,
                  "y":232},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的交易",
                      "target":{
                        "targetType":"page",
                        "url":"我的交易.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df3699885fc840e4b5b3d40173019395",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":93,
              "y":232},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7a74fb9acc24acf86f95951b9430a2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":93,
                  "y":232},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的劲态（默认关注）",
                      "target":{
                        "targetType":"page",
                        "url":"我的劲态（默认关注）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74777bcb01ec464ebd026c36a3d7c11d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":19,
              "y":232},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95cdd29d1d0a44ce8c97e392a96b5f21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":19,
                  "y":232},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的消息（未读）",
                      "target":{
                        "targetType":"page",
                        "url":"我的消息（未读）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ebfa90045364c6ca393890e782099b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":270,
              "y":160},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d25bfaa347bf496d84f55bf189b287ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":270,
                  "y":160},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的劲态（默认关注）",
                      "target":{
                        "targetType":"page",
                        "url":"我的劲态（默认关注）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96f426f177f14e4ab80f41d4813335ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":4,
              "y":4},
            "size":{
              "width":44,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"472e5a78704e4c52aabc772f71d83f6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":4,
                  "y":4},
                "size":{
                  "width":44,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 左侧边栏",
                      "target":{
                        "targetType":"page",
                        "url":"左侧边栏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56278cb3c96e4c489e42331b82368aa3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-1,
              "y":298},
            "size":{
              "width":320,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc6e90d19f2a4a6e80bf9c21fe074b61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-1,
                  "y":298},
                "size":{
                  "width":320,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的劲态（二维码）/u16.png"}},
{
          "id":"7f5558fdfb834593a14871ed2674cb8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":163,
              "y":302},
            "size":{
              "width":150,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8685c7f889644fdb83f30455e436ce6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":163,
                  "y":302},
                "size":{
                  "width":150,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的消息（已读）",
                      "target":{
                        "targetType":"page",
                        "url":"我的消息（已读）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e7630224c04b4f82b6a22e7effd3863c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":4,
              "y":302},
            "size":{
              "width":150,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85a8d8c92ff94e519e83c4d744de8bc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":4,
                  "y":302},
                "size":{
                  "width":150,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"386ba388a08d44f687ee2e536840ae04",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-1,
              "y":336},
            "size":{
              "width":320,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a310dc0b8e474ba48ecc1ddd42837ed5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-1,
                  "y":336},
                "size":{
                  "width":320,
                  "height":63}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的劲态（二维码）/u22.png"}},
{
          "id":"74b5bc2fb1d74ca18e2e3c1d1a43b447",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":9,
              "y":342},
            "size":{
              "width":280,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44954411700a4bcfbce96e42f7524ec8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":9,
                  "y":342},
                "size":{
                  "width":280,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 消息详情",
                      "target":{
                        "targetType":"page",
                        "url":"消息详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"67c1e3eb54dc47f7a5bb176fca51f12a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6FCEB6,
              "opacity":1},
            "location":{
              "x":9,
              "y":363},
            "size":{
              "width":280,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bac74aae05f648638349c5edf9847055",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6FCEB6,
                  "opacity":1},
                "location":{
                  "x":9,
                  "y":363},
                "size":{
                  "width":280,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 消息详情",
                      "target":{
                        "targetType":"page",
                        "url":"消息详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ac0dba53aad4f12892469c944096a3f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-1,
              "y":402},
            "size":{
              "width":320,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8be296908b9463dbbbe41c2ef07471d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-1,
                  "y":402},
                "size":{
                  "width":320,
                  "height":63}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的劲态（二维码）/u22.png"}},
{
          "id":"cb7b9cce25b04d7b9a0d12ce8dd779af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":9,
              "y":408},
            "size":{
              "width":280,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0433878f0fa7433e8168001756a2ffc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":9,
                  "y":408},
                "size":{
                  "width":280,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 消息详情",
                      "target":{
                        "targetType":"page",
                        "url":"消息详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06d05bba64c745e9b684541b22f5ceac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6FCEB6,
              "opacity":1},
            "location":{
              "x":9,
              "y":429},
            "size":{
              "width":280,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bda17af766114ec1bf51262a2a34e245",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6FCEB6,
                  "opacity":1},
                "location":{
                  "x":9,
                  "y":429},
                "size":{
                  "width":280,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 消息详情",
                      "target":{
                        "targetType":"page",
                        "url":"消息详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"500e45d2446249beaf60e1955647fd25",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-1,
              "y":466},
            "size":{
              "width":320,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be5c7681801b4d70abea35f645b43298",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-1,
                  "y":466},
                "size":{
                  "width":320,
                  "height":63}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的劲态（二维码）/u22.png"}},
{
          "id":"6379a9700f33445689e46b0895f48a38",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":9,
              "y":472},
            "size":{
              "width":280,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c7ab512e22c4814acadf41c5c6062a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":9,
                  "y":472},
                "size":{
                  "width":280,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 消息详情",
                      "target":{
                        "targetType":"page",
                        "url":"消息详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff9eecd4e23a47908ef49369c1fddbc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6FCEB6,
              "opacity":1},
            "location":{
              "x":9,
              "y":493},
            "size":{
              "width":280,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06f61ac9df1d4104819c8d2abc5f8eb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6FCEB6,
                  "opacity":1},
                "location":{
                  "x":9,
                  "y":493},
                "size":{
                  "width":280,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 消息详情",
                      "target":{
                        "targetType":"page",
                        "url":"消息详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "903a38b12354490982fee2fa34b4f5bc":{
      "scriptId":"u0"},
    "79dd8d6241cb4a488f4bfa788a0e59ac":{
      "scriptId":"u1"},
    "10f61e91d2e04468804ab5dbefa0e468":{
      "scriptId":"u2"},
    "042992cfb513456cb6b2e453c261ec20":{
      "scriptId":"u3"},
    "d667c4bd93464e9c93af2e7580e5dd6b":{
      "scriptId":"u4"},
    "aff0108cc480481484ea40043fd31d97":{
      "scriptId":"u5"},
    "9869b801b93b45bfb1ced792dcadb21a":{
      "scriptId":"u6"},
    "cae3d5d7b4014145b6399d6fda93be93":{
      "scriptId":"u7"},
    "df3699885fc840e4b5b3d40173019395":{
      "scriptId":"u8"},
    "c7a74fb9acc24acf86f95951b9430a2e":{
      "scriptId":"u9"},
    "74777bcb01ec464ebd026c36a3d7c11d":{
      "scriptId":"u10"},
    "95cdd29d1d0a44ce8c97e392a96b5f21":{
      "scriptId":"u11"},
    "6ebfa90045364c6ca393890e782099b7":{
      "scriptId":"u12"},
    "d25bfaa347bf496d84f55bf189b287ff":{
      "scriptId":"u13"},
    "96f426f177f14e4ab80f41d4813335ec":{
      "scriptId":"u14"},
    "472e5a78704e4c52aabc772f71d83f6a":{
      "scriptId":"u15"},
    "56278cb3c96e4c489e42331b82368aa3":{
      "scriptId":"u16"},
    "dc6e90d19f2a4a6e80bf9c21fe074b61":{
      "scriptId":"u17"},
    "7f5558fdfb834593a14871ed2674cb8c":{
      "scriptId":"u18"},
    "8685c7f889644fdb83f30455e436ce6f":{
      "scriptId":"u19"},
    "e7630224c04b4f82b6a22e7effd3863c":{
      "scriptId":"u20"},
    "85a8d8c92ff94e519e83c4d744de8bc7":{
      "scriptId":"u21"},
    "386ba388a08d44f687ee2e536840ae04":{
      "scriptId":"u22"},
    "a310dc0b8e474ba48ecc1ddd42837ed5":{
      "scriptId":"u23"},
    "74b5bc2fb1d74ca18e2e3c1d1a43b447":{
      "scriptId":"u24"},
    "44954411700a4bcfbce96e42f7524ec8":{
      "scriptId":"u25"},
    "67c1e3eb54dc47f7a5bb176fca51f12a":{
      "scriptId":"u26"},
    "bac74aae05f648638349c5edf9847055":{
      "scriptId":"u27"},
    "8ac0dba53aad4f12892469c944096a3f":{
      "scriptId":"u28"},
    "d8be296908b9463dbbbe41c2ef07471d":{
      "scriptId":"u29"},
    "cb7b9cce25b04d7b9a0d12ce8dd779af":{
      "scriptId":"u30"},
    "0433878f0fa7433e8168001756a2ffc1":{
      "scriptId":"u31"},
    "06d05bba64c745e9b684541b22f5ceac":{
      "scriptId":"u32"},
    "bda17af766114ec1bf51262a2a34e245":{
      "scriptId":"u33"},
    "500e45d2446249beaf60e1955647fd25":{
      "scriptId":"u34"},
    "be5c7681801b4d70abea35f645b43298":{
      "scriptId":"u35"},
    "6379a9700f33445689e46b0895f48a38":{
      "scriptId":"u36"},
    "6c7ab512e22c4814acadf41c5c6062a5":{
      "scriptId":"u37"},
    "ff9eecd4e23a47908ef49369c1fddbc8":{
      "scriptId":"u38"},
    "06f61ac9df1d4104819c8d2abc5f8eb0":{
      "scriptId":"u39"}}});