$axure.loadCurrentPage({
  "url":"我的劲态（二维码）.html",
  "generationDate":new Date(1429794606991.08),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"edbe79714f77495eaf8b5090ae18a3c6",
    "type":"Axure:Page",
    "name":"我的劲态（二维码）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1725a44661ae4429a4b74327125e40a5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":215}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9603798122241f19769473404d10a15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":215}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的劲态（二维码）/u0.png"}},
{
          "id":"8fb12d23423741cd9e0d570ca911c586",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":258},
            "size":{
              "width":320,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba4e3cb1b97b48f78bade5bb63e41d92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":258},
                "size":{
                  "width":320,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的劲态（二维码）/u2.png"}},
{
          "id":"7ffd2831bdc74fa3903dfeb85ae3ce9b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":325},
            "size":{
              "width":320,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"196dcf5a22b44c2aafb7e3d4cff54552",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":325},
                "size":{
                  "width":320,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的劲态（二维码）/u2.png"}},
{
          "id":"6ace5e2395494b6aa32150bdce7bcd93",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":479},
            "size":{
              "width":320,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bd61fa3cfd1449fae586b2bd7e9c222",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":479},
                "size":{
                  "width":320,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商户详情页（交易中）",
                      "target":{
                        "targetType":"page",
                        "url":"商户详情页（交易中）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的劲态（二维码）/u6.png"}},
{
          "id":"e606057954f64046ba71a7109361342f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":402},
            "size":{
              "width":320,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"804a4cb34b8b4473a23333f0da213e26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":402},
                "size":{
                  "width":320,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商户详情页（交易中）",
                      "target":{
                        "targetType":"page",
                        "url":"商户详情页（交易中）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的劲态（二维码）/u6.png"}},
{
          "id":"0e4ef94012ae45458fe600185b31b101",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":556},
            "size":{
              "width":62,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a8ab1d4cc634baab0a9df9a434af2d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":556},
                "size":{
                  "width":62,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的评价",
                      "target":{
                        "targetType":"page",
                        "url":"我的评价.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的劲态（二维码）/u10.png"}},
{
          "id":"871c46afbc7d4de8929bb0f3ae557446",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":556},
            "size":{
              "width":62,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4ef9e8528fe46fbabbe026606ec4385",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":83,
                  "y":556},
                "size":{
                  "width":62,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的交易",
                      "target":{
                        "targetType":"page",
                        "url":"我的交易.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的劲态（二维码）/u12.png"}},
{
          "id":"45d38d89eeab4448b397f6496d79e7f9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":173,
              "y":556},
            "size":{
              "width":62,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82bc9764c46c4d06a542a938a48d434d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":173,
                  "y":556},
                "size":{
                  "width":62,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我关注的商户",
                      "target":{
                        "targetType":"page",
                        "url":"我关注的商户.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的劲态（二维码）/u14.png"}},
{
          "id":"762c87c2a832450f87ea4a2c04656890",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":258,
              "y":556},
            "size":{
              "width":62,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f584b6bd252342d7bbc21821e55e028c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":258,
                  "y":556},
                "size":{
                  "width":62,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的消息",
                      "target":{
                        "targetType":"page",
                        "url":"我的消息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的劲态（二维码）/u16.png"}},
{
          "id":"2a142e6f9dff4d4e851a5b0df2aebb3a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":15},
            "size":{
              "width":22,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bea4ffc95a34f1bb2768384356cb9bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":15},
                "size":{
                  "width":22,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 左侧边栏",
                      "target":{
                        "targetType":"page",
                        "url":"左侧边栏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/左侧边栏/u2.png"}},
{
          "id":"8fd6cb3022c04dd89cb34967fff103bc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":215},
            "size":{
              "width":320,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"419f90a55f6641b4bcfcf5e2c0fcd924",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":215},
                "size":{
                  "width":320,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的劲态（二维码）/u20.png"}},
{
          "id":"8d8237c0df9e4155a4bb79de400659ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":162,
              "y":223},
            "size":{
              "width":120,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c09cd3c384948c5a6969996cd541b73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":162,
                  "y":223},
                "size":{
                  "width":120,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 持卡人评价我",
                      "target":{
                        "targetType":"page",
                        "url":"持卡人评价我.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e94f4adec9344a3e80f25de1d36dc765",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":277,
              "y":4},
            "size":{
              "width":43,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb045e33dd2947e8be9a5e80d4d07070",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":277,
                  "y":4},
                "size":{
                  "width":43,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的健身数据",
                      "target":{
                        "targetType":"page",
                        "url":"我的健身数据.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1725a44661ae4429a4b74327125e40a5":{
      "scriptId":"u0"},
    "c9603798122241f19769473404d10a15":{
      "scriptId":"u1"},
    "8fb12d23423741cd9e0d570ca911c586":{
      "scriptId":"u2"},
    "ba4e3cb1b97b48f78bade5bb63e41d92":{
      "scriptId":"u3"},
    "7ffd2831bdc74fa3903dfeb85ae3ce9b":{
      "scriptId":"u4"},
    "196dcf5a22b44c2aafb7e3d4cff54552":{
      "scriptId":"u5"},
    "6ace5e2395494b6aa32150bdce7bcd93":{
      "scriptId":"u6"},
    "2bd61fa3cfd1449fae586b2bd7e9c222":{
      "scriptId":"u7"},
    "e606057954f64046ba71a7109361342f":{
      "scriptId":"u8"},
    "804a4cb34b8b4473a23333f0da213e26":{
      "scriptId":"u9"},
    "0e4ef94012ae45458fe600185b31b101":{
      "scriptId":"u10"},
    "3a8ab1d4cc634baab0a9df9a434af2d0":{
      "scriptId":"u11"},
    "871c46afbc7d4de8929bb0f3ae557446":{
      "scriptId":"u12"},
    "e4ef9e8528fe46fbabbe026606ec4385":{
      "scriptId":"u13"},
    "45d38d89eeab4448b397f6496d79e7f9":{
      "scriptId":"u14"},
    "82bc9764c46c4d06a542a938a48d434d":{
      "scriptId":"u15"},
    "762c87c2a832450f87ea4a2c04656890":{
      "scriptId":"u16"},
    "f584b6bd252342d7bbc21821e55e028c":{
      "scriptId":"u17"},
    "2a142e6f9dff4d4e851a5b0df2aebb3a":{
      "scriptId":"u18"},
    "3bea4ffc95a34f1bb2768384356cb9bc":{
      "scriptId":"u19"},
    "8fd6cb3022c04dd89cb34967fff103bc":{
      "scriptId":"u20"},
    "419f90a55f6641b4bcfcf5e2c0fcd924":{
      "scriptId":"u21"},
    "8d8237c0df9e4155a4bb79de400659ef":{
      "scriptId":"u22"},
    "6c09cd3c384948c5a6969996cd541b73":{
      "scriptId":"u23"},
    "e94f4adec9344a3e80f25de1d36dc765":{
      "scriptId":"u24"},
    "fb045e33dd2947e8be9a5e80d4d07070":{
      "scriptId":"u25"}}});