$axure.loadCurrentPage({
  "url":"我的劲态（二维码）.html",
  "generationDate":new Date(1430066323616.95),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5f94413608f64413a70807e7516be86c",
    "type":"Axure:Page",
    "name":"我的劲态（二维码）",
    "notes":{
      "默认":"<p><span>1.会员卡信息只对持卡人可见。持卡人可以看到卡下面的交易信息，不同的卡不同的交易信息。</span></p><p><span>2.非持卡人只能看到交易记录。</span></p><p><span>3.添加会员卡</span><span>入口</span><span>：一是通过会员手机号码自动关联填充，二是用户手动添加</span><span>相关字段</span><span>。</span></p><p><span>&nbsp;</span></p>"},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"903a38b12354490982fee2fa34b4f5bc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79dd8d6241cb4a488f4bfa788a0e59ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的劲态（二维码）/u0.png"}},
{
          "id":"c8ce29ab19fc40559f674db986c858d1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":36},
            "size":{
              "width":22,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fca35595e5941bda7de48497b9e938e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":36},
                "size":{
                  "width":22,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 左侧边栏",
                      "target":{
                        "targetType":"page",
                        "url":"左侧边栏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/左侧边栏/u2.png"}},
{
          "id":"10f61e91d2e04468804ab5dbefa0e468",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":276,
              "y":24},
            "size":{
              "width":43,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"042992cfb513456cb6b2e453c261ec20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":276,
                  "y":24},
                "size":{
                  "width":43,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的健身数据",
                      "target":{
                        "targetType":"page",
                        "url":"我的健身数据.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d667c4bd93464e9c93af2e7580e5dd6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":240,
              "y":252},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aff0108cc480481484ea40043fd31d97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":240,
                  "y":252},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的评价（持卡人评价我）",
                      "target":{
                        "targetType":"page",
                        "url":"我的评价（持卡人评价我）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9869b801b93b45bfb1ced792dcadb21a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":167,
              "y":252},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cae3d5d7b4014145b6399d6fda93be93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":167,
                  "y":252},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的交易",
                      "target":{
                        "targetType":"page",
                        "url":"我的交易.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df3699885fc840e4b5b3d40173019395",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":93,
              "y":252},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7a74fb9acc24acf86f95951b9430a2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":93,
                  "y":252},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 关注的商户详情",
                      "target":{
                        "targetType":"page",
                        "url":"关注的商户详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74777bcb01ec464ebd026c36a3d7c11d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":19,
              "y":252},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95cdd29d1d0a44ce8c97e392a96b5f21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":19,
                  "y":252},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的消息（未读）",
                      "target":{
                        "targetType":"page",
                        "url":"我的消息（未读）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ebfa90045364c6ca393890e782099b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":270,
              "y":180},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d25bfaa347bf496d84f55bf189b287ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":270,
                  "y":180},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的劲态（默认关注）",
                      "target":{
                        "targetType":"page",
                        "url":"我的劲态（默认关注）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "903a38b12354490982fee2fa34b4f5bc":{
      "scriptId":"u0"},
    "79dd8d6241cb4a488f4bfa788a0e59ac":{
      "scriptId":"u1"},
    "c8ce29ab19fc40559f674db986c858d1":{
      "scriptId":"u2"},
    "3fca35595e5941bda7de48497b9e938e":{
      "scriptId":"u3"},
    "10f61e91d2e04468804ab5dbefa0e468":{
      "scriptId":"u4"},
    "042992cfb513456cb6b2e453c261ec20":{
      "scriptId":"u5"},
    "d667c4bd93464e9c93af2e7580e5dd6b":{
      "scriptId":"u6"},
    "aff0108cc480481484ea40043fd31d97":{
      "scriptId":"u7"},
    "9869b801b93b45bfb1ced792dcadb21a":{
      "scriptId":"u8"},
    "cae3d5d7b4014145b6399d6fda93be93":{
      "scriptId":"u9"},
    "df3699885fc840e4b5b3d40173019395":{
      "scriptId":"u10"},
    "c7a74fb9acc24acf86f95951b9430a2e":{
      "scriptId":"u11"},
    "74777bcb01ec464ebd026c36a3d7c11d":{
      "scriptId":"u12"},
    "95cdd29d1d0a44ce8c97e392a96b5f21":{
      "scriptId":"u13"},
    "6ebfa90045364c6ca393890e782099b7":{
      "scriptId":"u14"},
    "d25bfaa347bf496d84f55bf189b287ff":{
      "scriptId":"u15"}}});