$axure.loadCurrentPage({
  "url":"推送通知开关提醒.html",
  "generationDate":new Date(1430066324352.99),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1952c8326deb4d02927bf22e170f7e7a",
    "type":"Axure:Page",
    "name":"推送通知开关提醒",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fda4e35b52f248e1bc189e1326925dc1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":542}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74bb851546e748f6b521775ad32329e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":542}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u0.png"}},
{
          "id":"2f9eb64e06134016b6961192c324b804",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a7a8b45235541e989ea01b9951e7bfe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u2.png"}},
{
          "id":"d662acc762fd42498c8ade8b267ff8b2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":44},
            "size":{
              "width":320,
              "height":270}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64e0111379494ee7bae9022dc8727c45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":44},
                "size":{
                  "width":320,
                  "height":270}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u4.png"}},
{
          "id":"97cc912c8ea140219a09fcb2fa592295",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":490},
            "size":{
              "width":292,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0059336459745b296124b2ee6e0c132",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":490},
                "size":{
                  "width":292,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录页面",
                      "target":{
                        "targetType":"page",
                        "url":"登录页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/设置/u6.png"}},
{
          "id":"7f4bb2cf938f4646ad114af4cd45cd88",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-1,
              "y":118},
            "size":{
              "width":320,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b77708750214438e969ae70f0bee5421",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-1,
                  "y":118},
                "size":{
                  "width":320,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 推送通知开关提醒",
                      "target":{
                        "targetType":"page",
                        "url":"推送通知开关提醒.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/设置/u8.png"}},
{
          "id":"8610041cf3f746cb96c42b60f580a376",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "opacity":"0",
            "location":{
              "x":4,
              "y":161},
            "size":{
              "width":302,
              "height":33},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"066a723545d54e6eba893c8e830c919c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "opacity":"0",
                "location":{
                  "x":4,
                  "y":161},
                "size":{
                  "width":302,
                  "height":33},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 意见反馈",
                      "target":{
                        "targetType":"page",
                        "url":"意见反馈.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"546c33d385ad4a5bbde00b83af8b6918",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "opacity":"0",
            "location":{
              "x":0,
              "y":240},
            "size":{
              "width":302,
              "height":33},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94c659e95aaa48d3afe5b4265b0d52b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "opacity":"0",
                "location":{
                  "x":0,
                  "y":240},
                "size":{
                  "width":302,
                  "height":33},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 关于劲态",
                      "target":{
                        "targetType":"page",
                        "url":"关于劲态.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"914c9c9d157e4ddbb5740a57ecdc9c24",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "opacity":"0",
            "location":{
              "x":2,
              "y":279},
            "size":{
              "width":302,
              "height":33},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78db42643b6c43538dfd5235759fafac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "opacity":"0",
                "location":{
                  "x":2,
                  "y":279},
                "size":{
                  "width":302,
                  "height":33},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 帮助",
                      "target":{
                        "targetType":"page",
                        "url":"帮助.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43f84fc023724c92a031090d461a2681",
          "label":"短信通知提醒",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":130},
            "size":{
              "width":266,
              "height":170}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"45b6b05612d548499b10a665493df1d6",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8bc5152890e2467a8f11b7f53f9e093b",
                  "label":"",
                  "parentDynamicPanel":"43f84fc023724c92a031090d461a2681",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":266,
                      "height":172}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6848d38de8b147c49f9a39b602173931",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"43f84fc023724c92a031090d461a2681",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":266,
                          "height":172}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 短信通知提醒,<br>隐藏 (Image)",
                              "objectsToFades":[{
                                  "objectPath":["43f84fc023724c92a031090d461a2681"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["8bc5152890e2467a8f11b7f53f9e093b"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/推送通知开关提醒/u17.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "fda4e35b52f248e1bc189e1326925dc1":{
      "scriptId":"u0"},
    "74bb851546e748f6b521775ad32329e6":{
      "scriptId":"u1"},
    "2f9eb64e06134016b6961192c324b804":{
      "scriptId":"u2"},
    "5a7a8b45235541e989ea01b9951e7bfe":{
      "scriptId":"u3"},
    "d662acc762fd42498c8ade8b267ff8b2":{
      "scriptId":"u4"},
    "64e0111379494ee7bae9022dc8727c45":{
      "scriptId":"u5"},
    "97cc912c8ea140219a09fcb2fa592295":{
      "scriptId":"u6"},
    "e0059336459745b296124b2ee6e0c132":{
      "scriptId":"u7"},
    "7f4bb2cf938f4646ad114af4cd45cd88":{
      "scriptId":"u8"},
    "b77708750214438e969ae70f0bee5421":{
      "scriptId":"u9"},
    "8610041cf3f746cb96c42b60f580a376":{
      "scriptId":"u10"},
    "066a723545d54e6eba893c8e830c919c":{
      "scriptId":"u11"},
    "546c33d385ad4a5bbde00b83af8b6918":{
      "scriptId":"u12"},
    "94c659e95aaa48d3afe5b4265b0d52b7":{
      "scriptId":"u13"},
    "914c9c9d157e4ddbb5740a57ecdc9c24":{
      "scriptId":"u14"},
    "78db42643b6c43538dfd5235759fafac":{
      "scriptId":"u15"},
    "43f84fc023724c92a031090d461a2681":{
      "scriptId":"u16"},
    "8bc5152890e2467a8f11b7f53f9e093b":{
      "scriptId":"u17"},
    "6848d38de8b147c49f9a39b602173931":{
      "scriptId":"u18"}}});