$axure.loadCurrentPage({
  "url":"发布成功提示.html",
  "generationDate":new Date(1432847387625.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b340a1f79e2c4bf0b1a2b31013d5b5d8",
    "type":"Axure:Page",
    "name":"发布成功提示",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"687e551250f1491591adf6969728ffd2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":548}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9e7b9ba33454b5299a3e4a6f53053a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":548}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 买时间",
                      "target":{
                        "targetType":"page",
                        "url":"买时间.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/发布成功提示/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "687e551250f1491591adf6969728ffd2":{
      "scriptId":"u0"},
    "e9e7b9ba33454b5299a3e4a6f53053a6":{
      "scriptId":"u1"}}});