$axure.loadCurrentPage({
  "url":"发布出售成功.html",
  "generationDate":new Date(1432921475191.22),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d8adde91d900417fad855c0c39d6289e",
    "type":"Axure:Page",
    "name":"发布出售成功",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"58b510c6597341d793d32b457b68573d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":548}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b52ac0718494472b75368da7a64ed53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":548}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 卖时间",
                      "target":{
                        "targetType":"page",
                        "url":"卖时间.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/发布成功提示/u0.png"}},
{
          "id":"1ff857f3eb034f4ab72ab0149f3171ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE6E6E6},
            "location":{
              "x":50,
              "y":170},
            "size":{
              "width":220,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE6E6E6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"faa891e6f4644949a5ebd3a87e3d98c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE6E6E6},
                "location":{
                  "x":50,
                  "y":170},
                "size":{
                  "width":220,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE6E6E6}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 卖时间",
                      "target":{
                        "targetType":"page",
                        "url":"卖时间.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/发布成功提示/u2.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "58b510c6597341d793d32b457b68573d":{
      "scriptId":"u0"},
    "3b52ac0718494472b75368da7a64ed53":{
      "scriptId":"u1"},
    "1ff857f3eb034f4ab72ab0149f3171ad":{
      "scriptId":"u2"},
    "faa891e6f4644949a5ebd3a87e3d98c8":{
      "scriptId":"u3"}}});