$axure.loadCurrentPage({
  "url":"发布求购信息.html",
  "generationDate":new Date(1432847387554.2),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"05b2aa0bf6cf4658b19d544b087cd9a6",
    "type":"Axure:Page",
    "name":"发布求购信息",
    "notes":{
      "默认":"<p><span>点击ID查看 买 / 卖方的&nbsp;&nbsp; 个人详情页。</span></p>"},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ab171e7e716e4727a3fd940af2fe55a2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":0},
            "size":{
              "width":216,
              "height":548}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"748927ed8bdf4e3ababc34d1a90f7f7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":106,
                  "y":0},
                "size":{
                  "width":216,
                  "height":548}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布求购信息/u0.jpg"}},
{
          "id":"fa27548a09d04fe9a56e3c224a0a89f6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":106,
              "height":548}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52837c2932ec44228cf0533343a2e4ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":106,
                  "height":548}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 买时间",
                      "target":{
                        "targetType":"page",
                        "url":"买时间.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/出售详情页/u0.png"}},
{
          "id":"3477ed7380e546a7b1e239dde6abd0a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":152,
              "y":10},
            "size":{
              "width":112,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"426832b173544f39a0ad69f18d3c48db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":152,
                  "y":10},
                "size":{
                  "width":112,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2691318bffd14d969de8d3071284a875",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":118,
              "y":49},
            "size":{
              "width":146,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa8d9ac511ed463dbde6b8fd0b7adef2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":118,
                  "y":49},
                "size":{
                  "width":146,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (Image) 向下滑动 500 毫秒,<br>求购_区域列表 向下滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["50471f0c4bf645a99acf3556e972b33e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}},
{
                          "objectPath":["b77db0f2ee6b453a9d67df0b85d99d05"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0df0e9b19af04a14b64a135824f6b0e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":118,
              "y":93},
            "size":{
              "width":146,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"083397ed8b9e4215b671974ccd8955c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":118,
                  "y":93},
                "size":{
                  "width":146,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 求购_选择门店 向下滑动 500 毫秒,<br>(Image) 向下滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["723ba0208acf493d9ec083b6b5c1841c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}},
{
                          "objectPath":["c8fad531095544deaf3ca4c8acb0b4a6"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"041dfc5ad8cb4b8a8815a6c4dab489c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":118,
              "y":138},
            "size":{
              "width":182,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9873788d44147f9b26fcb7c37ff24d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":118,
                  "y":138},
                "size":{
                  "width":182,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 求购_选择品牌 向下滑动 500 毫秒,<br>(Image) 向下滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["49bf35c814ef4ef09e55ba05f7fcbb0d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}},
{
                          "objectPath":["e309d6081afe42f787d2a1b6e8769bdf"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13fe9938916947ccabdb868ef8572122",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":118,
              "y":182},
            "size":{
              "width":182,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e7cb9f52d594997bc9c73a682d0cba8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":118,
                  "y":182},
                "size":{
                  "width":182,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb9715f96e134da098bbeb0c8619d64e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":118,
              "y":226},
            "size":{
              "width":198,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb39cd9cbae14b119b6b35891b972839",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":118,
                  "y":226},
                "size":{
                  "width":198,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 买时间选择日期 向上滑动 500 毫秒,<br>(Image) 向上滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["1eb8c834b62e499fa286d1c2494a3895"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideUp",
                              "duration":500,
                              "showType":"none"}}},
{
                          "objectPath":["e134a6698e944d00984694482423f171"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideUp",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c02112bb2e8f4682a3e19dff6c0001e3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":489},
            "size":{
              "width":216,
              "height":59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4af505ae99042c6a01706fb82592151",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":106,
                  "y":489},
                "size":{
                  "width":216,
                  "height":59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/出售详情页/u18.png"}},
{
          "id":"3bf39b26e2f7420ab7bca05d43c3316c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":426},
            "size":{
              "width":216,
              "height":59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdce6dfc59284d7da616d6d4b4011459",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":106,
                  "y":426},
                "size":{
                  "width":216,
                  "height":59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/出售详情页/u18.png"}},
{
          "id":"1eb8c834b62e499fa286d1c2494a3895",
          "label":"买时间选择日期",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":2,
              "y":332},
            "size":{
              "width":320,
              "height":216},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"c4ccfdf199334c87a58639841f869858",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e134a6698e944d00984694482423f171",
                  "label":"",
                  "parentDynamicPanel":"1eb8c834b62e499fa286d1c2494a3895",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":216}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"231a160a1c044bcd8372a15a3710a4ea",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1eb8c834b62e499fa286d1c2494a3895",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":216}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 买时间选择日期,<br>(Image)",
                              "objectsToFades":[{
                                  "objectPath":["1eb8c834b62e499fa286d1c2494a3895"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["e134a6698e944d00984694482423f171"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/发布求购信息/u21.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"ec48488cc63845258fa74ea20ba35ba0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":109,
              "y":431},
            "size":{
              "width":210,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"218d519d87934e7289e604225118aa40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":109,
                  "y":431},
                "size":{
                  "width":210,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 发布成功提示",
                      "target":{
                        "targetType":"page",
                        "url":"发布成功提示.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00bddbc410014f4ab53515c9fb0dd63f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":109,
              "y":494},
            "size":{
              "width":210,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba5a570cec144a288705ffe1ca8dd90c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":109,
                  "y":494},
                "size":{
                  "width":210,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 买时间",
                      "target":{
                        "targetType":"page",
                        "url":"买时间.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"342808d276104b5b9e0e9cdac8d90f65",
          "label":"ButtonBigSecondary",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontSize":"18px",
            "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
            "opacity":"0.6",
            "location":{
              "x":226,
              "y":68},
            "size":{
              "width":87,
              "height":102},
            "visible":false,
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74641b274c8643158cc69b8cffa1cdf7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"18px",
                "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
                "opacity":"0.6",
                "location":{
                  "x":226,
                  "y":68},
                "size":{
                  "width":87,
                  "height":102},
                "visible":false,
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索页_切换城市/buttonbigsecondary_u2.png"}},
{
          "id":"b77db0f2ee6b453a9d67df0b85d99d05",
          "label":"求购_区域列表",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":226,
              "y":68},
            "size":{
              "width":87,
              "height":102},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"baaee6567d474ef1a9c563c4b618d0a8",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"50471f0c4bf645a99acf3556e972b33e",
                  "label":"",
                  "parentDynamicPanel":"b77db0f2ee6b453a9d67df0b85d99d05",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":87,
                      "height":102}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f94900a3f7b345ae8434d98bcab62bbd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b77db0f2ee6b453a9d67df0b85d99d05",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":87,
                          "height":102}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 求购_区域列表,<br>(Image)",
                              "objectsToFades":[{
                                  "objectPath":["b77db0f2ee6b453a9d67df0b85d99d05"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["50471f0c4bf645a99acf3556e972b33e"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/搜索页_切换城市/u5.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"a3d96a61478b4e6b936bfb2ab33a7cf2",
          "label":"ButtonBigSecondary",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontSize":"18px",
            "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
            "opacity":"0.6",
            "location":{
              "x":226,
              "y":112},
            "size":{
              "width":87,
              "height":102},
            "visible":false,
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd4c42988fda45dea3090e0991329ec4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"18px",
                "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
                "opacity":"0.6",
                "location":{
                  "x":226,
                  "y":112},
                "size":{
                  "width":87,
                  "height":102},
                "visible":false,
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索页_切换城市/buttonbigsecondary_u2.png"}},
{
          "id":"723ba0208acf493d9ec083b6b5c1841c",
          "label":"求购_选择门店",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":226,
              "y":112},
            "size":{
              "width":87,
              "height":102},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"65ddd21f15504daa9b0e5aa047059c72",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c8fad531095544deaf3ca4c8acb0b4a6",
                  "label":"",
                  "parentDynamicPanel":"723ba0208acf493d9ec083b6b5c1841c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":87,
                      "height":102}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bc071a9ee9c4480caaaf2e37b61bd09b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"723ba0208acf493d9ec083b6b5c1841c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":87,
                          "height":102}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 求购_选择门店,<br>(Image)",
                              "objectsToFades":[{
                                  "objectPath":["723ba0208acf493d9ec083b6b5c1841c"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["c8fad531095544deaf3ca4c8acb0b4a6"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/发布求购信息/u35.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"11cbb333edc0481e9ee5f46d2eded33c",
          "label":"ButtonBigSecondary",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontSize":"18px",
            "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
            "opacity":"0.6",
            "location":{
              "x":226,
              "y":154},
            "size":{
              "width":87,
              "height":102},
            "visible":false,
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1b5c7950f284b1caf0cf19f97e28b48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"18px",
                "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
                "opacity":"0.6",
                "location":{
                  "x":226,
                  "y":154},
                "size":{
                  "width":87,
                  "height":102},
                "visible":false,
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索页_切换城市/buttonbigsecondary_u2.png"}},
{
          "id":"49bf35c814ef4ef09e55ba05f7fcbb0d",
          "label":"求购_选择品牌",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":226,
              "y":154},
            "size":{
              "width":87,
              "height":102},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"943a01d1db904a9e9109a0d8061713e7",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e309d6081afe42f787d2a1b6e8769bdf",
                  "label":"",
                  "parentDynamicPanel":"49bf35c814ef4ef09e55ba05f7fcbb0d",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":87,
                      "height":102}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d31b935016e04b46a23c38ef36053760",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"49bf35c814ef4ef09e55ba05f7fcbb0d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":87,
                          "height":102}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 (Image),<br>求购_选择品牌",
                              "objectsToFades":[{
                                  "objectPath":["e309d6081afe42f787d2a1b6e8769bdf"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["49bf35c814ef4ef09e55ba05f7fcbb0d"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/发布求购信息/u40.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "ab171e7e716e4727a3fd940af2fe55a2":{
      "scriptId":"u0"},
    "748927ed8bdf4e3ababc34d1a90f7f7c":{
      "scriptId":"u1"},
    "fa27548a09d04fe9a56e3c224a0a89f6":{
      "scriptId":"u2"},
    "52837c2932ec44228cf0533343a2e4ef":{
      "scriptId":"u3"},
    "3477ed7380e546a7b1e239dde6abd0a9":{
      "scriptId":"u4"},
    "426832b173544f39a0ad69f18d3c48db":{
      "scriptId":"u5"},
    "2691318bffd14d969de8d3071284a875":{
      "scriptId":"u6"},
    "aa8d9ac511ed463dbde6b8fd0b7adef2":{
      "scriptId":"u7"},
    "0df0e9b19af04a14b64a135824f6b0e3":{
      "scriptId":"u8"},
    "083397ed8b9e4215b671974ccd8955c9":{
      "scriptId":"u9"},
    "041dfc5ad8cb4b8a8815a6c4dab489c9":{
      "scriptId":"u10"},
    "e9873788d44147f9b26fcb7c37ff24d0":{
      "scriptId":"u11"},
    "13fe9938916947ccabdb868ef8572122":{
      "scriptId":"u12"},
    "8e7cb9f52d594997bc9c73a682d0cba8":{
      "scriptId":"u13"},
    "eb9715f96e134da098bbeb0c8619d64e":{
      "scriptId":"u14"},
    "eb39cd9cbae14b119b6b35891b972839":{
      "scriptId":"u15"},
    "c02112bb2e8f4682a3e19dff6c0001e3":{
      "scriptId":"u16"},
    "b4af505ae99042c6a01706fb82592151":{
      "scriptId":"u17"},
    "3bf39b26e2f7420ab7bca05d43c3316c":{
      "scriptId":"u18"},
    "cdce6dfc59284d7da616d6d4b4011459":{
      "scriptId":"u19"},
    "1eb8c834b62e499fa286d1c2494a3895":{
      "scriptId":"u20"},
    "e134a6698e944d00984694482423f171":{
      "scriptId":"u21"},
    "231a160a1c044bcd8372a15a3710a4ea":{
      "scriptId":"u22"},
    "ec48488cc63845258fa74ea20ba35ba0":{
      "scriptId":"u23"},
    "218d519d87934e7289e604225118aa40":{
      "scriptId":"u24"},
    "00bddbc410014f4ab53515c9fb0dd63f":{
      "scriptId":"u25"},
    "ba5a570cec144a288705ffe1ca8dd90c":{
      "scriptId":"u26"},
    "342808d276104b5b9e0e9cdac8d90f65":{
      "scriptId":"u27"},
    "74641b274c8643158cc69b8cffa1cdf7":{
      "scriptId":"u28"},
    "b77db0f2ee6b453a9d67df0b85d99d05":{
      "scriptId":"u29"},
    "50471f0c4bf645a99acf3556e972b33e":{
      "scriptId":"u30"},
    "f94900a3f7b345ae8434d98bcab62bbd":{
      "scriptId":"u31"},
    "a3d96a61478b4e6b936bfb2ab33a7cf2":{
      "scriptId":"u32"},
    "fd4c42988fda45dea3090e0991329ec4":{
      "scriptId":"u33"},
    "723ba0208acf493d9ec083b6b5c1841c":{
      "scriptId":"u34"},
    "c8fad531095544deaf3ca4c8acb0b4a6":{
      "scriptId":"u35"},
    "bc071a9ee9c4480caaaf2e37b61bd09b":{
      "scriptId":"u36"},
    "11cbb333edc0481e9ee5f46d2eded33c":{
      "scriptId":"u37"},
    "c1b5c7950f284b1caf0cf19f97e28b48":{
      "scriptId":"u38"},
    "49bf35c814ef4ef09e55ba05f7fcbb0d":{
      "scriptId":"u39"},
    "e309d6081afe42f787d2a1b6e8769bdf":{
      "scriptId":"u40"},
    "d31b935016e04b46a23c38ef36053760":{
      "scriptId":"u41"}}});