$axure.loadCurrentPage({
  "url":"微信登录.html",
  "generationDate":new Date(1432847386385.14),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"47ffc40360a742e4b34467edf3542073",
    "type":"Axure:Page",
    "name":"微信登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dd18da00ec0e417cb02eeb664aac3614",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":-20},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7268d4662fab4e7fb2637fdebecc238c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":-20},
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信登录/u0.png"}},
{
          "id":"6e6adb5c101d445a8ac9af41f7cc7a6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "opacity":"0",
            "location":{
              "x":8,
              "y":11},
            "size":{
              "width":72,
              "height":39},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2e3d68456d74d6b85bd85f2e75cb290",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "opacity":"0",
                "location":{
                  "x":8,
                  "y":11},
                "size":{
                  "width":72,
                  "height":39},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录页面",
                      "target":{
                        "targetType":"page",
                        "url":"登录页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a9a0fa556524fed9992cfcd5ccef9aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "opacity":"0",
            "location":{
              "x":20,
              "y":298},
            "size":{
              "width":280,
              "height":39},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b576d3a3b64a463e8642ba878e022416",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "opacity":"0",
                "location":{
                  "x":20,
                  "y":298},
                "size":{
                  "width":280,
                  "height":39},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 【我的】页面（新注册）",
                      "target":{
                        "targetType":"page",
                        "url":"【我的】页面（新注册）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"383fba14b0994297a231fd7e398ac36f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":129,
              "y":77},
            "size":{
              "width":57,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"297151a6268c4120ba44de05f3430980",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":129,
                  "y":77},
                "size":{
                  "width":57,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微信登录/u6.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "dd18da00ec0e417cb02eeb664aac3614":{
      "scriptId":"u0"},
    "7268d4662fab4e7fb2637fdebecc238c":{
      "scriptId":"u1"},
    "6e6adb5c101d445a8ac9af41f7cc7a6a":{
      "scriptId":"u2"},
    "a2e3d68456d74d6b85bd85f2e75cb290":{
      "scriptId":"u3"},
    "6a9a0fa556524fed9992cfcd5ccef9aa":{
      "scriptId":"u4"},
    "b576d3a3b64a463e8642ba878e022416":{
      "scriptId":"u5"},
    "383fba14b0994297a231fd7e398ac36f":{
      "scriptId":"u6"},
    "297151a6268c4120ba44de05f3430980":{
      "scriptId":"u7"}}});