$axure.loadCurrentPage({
  "url":"评价详情.html",
  "generationDate":new Date(1432921476788.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b828dc3ab9754a62a612d8a706abf085",
    "type":"Axure:Page",
    "name":"评价详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d04226ea9a45459a91eb0d26892432f7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":104,
              "height":548}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30ea5dad5e1f4c80a64045147d9e46f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":104,
                  "height":548}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 评价页面",
                      "target":{
                        "targetType":"page",
                        "url":"评价页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/通知详情/u0.png"}},
{
          "id":"12743918fc864653a80e64eab6187c65",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":103,
              "y":0},
            "size":{
              "width":208,
              "height":548}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e848f6b24fb944839fc8099b4e94ef24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":103,
                  "y":0},
                "size":{
                  "width":208,
                  "height":548}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 评价页面",
                      "target":{
                        "targetType":"page",
                        "url":"评价页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/通知详情/u2.jpg"}},
{
          "id":"36a9acc77a4d412995798145c0ab19d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":117,
              "y":66},
            "size":{
              "width":180,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c31b1679da243a282776f13429d2377",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":117,
                  "y":66},
                "size":{
                  "width":180,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 评价页面",
                      "target":{
                        "targetType":"page",
                        "url":"评价页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"575dfeeaaf54489ebc242ff31a0830aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":168,
              "y":19},
            "size":{
              "width":76,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fd937df0d514053a052ad453c79c869",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":168,
                  "y":19},
                "size":{
                  "width":76,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "d04226ea9a45459a91eb0d26892432f7":{
      "scriptId":"u0"},
    "30ea5dad5e1f4c80a64045147d9e46f2":{
      "scriptId":"u1"},
    "12743918fc864653a80e64eab6187c65":{
      "scriptId":"u2"},
    "e848f6b24fb944839fc8099b4e94ef24":{
      "scriptId":"u3"},
    "36a9acc77a4d412995798145c0ab19d0":{
      "scriptId":"u4"},
    "4c31b1679da243a282776f13429d2377":{
      "scriptId":"u5"},
    "575dfeeaaf54489ebc242ff31a0830aa":{
      "scriptId":"u6"},
    "4fd937df0d514053a052ad453c79c869":{
      "scriptId":"u7"}}});