$axure.loadCurrentPage({
  "url":"买时间.html",
  "generationDate":new Date(1430066321861.85),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"677b6c3fe51c4eafa152bb433fae3701",
    "type":"Axure:Page",
    "name":"买时间",
    "notes":{
      "默认":"<p><span>1.商户列表按照从近到远排。</span></p><p><span>2.一条商户记录包含商户简要信息加最近一条发布的出售信息。点击这条记录进入商户交易页面。</span><span></span></p><p><span>3.购买的时间如果存在冲突，比如同一天购买了1家以上的健身门店服务，系统会进行二次确认。或者不允许同一天购买1家以上的健身门店服务。</span></p>"},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f59f9badcaf544a0ba28806d40260971",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b2a34b889f248868ad6dfae250747d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/u0.png"}},
{
          "id":"8cfc9fae93cf400885c6743bcc4699a5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":16,
              "y":37},
            "size":{
              "width":22,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cc1eb4869d24ab088bf15eca4e16c6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":16,
                  "y":37},
                "size":{
                  "width":22,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 左侧边栏",
                      "target":{
                        "targetType":"page",
                        "url":"左侧边栏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/左侧边栏/u2.png"}},
{
          "id":"8339921785fe49a3b42ae4ecae78cbea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":271,
              "y":26},
            "size":{
              "width":43,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db961ae72d4746a194f2739d62c8af60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":271,
                  "y":26},
                "size":{
                  "width":43,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 买卖时间 向下滑动 500 毫秒,<br>(Image) 向下滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["56fbef2882844e20b904f3be621a3419"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}},
{
                          "objectPath":["10be340493184075951498ecc6489432"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd3943f2c14445cf85a315d301e5f2c2",
          "label":"ButtonBigSecondary",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontSize":"18px",
            "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
            "opacity":"0.6",
            "location":{
              "x":190,
              "y":65},
            "size":{
              "width":130,
              "height":76},
            "visible":false,
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aafd4eca0fa3493aa9b3a54ac155a32a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"18px",
                "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
                "opacity":"0.6",
                "location":{
                  "x":190,
                  "y":65},
                "size":{
                  "width":130,
                  "height":76},
                "visible":false,
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/buttonbigsecondary_u6.png"}},
{
          "id":"56fbef2882844e20b904f3be621a3419",
          "label":"买卖时间",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":190,
              "y":65},
            "size":{
              "width":130,
              "height":76},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"a31eba5d0d6d4a5b97726ef93c9c5504",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"10be340493184075951498ecc6489432",
                  "label":"",
                  "parentDynamicPanel":"56fbef2882844e20b904f3be621a3419",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":130,
                      "height":76}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e6398637a19a4a1f9524c0f2e726b4c3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"56fbef2882844e20b904f3be621a3419",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":130,
                          "height":76}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/买时间/u9.png"}},
{
                  "id":"bb049c80fc6e4fd7aca12c51af597c5f",
                  "label":"",
                  "parentDynamicPanel":"56fbef2882844e20b904f3be621a3419",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0",
                    "location":{
                      "x":0,
                      "y":1},
                    "size":{
                      "width":130,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"693f9c2d03c448118de614fd922dc186",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"56fbef2882844e20b904f3be621a3419",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0",
                        "location":{
                          "x":0,
                          "y":1},
                        "size":{
                          "width":130,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 发起出售请求页",
                              "target":{
                                "targetType":"page",
                                "url":"发起出售请求页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5b1244377ce24acea6a502ecc23ee467",
                  "label":"",
                  "parentDynamicPanel":"56fbef2882844e20b904f3be621a3419",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0",
                    "location":{
                      "x":0,
                      "y":41},
                    "size":{
                      "width":130,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"69d6fe9825f147049f7b1ef5ccb157b0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"56fbef2882844e20b904f3be621a3419",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0",
                        "location":{
                          "x":0,
                          "y":41},
                        "size":{
                          "width":130,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 发起购买请求页",
                              "target":{
                                "targetType":"page",
                                "url":"发起购买请求页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"16f704bf74214a45a3bf32c267461f72",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":161,
              "y":74},
            "size":{
              "width":70,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a7dc657d79a4e7a9737c6096247215e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":161,
                  "y":74},
                "size":{
                  "width":70,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 卖时间",
                      "target":{
                        "targetType":"page",
                        "url":"卖时间.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f85651c4a63b4625af93a31c97e203b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":249,
              "y":202},
            "size":{
              "width":67,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7687fd47964f4d19a78753d9627767a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":249,
                  "y":202},
                "size":{
                  "width":67,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 购买请求确认页",
                      "target":{
                        "targetType":"page",
                        "url":"购买请求确认页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "f59f9badcaf544a0ba28806d40260971":{
      "scriptId":"u0"},
    "7b2a34b889f248868ad6dfae250747d2":{
      "scriptId":"u1"},
    "8cfc9fae93cf400885c6743bcc4699a5":{
      "scriptId":"u2"},
    "7cc1eb4869d24ab088bf15eca4e16c6c":{
      "scriptId":"u3"},
    "8339921785fe49a3b42ae4ecae78cbea":{
      "scriptId":"u4"},
    "db961ae72d4746a194f2739d62c8af60":{
      "scriptId":"u5"},
    "cd3943f2c14445cf85a315d301e5f2c2":{
      "scriptId":"u6"},
    "aafd4eca0fa3493aa9b3a54ac155a32a":{
      "scriptId":"u7"},
    "56fbef2882844e20b904f3be621a3419":{
      "scriptId":"u8"},
    "10be340493184075951498ecc6489432":{
      "scriptId":"u9"},
    "e6398637a19a4a1f9524c0f2e726b4c3":{
      "scriptId":"u10"},
    "bb049c80fc6e4fd7aca12c51af597c5f":{
      "scriptId":"u11"},
    "693f9c2d03c448118de614fd922dc186":{
      "scriptId":"u12"},
    "5b1244377ce24acea6a502ecc23ee467":{
      "scriptId":"u13"},
    "69d6fe9825f147049f7b1ef5ccb157b0":{
      "scriptId":"u14"},
    "16f704bf74214a45a3bf32c267461f72":{
      "scriptId":"u15"},
    "0a7dc657d79a4e7a9737c6096247215e":{
      "scriptId":"u16"},
    "f85651c4a63b4625af93a31c97e203b7":{
      "scriptId":"u17"},
    "7687fd47964f4d19a78753d9627767a9":{
      "scriptId":"u18"}}});