$axure.loadCurrentPage({
  "url":"买时间.html",
  "generationDate":new Date(1432237663917.44),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"677b6c3fe51c4eafa152bb433fae3701",
    "type":"Axure:Page",
    "name":"买时间",
    "notes":{
      "默认":"<p><span>1.商户列表按照从近到远排。</span></p><p><span>2.一条商户记录包含商户简要信息加最近一条发布的出售信息。点击这条记录进入商户交易页面。</span><span></span></p><p><span>3.购买的时间如果存在冲突，比如同一天购买了1家以上的健身门店服务，系统会进行二次确认。或者不允许同一天购买1家以上的健身门店服务。</span></p>"},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e6c1248a0e9d4c50907f34fa68f2aece",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2e8a932f2dc450ebab8523a89aa3700",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/u0.png"}},
{
          "id":"7cc5605286fe47bc9cd7a0f307dd7414",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":118,
              "y":4},
            "size":{
              "width":84,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e6e4e24a2ca43baae8df43f02802f02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":118,
                  "y":4},
                "size":{
                  "width":84,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13c8435573004ebe947de88dcbcdf1f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":6,
              "y":4},
            "size":{
              "width":44,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"952da029f9f7401a813cf085d40bd8d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":6,
                  "y":4},
                "size":{
                  "width":44,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 左侧边栏",
                      "target":{
                        "targetType":"page",
                        "url":"左侧边栏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f284f775dbcf41ddb4fb17999296151d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":44},
            "size":{
              "width":320,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"467adc874d1e4455953bd7389c5ed929",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":44},
                "size":{
                  "width":320,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/u6.png"}},
{
          "id":"4b347fbe9fdd49f1b3205f0f2ae3d6d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":87,
              "y":54},
            "size":{
              "width":70,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38a8a111bf4b4b6e9cf7420b7300b594",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":87,
                  "y":54},
                "size":{
                  "width":70,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"146e8848a3384c9087ead93e6c318256",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF4175B9,
              "opacity":1},
            "location":{
              "x":162,
              "y":54},
            "size":{
              "width":70,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db81a3e590e94f18994d0484ce72f9c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF4175B9,
                  "opacity":1},
                "location":{
                  "x":162,
                  "y":54},
                "size":{
                  "width":70,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 卖时间",
                      "target":{
                        "targetType":"page",
                        "url":"卖时间.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"52f07b61f9ea42a0be8454d95ff62a5d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":89},
            "size":{
              "width":320,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acf1db43b67343098ab9a033112ea0c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":89},
                "size":{
                  "width":320,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/u12.png"}},
{
          "id":"fe0eebcb665d4b8081d713bb0d6e0a12",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":177},
            "size":{
              "width":320,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11d8fdef87d641fe891ddec2ebae25f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":177},
                "size":{
                  "width":320,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/u14.png"}},
{
          "id":"ad79f1f7c1cf44e1adb7e9b844075ee9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":92,
              "y":90},
            "size":{
              "width":178,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a15f44121264487868f35b3f5b29257",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":92,
                  "y":90},
                "size":{
                  "width":178,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d0710503a994a59abbc10105c7e2050",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":92,
              "y":109},
            "size":{
              "width":188,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2961ebbab2e4945a7530c5206b5c04d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":92,
                  "y":109},
                "size":{
                  "width":188,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e6ac83f40ac403b801435d2c31b6804",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":92,
              "y":181},
            "size":{
              "width":178,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d2eef35b6694a119cf9ca3a61e631a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":92,
                  "y":181},
                "size":{
                  "width":178,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e4c31f0e3f8f48709c2ab64385ff011e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":92,
              "y":200},
            "size":{
              "width":188,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6582c2585444499db98fe23041e3534e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":92,
                  "y":200},
                "size":{
                  "width":188,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cbef8fe357b34eb58978041ead20fb4b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":265},
            "size":{
              "width":320,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38de7e503bd142d18b1606f46581319c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":265},
                "size":{
                  "width":320,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/u24.png"}},
{
          "id":"77bb09b959b843df8065d22b6d07ca20",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":357},
            "size":{
              "width":320,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac9cb8d412ee4b28903878f446b458c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":357},
                "size":{
                  "width":320,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/u26.png"}},
{
          "id":"64379c81ab684f4e83e8999942347f3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":25,
              "y":267},
            "size":{
              "width":178,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8421ece01c0642d49f993baf27d02e2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":25,
                  "y":267},
                "size":{
                  "width":178,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"60970e75a962482aa86081c24b20c39c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":25,
              "y":286},
            "size":{
              "width":185,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"192a60128ba04e38ace9cfeeb7923f8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":25,
                  "y":286},
                "size":{
                  "width":185,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5908204cbf5400aa9b4695421cceda5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":247,
              "y":266},
            "size":{
              "width":70,
              "height":88}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7685507ce6484dc7b8aa1d1befb47250",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":247,
                  "y":266},
                "size":{
                  "width":70,
                  "height":88}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 订单详情页",
                      "target":{
                        "targetType":"page",
                        "url":"订单详情页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81e4139d42494ebab48ec2ce41d62b79",
          "label":"ButtonBigSecondary",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontSize":"18px",
            "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
            "opacity":"0.6",
            "location":{
              "x":190,
              "y":44},
            "size":{
              "width":130,
              "height":76},
            "visible":false,
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bb573ce0568400fabffe98f9036c962",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"18px",
                "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
                "opacity":"0.6",
                "location":{
                  "x":190,
                  "y":44},
                "size":{
                  "width":130,
                  "height":76},
                "visible":false,
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/buttonbigsecondary_u34.png"}},
{
          "id":"881bc58850624b7e9ef79d02a878eaeb",
          "label":"买卖时间",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":190,
              "y":44},
            "size":{
              "width":130,
              "height":76},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"020b1cb8bf7d474287a03c00ce17d113",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"fdbae9ab2e4648448b4e77644fe98318",
                  "label":"",
                  "parentDynamicPanel":"881bc58850624b7e9ef79d02a878eaeb",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":130,
                      "height":76}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b29d74c6c46d46849c0ef7f78461ecd8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"881bc58850624b7e9ef79d02a878eaeb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":130,
                          "height":76}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/买时间/u37.png"}},
{
                  "id":"33d910f937a447c59e8d248f15ca5276",
                  "label":"",
                  "parentDynamicPanel":"881bc58850624b7e9ef79d02a878eaeb",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0",
                    "location":{
                      "x":0,
                      "y":1},
                    "size":{
                      "width":130,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b0adc5d50be244fa95bb1b391717c91b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"881bc58850624b7e9ef79d02a878eaeb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0",
                        "location":{
                          "x":0,
                          "y":1},
                        "size":{
                          "width":130,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 发起出售请求页",
                              "target":{
                                "targetType":"page",
                                "url":"发起出售请求页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a0b8dc6632874e93a98889f949113736",
                  "label":"",
                  "parentDynamicPanel":"881bc58850624b7e9ef79d02a878eaeb",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0",
                    "location":{
                      "x":0,
                      "y":41},
                    "size":{
                      "width":130,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b5b86db5e5f84c1398151c7c88bc8016",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"881bc58850624b7e9ef79d02a878eaeb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0",
                        "location":{
                          "x":0,
                          "y":41},
                        "size":{
                          "width":130,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 发起购买请求页",
                              "target":{
                                "targetType":"page",
                                "url":"发起购买请求页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"e0d28dd22c39446e899a710324fa0d48",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":25,
              "y":359},
            "size":{
              "width":178,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d31cefc9f7f34a8d8bce61d37f8a2c49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":25,
                  "y":359},
                "size":{
                  "width":178,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a802c29b6df447cb8a753e65871a9dde",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":25,
              "y":378},
            "size":{
              "width":185,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ca6446d5159429bbe46c99a51aea9fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":25,
                  "y":378},
                "size":{
                  "width":185,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"32f5b0cfe90f42328996dcaadf8a4387",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":247,
              "y":358},
            "size":{
              "width":70,
              "height":88}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2249a6c65edb4ba0bde4fc825fa5379e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":247,
                  "y":358},
                "size":{
                  "width":70,
                  "height":88}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 订单详情页",
                      "target":{
                        "targetType":"page",
                        "url":"订单详情页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb553d5961aa438aa21ea99319464416",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF6F5F6},
            "location":{
              "x":0,
              "y":445},
            "size":{
              "width":320,
              "height":86},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF6F5F6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e31b3862e0884f46abab8b1e1630b75d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF6F5F6},
                "location":{
                  "x":0,
                  "y":445},
                "size":{
                  "width":320,
                  "height":86},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF6F5F6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/u49.png"}},
{
          "id":"430f946c70084ce8bcb8fa728a84946d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":458},
            "size":{
              "width":65,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d49e04921e9f42049c24082ab9f06fa3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":458},
                "size":{
                  "width":65,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/u51.png"}},
{
          "id":"1bbe3732d5584e9db46ab87d3211f84e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":92,
              "y":446},
            "size":{
              "width":178,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f18255286144c739ac398c8ff0aab6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":92,
                  "y":446},
                "size":{
                  "width":178,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bdc5c2f416c74abbbea177aa07350c59",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":92,
              "y":465},
            "size":{
              "width":182,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"040094bbdf594ed59c955dff6584d42e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":92,
                  "y":465},
                "size":{
                  "width":182,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"651f9468adab4c9ab21af967ff18c032",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":284,
              "y":474},
            "size":{
              "width":26,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b75b64a226546fc8cc4a7af3908ebe0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":284,
                  "y":474},
                "size":{
                  "width":26,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/u57.png"}},
{
          "id":"eef97afb237b4664a6105b490800a8b9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":227},
            "size":{
              "width":24,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"baf15f8c68284db9b4100c88c99635c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":227},
                "size":{
                  "width":24,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/u59.png"}},
{
          "id":"8c82565eb5fe479081795d9e16eebbd0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":139},
            "size":{
              "width":24,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3925ed829d1d4b50893e05f0887e1a3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":139},
                "size":{
                  "width":24,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/u59.png"}},
{
          "id":"4deec8d9b7b34e64b15bc9ffe9f872ac",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":496},
            "size":{
              "width":24,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d170bba5b7e545899160cc9c2215a18b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":496},
                "size":{
                  "width":24,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/u59.png"}},
{
          "id":"f1d5ec047b3b439f8ea82800141f808d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":272,
              "y":5},
            "size":{
              "width":43,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b85a8b0faf2f4f3181c7538c1e644caa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":272,
                  "y":5},
                "size":{
                  "width":43,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (Image) 向下滑动 500 毫秒,<br>买卖时间 向下滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["fdbae9ab2e4648448b4e77644fe98318"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}},
{
                          "objectPath":["881bc58850624b7e9ef79d02a878eaeb"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e6c1248a0e9d4c50907f34fa68f2aece":{
      "scriptId":"u0"},
    "d2e8a932f2dc450ebab8523a89aa3700":{
      "scriptId":"u1"},
    "7cc5605286fe47bc9cd7a0f307dd7414":{
      "scriptId":"u2"},
    "3e6e4e24a2ca43baae8df43f02802f02":{
      "scriptId":"u3"},
    "13c8435573004ebe947de88dcbcdf1f8":{
      "scriptId":"u4"},
    "952da029f9f7401a813cf085d40bd8d0":{
      "scriptId":"u5"},
    "f284f775dbcf41ddb4fb17999296151d":{
      "scriptId":"u6"},
    "467adc874d1e4455953bd7389c5ed929":{
      "scriptId":"u7"},
    "4b347fbe9fdd49f1b3205f0f2ae3d6d7":{
      "scriptId":"u8"},
    "38a8a111bf4b4b6e9cf7420b7300b594":{
      "scriptId":"u9"},
    "146e8848a3384c9087ead93e6c318256":{
      "scriptId":"u10"},
    "db81a3e590e94f18994d0484ce72f9c9":{
      "scriptId":"u11"},
    "52f07b61f9ea42a0be8454d95ff62a5d":{
      "scriptId":"u12"},
    "acf1db43b67343098ab9a033112ea0c4":{
      "scriptId":"u13"},
    "fe0eebcb665d4b8081d713bb0d6e0a12":{
      "scriptId":"u14"},
    "11d8fdef87d641fe891ddec2ebae25f1":{
      "scriptId":"u15"},
    "ad79f1f7c1cf44e1adb7e9b844075ee9":{
      "scriptId":"u16"},
    "9a15f44121264487868f35b3f5b29257":{
      "scriptId":"u17"},
    "8d0710503a994a59abbc10105c7e2050":{
      "scriptId":"u18"},
    "e2961ebbab2e4945a7530c5206b5c04d":{
      "scriptId":"u19"},
    "2e6ac83f40ac403b801435d2c31b6804":{
      "scriptId":"u20"},
    "6d2eef35b6694a119cf9ca3a61e631a5":{
      "scriptId":"u21"},
    "e4c31f0e3f8f48709c2ab64385ff011e":{
      "scriptId":"u22"},
    "6582c2585444499db98fe23041e3534e":{
      "scriptId":"u23"},
    "cbef8fe357b34eb58978041ead20fb4b":{
      "scriptId":"u24"},
    "38de7e503bd142d18b1606f46581319c":{
      "scriptId":"u25"},
    "77bb09b959b843df8065d22b6d07ca20":{
      "scriptId":"u26"},
    "ac9cb8d412ee4b28903878f446b458c0":{
      "scriptId":"u27"},
    "64379c81ab684f4e83e8999942347f3d":{
      "scriptId":"u28"},
    "8421ece01c0642d49f993baf27d02e2a":{
      "scriptId":"u29"},
    "60970e75a962482aa86081c24b20c39c":{
      "scriptId":"u30"},
    "192a60128ba04e38ace9cfeeb7923f8f":{
      "scriptId":"u31"},
    "e5908204cbf5400aa9b4695421cceda5":{
      "scriptId":"u32"},
    "7685507ce6484dc7b8aa1d1befb47250":{
      "scriptId":"u33"},
    "81e4139d42494ebab48ec2ce41d62b79":{
      "scriptId":"u34"},
    "7bb573ce0568400fabffe98f9036c962":{
      "scriptId":"u35"},
    "881bc58850624b7e9ef79d02a878eaeb":{
      "scriptId":"u36"},
    "fdbae9ab2e4648448b4e77644fe98318":{
      "scriptId":"u37"},
    "b29d74c6c46d46849c0ef7f78461ecd8":{
      "scriptId":"u38"},
    "33d910f937a447c59e8d248f15ca5276":{
      "scriptId":"u39"},
    "b0adc5d50be244fa95bb1b391717c91b":{
      "scriptId":"u40"},
    "a0b8dc6632874e93a98889f949113736":{
      "scriptId":"u41"},
    "b5b86db5e5f84c1398151c7c88bc8016":{
      "scriptId":"u42"},
    "e0d28dd22c39446e899a710324fa0d48":{
      "scriptId":"u43"},
    "d31cefc9f7f34a8d8bce61d37f8a2c49":{
      "scriptId":"u44"},
    "a802c29b6df447cb8a753e65871a9dde":{
      "scriptId":"u45"},
    "1ca6446d5159429bbe46c99a51aea9fb":{
      "scriptId":"u46"},
    "32f5b0cfe90f42328996dcaadf8a4387":{
      "scriptId":"u47"},
    "2249a6c65edb4ba0bde4fc825fa5379e":{
      "scriptId":"u48"},
    "eb553d5961aa438aa21ea99319464416":{
      "scriptId":"u49"},
    "e31b3862e0884f46abab8b1e1630b75d":{
      "scriptId":"u50"},
    "430f946c70084ce8bcb8fa728a84946d":{
      "scriptId":"u51"},
    "d49e04921e9f42049c24082ab9f06fa3":{
      "scriptId":"u52"},
    "1bbe3732d5584e9db46ab87d3211f84e":{
      "scriptId":"u53"},
    "6f18255286144c739ac398c8ff0aab6e":{
      "scriptId":"u54"},
    "bdc5c2f416c74abbbea177aa07350c59":{
      "scriptId":"u55"},
    "040094bbdf594ed59c955dff6584d42e":{
      "scriptId":"u56"},
    "651f9468adab4c9ab21af967ff18c032":{
      "scriptId":"u57"},
    "6b75b64a226546fc8cc4a7af3908ebe0":{
      "scriptId":"u58"},
    "eef97afb237b4664a6105b490800a8b9":{
      "scriptId":"u59"},
    "baf15f8c68284db9b4100c88c99635c0":{
      "scriptId":"u60"},
    "8c82565eb5fe479081795d9e16eebbd0":{
      "scriptId":"u61"},
    "3925ed829d1d4b50893e05f0887e1a3a":{
      "scriptId":"u62"},
    "4deec8d9b7b34e64b15bc9ffe9f872ac":{
      "scriptId":"u63"},
    "d170bba5b7e545899160cc9c2215a18b":{
      "scriptId":"u64"},
    "f1d5ec047b3b439f8ea82800141f808d":{
      "scriptId":"u65"},
    "b85a8b0faf2f4f3181c7538c1e644caa":{
      "scriptId":"u66"}}});