$axure.loadCurrentPage({
  "url":"注册页面.html",
  "generationDate":new Date(1430762528139.53),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"44ba86cd529f40c7ac8032df785b18b9",
    "type":"Axure:Page",
    "name":"注册页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"091498a5026b4af49719e451356e3bc4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":548}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa62fe4c0d974a129cc30952c3ca945f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":548}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页面/u0.png"}},
{
          "id":"6dccf23bef0d482fbaf9a95e8ea5867f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "opacity":"0",
            "location":{
              "x":8,
              "y":31},
            "size":{
              "width":72,
              "height":39},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02f93300fc384ec19a13ac90d07c2747",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "opacity":"0",
                "location":{
                  "x":8,
                  "y":31},
                "size":{
                  "width":72,
                  "height":39},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 启动页",
                      "target":{
                        "targetType":"page",
                        "url":"启动页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9dc50f5b2cf74a00b927caeec23a2ee4",
          "label":"注册页短信验证",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":90},
            "size":{
              "width":266,
              "height":139}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"02716822ab3a4bafa331b4f6461e8e64",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1458e550ea564fbf88480540d58a260e",
                  "label":"",
                  "parentDynamicPanel":"9dc50f5b2cf74a00b927caeec23a2ee4",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":266,
                      "height":139}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8d1d422d684e412e9e2d46eb5234c52b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9dc50f5b2cf74a00b927caeec23a2ee4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":266,
                          "height":139}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 验证码",
                              "target":{
                                "targetType":"page",
                                "url":"验证码.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/注册页面/u5.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "091498a5026b4af49719e451356e3bc4":{
      "scriptId":"u0"},
    "fa62fe4c0d974a129cc30952c3ca945f":{
      "scriptId":"u1"},
    "6dccf23bef0d482fbaf9a95e8ea5867f":{
      "scriptId":"u2"},
    "02f93300fc384ec19a13ac90d07c2747":{
      "scriptId":"u3"},
    "9dc50f5b2cf74a00b927caeec23a2ee4":{
      "scriptId":"u4"},
    "1458e550ea564fbf88480540d58a260e":{
      "scriptId":"u5"},
    "8d1d422d684e412e9e2d46eb5234c52b":{
      "scriptId":"u6"}}});