$axure.loadCurrentPage({
  "url":"持卡人评价我_1.html",
  "generationDate":new Date(1429794607203.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a656e4642f7c4f569a009d8313a0cdfc",
    "type":"Axure:Page",
    "name":"持卡人评价我",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"90812b92474f4da8aac1fd47e7eeeb1f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":215}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb26d8b5a634487f91b3f04d8af7246f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":215}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的劲态（健身卡）/u0.png"}},
{
          "id":"8760fb30a1024a93a2216e54cecb79dc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":258},
            "size":{
              "width":320,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bdf282a1987485ea774cef5c5785597",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":258},
                "size":{
                  "width":320,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的劲态（二维码）/u2.png"}},
{
          "id":"a18b17ae54154ea7838354aacf6ac56c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":325},
            "size":{
              "width":320,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f982491d14b244de91d4a7cd421e5c9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":325},
                "size":{
                  "width":320,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的劲态（二维码）/u2.png"}},
{
          "id":"53da1b04f6314bb690d360b4bc529946",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":479},
            "size":{
              "width":320,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"151c044562504e2fb5de6d8b72134e84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":479},
                "size":{
                  "width":320,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的劲态（二维码）/u6.png"}},
{
          "id":"9ac509cbcf184b63906f58b6181f6c49",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":402},
            "size":{
              "width":320,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa5da18d46144b1b8942059459365722",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":402},
                "size":{
                  "width":320,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的劲态（二维码）/u6.png"}},
{
          "id":"095b3e8f9ce44697846902d87c17eea1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":556},
            "size":{
              "width":62,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ce124f384fb4fcd8ae93b9156423404",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":556},
                "size":{
                  "width":62,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的评价",
                      "target":{
                        "targetType":"page",
                        "url":"我的评价.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的劲态（二维码）/u10.png"}},
{
          "id":"804f8e458ffe4223a6978e622e0bc1da",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":556},
            "size":{
              "width":62,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8add915c87c49ffb29686996c109916",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":83,
                  "y":556},
                "size":{
                  "width":62,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的交易",
                      "target":{
                        "targetType":"page",
                        "url":"我的交易.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的劲态（二维码）/u12.png"}},
{
          "id":"0d0ae259901d41dc9daaf0126ab93e0b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":173,
              "y":556},
            "size":{
              "width":62,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b31d8e22e9643da9071eb78e617c461",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":173,
                  "y":556},
                "size":{
                  "width":62,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我关注的商户",
                      "target":{
                        "targetType":"page",
                        "url":"我关注的商户.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的劲态（二维码）/u14.png"}},
{
          "id":"b911cffdbb8548b0bb2b2c6bf820c10c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":258,
              "y":556},
            "size":{
              "width":62,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67f970add4ce47988cbbbe75b907f05c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":258,
                  "y":556},
                "size":{
                  "width":62,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的消息",
                      "target":{
                        "targetType":"page",
                        "url":"我的消息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的劲态（二维码）/u16.png"}},
{
          "id":"635f6bd2bbf54ad68f7869fcd152a9d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":215},
            "size":{
              "width":320,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d32e0c84cda41549188d81a5d76e0f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":215},
                "size":{
                  "width":320,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的劲态（二维码）/u20.png"}},
{
          "id":"94b6d4b0f3eb4d71ad2620f61352eb73",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":40,
              "y":222.5},
            "size":{
              "width":120,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8c32a96e7aa4a799e67f7f8d1fe9769",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":40,
                  "y":222.5},
                "size":{
                  "width":120,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 持卡人评价我",
                      "target":{
                        "targetType":"page",
                        "url":"持卡人评价我_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7dc30f33d41344ae9e14140f6bb81c49",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":15},
            "size":{
              "width":22,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51fca428903d4b9cb02a8bfa12c37654",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":15},
                "size":{
                  "width":22,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 左侧边栏",
                      "target":{
                        "targetType":"page",
                        "url":"左侧边栏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/左侧边栏/u2.png"}},
{
          "id":"23bb58d728a24789aad32c10c66307ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":277,
              "y":4},
            "size":{
              "width":43,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3653db915ba040ca99535ce5935b3e58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":277,
                  "y":4},
                "size":{
                  "width":43,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的健身数据",
                      "target":{
                        "targetType":"page",
                        "url":"我的健身数据.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "90812b92474f4da8aac1fd47e7eeeb1f":{
      "scriptId":"u0"},
    "bb26d8b5a634487f91b3f04d8af7246f":{
      "scriptId":"u1"},
    "8760fb30a1024a93a2216e54cecb79dc":{
      "scriptId":"u2"},
    "4bdf282a1987485ea774cef5c5785597":{
      "scriptId":"u3"},
    "a18b17ae54154ea7838354aacf6ac56c":{
      "scriptId":"u4"},
    "f982491d14b244de91d4a7cd421e5c9b":{
      "scriptId":"u5"},
    "53da1b04f6314bb690d360b4bc529946":{
      "scriptId":"u6"},
    "151c044562504e2fb5de6d8b72134e84":{
      "scriptId":"u7"},
    "9ac509cbcf184b63906f58b6181f6c49":{
      "scriptId":"u8"},
    "fa5da18d46144b1b8942059459365722":{
      "scriptId":"u9"},
    "095b3e8f9ce44697846902d87c17eea1":{
      "scriptId":"u10"},
    "0ce124f384fb4fcd8ae93b9156423404":{
      "scriptId":"u11"},
    "804f8e458ffe4223a6978e622e0bc1da":{
      "scriptId":"u12"},
    "d8add915c87c49ffb29686996c109916":{
      "scriptId":"u13"},
    "0d0ae259901d41dc9daaf0126ab93e0b":{
      "scriptId":"u14"},
    "9b31d8e22e9643da9071eb78e617c461":{
      "scriptId":"u15"},
    "b911cffdbb8548b0bb2b2c6bf820c10c":{
      "scriptId":"u16"},
    "67f970add4ce47988cbbbe75b907f05c":{
      "scriptId":"u17"},
    "635f6bd2bbf54ad68f7869fcd152a9d4":{
      "scriptId":"u18"},
    "8d32e0c84cda41549188d81a5d76e0f6":{
      "scriptId":"u19"},
    "94b6d4b0f3eb4d71ad2620f61352eb73":{
      "scriptId":"u20"},
    "f8c32a96e7aa4a799e67f7f8d1fe9769":{
      "scriptId":"u21"},
    "7dc30f33d41344ae9e14140f6bb81c49":{
      "scriptId":"u22"},
    "51fca428903d4b9cb02a8bfa12c37654":{
      "scriptId":"u23"},
    "23bb58d728a24789aad32c10c66307ac":{
      "scriptId":"u24"},
    "3653db915ba040ca99535ce5935b3e58":{
      "scriptId":"u25"}}});