$axure.loadCurrentPage({
  "url":"我的劲态（健身卡）.html",
  "generationDate":new Date(1429794607142.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5f94413608f64413a70807e7516be86c",
    "type":"Axure:Page",
    "name":"我的劲态（健身卡）",
    "notes":{
      "默认":"<p><span>1.会员卡信息只对持卡人可见。持卡人可以看到卡下面的交易信息，不同的卡不同的交易信息。</span></p><p><span>2.非持卡人只能看到交易记录。</span></p><p><span>3.添加会员卡</span><span>入口</span><span>：一是通过会员手机号码自动关联填充，二是用户手动添加</span><span>相关字段</span><span>。</span></p><p><span>&nbsp;</span></p>"},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"371a35e615ef4ec094b2bafeacbf610f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":215}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b345b20cad7b4637a7dca58e01889848",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":215}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的劲态（健身卡）/u0.png"}},
{
          "id":"e9b1cfa3447f4565a45117f47aa7d2d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":258},
            "size":{
              "width":320,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0cdfb86a733461d8d821eb356488324",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":258},
                "size":{
                  "width":320,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的劲态（二维码）/u2.png"}},
{
          "id":"e1f4388597f14415af48f6bb4bb38c11",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":325},
            "size":{
              "width":320,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4ad95890c654b30b13433549b78ab3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":325},
                "size":{
                  "width":320,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的劲态（二维码）/u2.png"}},
{
          "id":"43aeb0efeb2e40d79652b55a3708f82d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":479},
            "size":{
              "width":320,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73a3f5bf1ebd41c8b1f10ab6b570929d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":479},
                "size":{
                  "width":320,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的劲态（二维码）/u6.png"}},
{
          "id":"7d3adf1c0815455ab11fc254e66840cc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":402},
            "size":{
              "width":320,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a1288d466664f8585a2df55e6a04a39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":402},
                "size":{
                  "width":320,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的劲态（二维码）/u6.png"}},
{
          "id":"ef2aee4ed49a42b0af5f27898964f886",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":556},
            "size":{
              "width":62,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af0ee06377004f24b835ea0f11919719",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":556},
                "size":{
                  "width":62,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的评价",
                      "target":{
                        "targetType":"page",
                        "url":"我的评价.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的劲态（二维码）/u10.png"}},
{
          "id":"b35f1f136c5146b59b2e35ea99376147",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":556},
            "size":{
              "width":62,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24e21841a07340138e85b1024a319af0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":83,
                  "y":556},
                "size":{
                  "width":62,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的交易",
                      "target":{
                        "targetType":"page",
                        "url":"我的交易.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的劲态（二维码）/u12.png"}},
{
          "id":"874f0b8f6883425084374c9ff0abae72",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":173,
              "y":556},
            "size":{
              "width":62,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51be078df2dd4165854e0924cd67ee14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":173,
                  "y":556},
                "size":{
                  "width":62,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我关注的商户",
                      "target":{
                        "targetType":"page",
                        "url":"我关注的商户.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的劲态（二维码）/u14.png"}},
{
          "id":"5ea330c655bc46f4a4b759e536db2601",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":258,
              "y":556},
            "size":{
              "width":62,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cd095bf13ca4d5f94740e628ff87b1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":258,
                  "y":556},
                "size":{
                  "width":62,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的消息",
                      "target":{
                        "targetType":"page",
                        "url":"我的消息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的劲态（二维码）/u16.png"}},
{
          "id":"e25dee1134ce4ead9bfe333373fea2db",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":215},
            "size":{
              "width":320,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"099ca1acef1d470a854589e125cbd09a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":215},
                "size":{
                  "width":320,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的劲态（二维码）/u20.png"}},
{
          "id":"78dab361cbcf4b9a8fb8b5e789b5b178",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":162,
              "y":223},
            "size":{
              "width":120,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98cc309c0d1c47d3b1590b70f3c424e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":162,
                  "y":223},
                "size":{
                  "width":120,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 持卡人评价我",
                      "target":{
                        "targetType":"page",
                        "url":"持卡人评价我_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11d6bd8d7e6b467499b978a9c8aff784",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":15},
            "size":{
              "width":22,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88def7cf5a764d808e63bad050932ffd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":15},
                "size":{
                  "width":22,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 左侧边栏",
                      "target":{
                        "targetType":"page",
                        "url":"左侧边栏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/左侧边栏/u2.png"}},
{
          "id":"37943a9eb9cd4d82a1aaa9add5875b8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":277,
              "y":4},
            "size":{
              "width":43,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92b01f0b5c044342a33d8b40cdcb8193",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":277,
                  "y":4},
                "size":{
                  "width":43,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的健身数据",
                      "target":{
                        "targetType":"page",
                        "url":"我的健身数据.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "371a35e615ef4ec094b2bafeacbf610f":{
      "scriptId":"u0"},
    "b345b20cad7b4637a7dca58e01889848":{
      "scriptId":"u1"},
    "e9b1cfa3447f4565a45117f47aa7d2d4":{
      "scriptId":"u2"},
    "f0cdfb86a733461d8d821eb356488324":{
      "scriptId":"u3"},
    "e1f4388597f14415af48f6bb4bb38c11":{
      "scriptId":"u4"},
    "d4ad95890c654b30b13433549b78ab3b":{
      "scriptId":"u5"},
    "43aeb0efeb2e40d79652b55a3708f82d":{
      "scriptId":"u6"},
    "73a3f5bf1ebd41c8b1f10ab6b570929d":{
      "scriptId":"u7"},
    "7d3adf1c0815455ab11fc254e66840cc":{
      "scriptId":"u8"},
    "3a1288d466664f8585a2df55e6a04a39":{
      "scriptId":"u9"},
    "ef2aee4ed49a42b0af5f27898964f886":{
      "scriptId":"u10"},
    "af0ee06377004f24b835ea0f11919719":{
      "scriptId":"u11"},
    "b35f1f136c5146b59b2e35ea99376147":{
      "scriptId":"u12"},
    "24e21841a07340138e85b1024a319af0":{
      "scriptId":"u13"},
    "874f0b8f6883425084374c9ff0abae72":{
      "scriptId":"u14"},
    "51be078df2dd4165854e0924cd67ee14":{
      "scriptId":"u15"},
    "5ea330c655bc46f4a4b759e536db2601":{
      "scriptId":"u16"},
    "5cd095bf13ca4d5f94740e628ff87b1b":{
      "scriptId":"u17"},
    "e25dee1134ce4ead9bfe333373fea2db":{
      "scriptId":"u18"},
    "099ca1acef1d470a854589e125cbd09a":{
      "scriptId":"u19"},
    "78dab361cbcf4b9a8fb8b5e789b5b178":{
      "scriptId":"u20"},
    "98cc309c0d1c47d3b1590b70f3c424e7":{
      "scriptId":"u21"},
    "11d6bd8d7e6b467499b978a9c8aff784":{
      "scriptId":"u22"},
    "88def7cf5a764d808e63bad050932ffd":{
      "scriptId":"u23"},
    "37943a9eb9cd4d82a1aaa9add5875b8f":{
      "scriptId":"u24"},
    "92b01f0b5c044342a33d8b40cdcb8193":{
      "scriptId":"u25"}}});