$axure.loadCurrentPage({
  "url":"发起出售请求页.html",
  "generationDate":new Date(1430066322230.87),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"08f0b752a943406190b8ea061be095b4",
    "type":"Axure:Page",
    "name":"发起出售请求页",
    "notes":{
      "默认":"<p><span>求购信息列表【回应】，发起出售请求的模板。持卡人信息校验正确，并且可售时间满足求购信息需求之后，系统自动向买方发送站内信通知以及短信通知。（后台匹配出错有相应提示。）</span></p>"},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"42222037a059419eadd22cd8d628ac7b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d434539902c4a87b9dc50b2d4896e5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起购买请求页/u0.png"}},
{
          "id":"3f6812e7cc864eb0828066abb6ae1eed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "size":{
              "width":110,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83ddc973f20c4e18891a0f7cc1d00d7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "size":{
                  "width":110,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 卖时间",
                      "target":{
                        "targetType":"page",
                        "url":"卖时间.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2626f5a7e9ee4dce827165e2ad0e36b8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":104,
              "y":0},
            "size":{
              "width":216,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3587f083a39347b09ccfc7df0a179436",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":104,
                  "y":0},
                "size":{
                  "width":216,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起出售请求页/u4.png"}},
{
          "id":"73a2567704f644c0ae8e14e92c7ab406",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":110,
              "y":244},
            "size":{
              "width":200,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"722fdb9597ba40f6beaa84440f89723d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":110,
                  "y":244},
                "size":{
                  "width":200,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 买时间选择日期 向上滑动 500 毫秒,<br>(Image) 向上滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["c398efbd4ca447a4b2419f2af59b4b51"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideUp",
                              "duration":500,
                              "showType":"none"}}},
{
                          "objectPath":["cc5c4d3bd99e441a908a1b4833f959db"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideUp",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c398efbd4ca447a4b2419f2af59b4b51",
          "label":"买时间选择日期",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":0,
              "y":352},
            "size":{
              "width":320,
              "height":216},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"e034164bc6ac4d8fbd0f7e191e1e354a",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"cc5c4d3bd99e441a908a1b4833f959db",
                  "label":"",
                  "parentDynamicPanel":"c398efbd4ca447a4b2419f2af59b4b51",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":216}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2ba1594612e34444bd37f972d7312317",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c398efbd4ca447a4b2419f2af59b4b51",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":216}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 出售请求确认页",
                              "target":{
                                "targetType":"page",
                                "url":"出售请求确认页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/发起购买请求页/u5.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "42222037a059419eadd22cd8d628ac7b":{
      "scriptId":"u0"},
    "9d434539902c4a87b9dc50b2d4896e5f":{
      "scriptId":"u1"},
    "3f6812e7cc864eb0828066abb6ae1eed":{
      "scriptId":"u2"},
    "83ddc973f20c4e18891a0f7cc1d00d7d":{
      "scriptId":"u3"},
    "2626f5a7e9ee4dce827165e2ad0e36b8":{
      "scriptId":"u4"},
    "3587f083a39347b09ccfc7df0a179436":{
      "scriptId":"u5"},
    "73a2567704f644c0ae8e14e92c7ab406":{
      "scriptId":"u6"},
    "722fdb9597ba40f6beaa84440f89723d":{
      "scriptId":"u7"},
    "c398efbd4ca447a4b2419f2af59b4b51":{
      "scriptId":"u8"},
    "cc5c4d3bd99e441a908a1b4833f959db":{
      "scriptId":"u9"},
    "2ba1594612e34444bd37f972d7312317":{
      "scriptId":"u10"}}});