$axure.loadCurrentPage({
  "url":"设置.html",
  "generationDate":new Date(1432847391467.43),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f5eda4fff40d4bc98045c9518aafebd8",
    "type":"Axure:Page",
    "name":"设置",
    "notes":{
      "默认":"<p><span>1.用户在查看自己发布的出售信息时， 信息旁边的【购买】按钮显示为【下架】。</span></p><p><span>2.过期的信息置灰不可操作，并不隐藏，加上【已过期】标示。</span></p>"},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1b2c16f56ef54bbb97d04dd9800a8f7e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":542}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6aabd5f99ccb4e90a4ea2564b35f56e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":542}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u0.png"}},
{
          "id":"b948485b09a44bb28febe5c025a89847",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":490},
            "size":{
              "width":292,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d2867e0586d43998bd562c3e7065cf2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":490},
                "size":{
                  "width":292,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u2.png"}},
{
          "id":"a62e5f7f49b84a62b09778fcddb76b8d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":44},
            "size":{
              "width":320,
              "height":276}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c403b21453304526827fcc9bbb92fbf3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":44},
                "size":{
                  "width":320,
                  "height":276}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u4.png"}},
{
          "id":"4725dc6fcdb346c88ad537904137e743",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a830cbd2bc9b4dbb94d72258348c9b30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u6.png"}},
{
          "id":"1ebbdadb16c24575ac273973c4d98dda",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":30,
              "y":493},
            "size":{
              "width":270,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96ed476f280140a18013ec57d9431594",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":30,
                  "y":493},
                "size":{
                  "width":270,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录页面",
                      "target":{
                        "targetType":"page",
                        "url":"登录页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7f6114e0b5449fd881e88a6f4d7bc24",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":5,
              "y":3},
            "size":{
              "width":44,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4de86b0e6bc496e934a0ce82dbb569f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":5,
                  "y":3},
                "size":{
                  "width":44,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 左侧边栏",
                      "target":{
                        "targetType":"page",
                        "url":"左侧边栏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8c3a3a1c70645878f0ebcd1752b7f7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":5,
              "y":292},
            "size":{
              "width":265,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae31174efd8a4cdc93fb3ef51e035ae7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":5,
                  "y":292},
                "size":{
                  "width":265,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 帮助",
                      "target":{
                        "targetType":"page",
                        "url":"帮助.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"430029f4d62942389be55575e2e7fb17",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":5,
              "y":254},
            "size":{
              "width":265,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0b8a03923c845429c2dca28b78f6643",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":5,
                  "y":254},
                "size":{
                  "width":265,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 关于劲态",
                      "target":{
                        "targetType":"page",
                        "url":"关于劲态.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6ccaa490f7747e9bc93455a17cb20e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":5,
              "y":214},
            "size":{
              "width":265,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ca3c8bc50f142a59238b9ca9c3e3cea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":5,
                  "y":214},
                "size":{
                  "width":265,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 版本更新",
                      "target":{
                        "targetType":"page",
                        "url":"版本更新.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71df2554028d4a7e89d3c150fabd2b35",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":5,
              "y":175},
            "size":{
              "width":265,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"531ce656c3b74d9d8371665d55d80205",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":5,
                  "y":175},
                "size":{
                  "width":265,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 意见反馈",
                      "target":{
                        "targetType":"page",
                        "url":"意见反馈.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f3319188d7547999e0e187d1c5247fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":5,
              "y":133},
            "size":{
              "width":265,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92971eeeebb24eafb4f9dbaa06a19fc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":5,
                  "y":133},
                "size":{
                  "width":265,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 推送通知开关提醒",
                      "target":{
                        "targetType":"page",
                        "url":"推送通知开关提醒.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"52726683426044d19c5b15da6543a3c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":5,
              "y":94},
            "size":{
              "width":265,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bb62bdcbdcd4a4fb5fe0504b79fd642",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":5,
                  "y":94},
                "size":{
                  "width":265,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 推送通知开关提醒",
                      "target":{
                        "targetType":"page",
                        "url":"推送通知开关提醒.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70b44c21c4f94e3e9748de9f6504a503",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":5,
              "y":54},
            "size":{
              "width":225,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a963bab1a2043b1b8a7d7dfe3016f31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":5,
                  "y":54},
                "size":{
                  "width":225,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"819521a1108f4578b633778ea82ca642",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"10px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":234,
              "y":48},
            "size":{
              "width":85,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db6b85b4650f45759b95babbb351fe04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"10px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":234,
                  "y":48},
                "size":{
                  "width":85,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34b3da85c3394d87942540ce1b33d5cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"10px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":240,
              "y":208},
            "size":{
              "width":75,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de3bd340d5ee40138083a35f429594a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"10px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":240,
                  "y":208},
                "size":{
                  "width":75,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53ffe4ea11c641afbba51a65a85592c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":121,
              "y":4},
            "size":{
              "width":73,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef422986a2c64711ba82a3db30313f3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":121,
                  "y":4},
                "size":{
                  "width":73,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1b2c16f56ef54bbb97d04dd9800a8f7e":{
      "scriptId":"u0"},
    "6aabd5f99ccb4e90a4ea2564b35f56e5":{
      "scriptId":"u1"},
    "b948485b09a44bb28febe5c025a89847":{
      "scriptId":"u2"},
    "1d2867e0586d43998bd562c3e7065cf2":{
      "scriptId":"u3"},
    "a62e5f7f49b84a62b09778fcddb76b8d":{
      "scriptId":"u4"},
    "c403b21453304526827fcc9bbb92fbf3":{
      "scriptId":"u5"},
    "4725dc6fcdb346c88ad537904137e743":{
      "scriptId":"u6"},
    "a830cbd2bc9b4dbb94d72258348c9b30":{
      "scriptId":"u7"},
    "1ebbdadb16c24575ac273973c4d98dda":{
      "scriptId":"u8"},
    "96ed476f280140a18013ec57d9431594":{
      "scriptId":"u9"},
    "f7f6114e0b5449fd881e88a6f4d7bc24":{
      "scriptId":"u10"},
    "f4de86b0e6bc496e934a0ce82dbb569f":{
      "scriptId":"u11"},
    "e8c3a3a1c70645878f0ebcd1752b7f7f":{
      "scriptId":"u12"},
    "ae31174efd8a4cdc93fb3ef51e035ae7":{
      "scriptId":"u13"},
    "430029f4d62942389be55575e2e7fb17":{
      "scriptId":"u14"},
    "f0b8a03923c845429c2dca28b78f6643":{
      "scriptId":"u15"},
    "c6ccaa490f7747e9bc93455a17cb20e8":{
      "scriptId":"u16"},
    "1ca3c8bc50f142a59238b9ca9c3e3cea":{
      "scriptId":"u17"},
    "71df2554028d4a7e89d3c150fabd2b35":{
      "scriptId":"u18"},
    "531ce656c3b74d9d8371665d55d80205":{
      "scriptId":"u19"},
    "5f3319188d7547999e0e187d1c5247fd":{
      "scriptId":"u20"},
    "92971eeeebb24eafb4f9dbaa06a19fc2":{
      "scriptId":"u21"},
    "52726683426044d19c5b15da6543a3c3":{
      "scriptId":"u22"},
    "8bb62bdcbdcd4a4fb5fe0504b79fd642":{
      "scriptId":"u23"},
    "70b44c21c4f94e3e9748de9f6504a503":{
      "scriptId":"u24"},
    "7a963bab1a2043b1b8a7d7dfe3016f31":{
      "scriptId":"u25"},
    "819521a1108f4578b633778ea82ca642":{
      "scriptId":"u26"},
    "db6b85b4650f45759b95babbb351fe04":{
      "scriptId":"u27"},
    "34b3da85c3394d87942540ce1b33d5cd":{
      "scriptId":"u28"},
    "de3bd340d5ee40138083a35f429594a6":{
      "scriptId":"u29"},
    "53ffe4ea11c641afbba51a65a85592c3":{
      "scriptId":"u30"},
    "ef422986a2c64711ba82a3db30313f3c":{
      "scriptId":"u31"}}});