$axure.loadCurrentPage({
  "url":"设置.html",
  "generationDate":new Date(1430066324171.98),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f5eda4fff40d4bc98045c9518aafebd8",
    "type":"Axure:Page",
    "name":"设置",
    "notes":{
      "默认":"<p><span>1.用户在查看自己发布的出售信息时， 信息旁边的【购买】按钮显示为【下架】。</span></p><p><span>2.过期的信息置灰不可操作，并不隐藏，加上【已过期】标示。</span></p>"},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"57a52d1f5f444fe49ed3c26ab8c94bb5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":542}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"638c011a745e4079ac45ac5987c8a2ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":542}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u0.png"}},
{
          "id":"419437f49b93411dbafab01a7fd17e51",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"411c6660087d4c92aa9f4f00ae70566c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u2.png"}},
{
          "id":"5a9fd7fe71ed498683de60daa4ba7d62",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":44},
            "size":{
              "width":320,
              "height":270}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"424e54e92f2743adaeb7dd555ab3b6df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":44},
                "size":{
                  "width":320,
                  "height":270}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u4.png"}},
{
          "id":"a8d07aca2e024cf7aedcf5cf51c6983d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":490},
            "size":{
              "width":292,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"add13de25423425380374cfd042ec4b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":490},
                "size":{
                  "width":292,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录页面",
                      "target":{
                        "targetType":"page",
                        "url":"登录页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/设置/u6.png"}},
{
          "id":"2d0a67ff083e4f3898082a60a94e3815",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-1,
              "y":118},
            "size":{
              "width":320,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc3613b38431467fb971cd917cf1a3fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-1,
                  "y":118},
                "size":{
                  "width":320,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 推送通知开关提醒",
                      "target":{
                        "targetType":"page",
                        "url":"推送通知开关提醒.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/设置/u8.png"}},
{
          "id":"c5621dcb7b974c8d9482e29cc3e12841",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":274,
              "y":127},
            "size":{
              "width":32,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6fc76a43a2b49e98051d14b9c353a33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":274,
                  "y":127},
                "size":{
                  "width":32,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u10.png"}},
{
          "id":"4745e8387db94b90ba08333bcb5eef45",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "opacity":"0",
            "location":{
              "x":4,
              "y":161},
            "size":{
              "width":302,
              "height":33},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20c68337700545e9a82d2f4fe3fb60f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "opacity":"0",
                "location":{
                  "x":4,
                  "y":161},
                "size":{
                  "width":302,
                  "height":33},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 意见反馈",
                      "target":{
                        "targetType":"page",
                        "url":"意见反馈.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c84157d60fb24b13984712e24e85fe5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "opacity":"0",
            "location":{
              "x":0,
              "y":240},
            "size":{
              "width":302,
              "height":33},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b1662ae04534938a56eae71590dce44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "opacity":"0",
                "location":{
                  "x":0,
                  "y":240},
                "size":{
                  "width":302,
                  "height":33},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 关于劲态",
                      "target":{
                        "targetType":"page",
                        "url":"关于劲态.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18e2a63ccbac49b38258762039fa95c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "opacity":"0",
            "location":{
              "x":2,
              "y":279},
            "size":{
              "width":302,
              "height":33},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c13afc387ff240249323ed18d9a609f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "opacity":"0",
                "location":{
                  "x":2,
                  "y":279},
                "size":{
                  "width":302,
                  "height":33},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 帮助",
                      "target":{
                        "targetType":"page",
                        "url":"帮助.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f41776cd66ae4c4cbaef71eaac5740ec",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":16},
            "size":{
              "width":22,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c896218dad0b40a7920bd68d644fd96b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":16},
                "size":{
                  "width":22,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 左侧边栏",
                      "target":{
                        "targetType":"page",
                        "url":"左侧边栏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/左侧边栏/u2.png"}},
{
          "id":"208c091af1a4443c836b9dff6ffb24bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "opacity":"0",
            "location":{
              "x":1,
              "y":200},
            "size":{
              "width":302,
              "height":33},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"309a097fd8954d009509a53b51917ca9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "opacity":"0",
                "location":{
                  "x":1,
                  "y":200},
                "size":{
                  "width":302,
                  "height":33},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 版本更新",
                      "target":{
                        "targetType":"page",
                        "url":"版本更新.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a3f25ef9d87490d8e32d0f761adb49a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "opacity":"0",
            "location":{
              "x":0,
              "y":80},
            "size":{
              "width":318,
              "height":33},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbc8b800a6e04c50b2e3ab0cb04f62d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "opacity":"0",
                "location":{
                  "x":0,
                  "y":80},
                "size":{
                  "width":318,
                  "height":33},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 清除缓存",
                      "target":{
                        "targetType":"page",
                        "url":"清除缓存.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "57a52d1f5f444fe49ed3c26ab8c94bb5":{
      "scriptId":"u0"},
    "638c011a745e4079ac45ac5987c8a2ca":{
      "scriptId":"u1"},
    "419437f49b93411dbafab01a7fd17e51":{
      "scriptId":"u2"},
    "411c6660087d4c92aa9f4f00ae70566c":{
      "scriptId":"u3"},
    "5a9fd7fe71ed498683de60daa4ba7d62":{
      "scriptId":"u4"},
    "424e54e92f2743adaeb7dd555ab3b6df":{
      "scriptId":"u5"},
    "a8d07aca2e024cf7aedcf5cf51c6983d":{
      "scriptId":"u6"},
    "add13de25423425380374cfd042ec4b7":{
      "scriptId":"u7"},
    "2d0a67ff083e4f3898082a60a94e3815":{
      "scriptId":"u8"},
    "bc3613b38431467fb971cd917cf1a3fc":{
      "scriptId":"u9"},
    "c5621dcb7b974c8d9482e29cc3e12841":{
      "scriptId":"u10"},
    "b6fc76a43a2b49e98051d14b9c353a33":{
      "scriptId":"u11"},
    "4745e8387db94b90ba08333bcb5eef45":{
      "scriptId":"u12"},
    "20c68337700545e9a82d2f4fe3fb60f7":{
      "scriptId":"u13"},
    "c84157d60fb24b13984712e24e85fe5c":{
      "scriptId":"u14"},
    "0b1662ae04534938a56eae71590dce44":{
      "scriptId":"u15"},
    "18e2a63ccbac49b38258762039fa95c0":{
      "scriptId":"u16"},
    "c13afc387ff240249323ed18d9a609f6":{
      "scriptId":"u17"},
    "f41776cd66ae4c4cbaef71eaac5740ec":{
      "scriptId":"u18"},
    "c896218dad0b40a7920bd68d644fd96b":{
      "scriptId":"u19"},
    "208c091af1a4443c836b9dff6ffb24bf":{
      "scriptId":"u20"},
    "309a097fd8954d009509a53b51917ca9":{
      "scriptId":"u21"},
    "3a3f25ef9d87490d8e32d0f761adb49a":{
      "scriptId":"u22"},
    "bbc8b800a6e04c50b2e3ab0cb04f62d9":{
      "scriptId":"u23"}}});