$axure.loadCurrentPage({
  "url":"下架提示.html",
  "generationDate":new Date(1432847387425.2),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f515796c4b0b461eaf2c36d77e955653",
    "type":"Axure:Page",
    "name":"下架提示",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"be380b0e9d3c491b9abf0bb6056dddeb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":548}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fda57332f2904766b8853e08b617dd05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":548}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 买时间",
                      "target":{
                        "targetType":"page",
                        "url":"买时间.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/下架提示/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "be380b0e9d3c491b9abf0bb6056dddeb":{
      "scriptId":"u0"},
    "fda57332f2904766b8853e08b617dd05":{
      "scriptId":"u1"}}});