$axure.loadCurrentPage({
  "url":"课程页面.html",
  "generationDate":new Date(1432921476348.28),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a3f7680c5b4f48f3853eed2ed59fa794",
    "type":"Axure:Page",
    "name":"课程页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"86fd98f661bd40b0b83a6ee04e273d49",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88cc6aaf6f9f46bda7415bceced61531",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户详情页（交易中）/u2.png"}},
{
          "id":"642e5a6bc0d64ff194fda52c2205dceb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":44},
            "size":{
              "width":320,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80ae692a2b254947804f212cc35c2237",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":44},
                "size":{
                  "width":320,
                  "height":106}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户详情页（交易中）/u4.png"}},
{
          "id":"746fce3b26c9498aa458c2d9b1882064",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":8,
              "y":4},
            "size":{
              "width":44,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a94e5b6675fd4f40a99d9c540e4a3cb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":8,
                  "y":4},
                "size":{
                  "width":44,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 左侧边栏",
                      "target":{
                        "targetType":"page",
                        "url":"左侧边栏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1331bcd5e1d54b458b95c346ad01334b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":122,
              "y":5},
            "size":{
              "width":76,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6209b54b0ce4347812942021878150c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":122,
                  "y":5},
                "size":{
                  "width":76,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8af379f631064cf1abafeb0d9e25d5d8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":159},
            "size":{
              "width":61,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a35a2202216e4861a3e04a36eba7bec9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":159},
                "size":{
                  "width":61,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商户信息介绍",
                      "target":{
                        "targetType":"page",
                        "url":"商户信息介绍.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商户详情页（交易中）/u10.png"}},
{
          "id":"f5e55cca7cc945d8ad4583c378eb954b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":92,
              "y":159},
            "size":{
              "width":61,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68283619229846aab1f3affa0e11a951",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":92,
                  "y":159},
                "size":{
                  "width":61,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商户详情页（交易中）",
                      "target":{
                        "targetType":"page",
                        "url":"商户详情页（交易中）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商户详情页（交易中）/u12.png"}},
{
          "id":"540790bbe5f243cca0e18d5113d1ffb2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":159},
            "size":{
              "width":61,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f61aea485134ad690df3a1bfa68e171",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":159},
                "size":{
                  "width":61,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 通知页面",
                      "target":{
                        "targetType":"page",
                        "url":"通知页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商户详情页（交易中）/u14.png"}},
{
          "id":"eb02735562334ff4ad29d1303b66f22d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":259,
              "y":159},
            "size":{
              "width":61,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"645b6ead5ae248349c2efbd3abfd34a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":259,
                  "y":159},
                "size":{
                  "width":61,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课程页面",
                      "target":{
                        "targetType":"page",
                        "url":"课程页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商户详情页（交易中）/u16.png"}},
{
          "id":"c74c62e32c3a49c3a67828f0ad385bc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":130,
              "y":60},
            "size":{
              "width":160,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5676a9b8090546519f1d1f1259a75a49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":130,
                  "y":60},
                "size":{
                  "width":160,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35c8bffd93e94e03a43c5790a77a0979",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":146,
              "y":105},
            "size":{
              "width":160,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"318aa3afa3324a1bb78472c4b5d46694",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":146,
                  "y":105},
                "size":{
                  "width":160,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a13976f288164cf58b0c25f7acb5074e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":147},
            "size":{
              "width":312,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户详情页（交易中）/u22_line.png"}},
{
          "id":"74105493ffdd49cbb0905d2ba8a51960",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":227},
            "size":{
              "width":312,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户详情页（交易中）/u22_line.png"}},
{
          "id":"70cb4c129ca143a3b303405d07ee1101",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":242},
            "size":{
              "width":320,
              "height":166}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19afc94a94f54759aee07419674c0d74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":242},
                "size":{
                  "width":320,
                  "height":166}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课程页面/u22.png"}},
{
          "id":"8bd1995b785c492f9419c82ec3709a40",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":14,
              "y":242},
            "size":{
              "width":36,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"358e2ef577d44bfca62f43c7eb62b7db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":14,
                  "y":242},
                "size":{
                  "width":36,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5469d540505943e7b6d0ff368e17ea9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":16,
              "y":330},
            "size":{
              "width":40,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94a10fa0262f43679d6ae82d207eed14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":16,
                  "y":330},
                "size":{
                  "width":40,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d88be63c2367433593591df2dc70c930",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":74,
              "y":330},
            "size":{
              "width":50,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66ae303b9459437787cafcf41536687e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":74,
                  "y":330},
                "size":{
                  "width":50,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1930ac14ff64ea99db89993515121c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":134,
              "y":330},
            "size":{
              "width":52,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45fcd895819b492bb7bb5f0e65bac9f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":134,
                  "y":330},
                "size":{
                  "width":52,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c144734f1f494f1da7e5088845a51ae1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":202,
              "y":330},
            "size":{
              "width":40,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7da5e37283da469f81cbea0e065f1c12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":202,
                  "y":330},
                "size":{
                  "width":40,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12bc8fa470aa47c28c01bd1e1fdc6318",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":264,
              "y":330},
            "size":{
              "width":40,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b11bbf658fad410e895c4e9233d3cef3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":264,
                  "y":330},
                "size":{
                  "width":40,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab160376d0a543259a4f41bf7d55a079",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":16,
              "y":410},
            "size":{
              "width":40,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"149a72e9cf18463f8e12a06696fcb268",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":16,
                  "y":410},
                "size":{
                  "width":40,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"49a587c505994ff09a4ed4319f11c24f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":79,
              "y":410},
            "size":{
              "width":40,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c570147cd91f46a5a6d8966f3ebf59b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":79,
                  "y":410},
                "size":{
                  "width":40,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b472f6954ab84e07956c33c463ded98d",
          "label":"ButtonBigSecondary",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontSize":"18px",
            "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
            "opacity":"0.6",
            "location":{
              "x":192,
              "y":44},
            "size":{
              "width":130,
              "height":76},
            "visible":false,
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab321b8ece1d4d9f8a097ad35e3182df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"18px",
                "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
                "opacity":"0.6",
                "location":{
                  "x":192,
                  "y":44},
                "size":{
                  "width":130,
                  "height":76},
                "visible":false,
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/buttonbigsecondary_u58.png"}},
{
          "id":"88d701e3850243e5b694047605588fd6",
          "label":"买卖时间",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":192,
              "y":44},
            "size":{
              "width":130,
              "height":76},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"5c2e08ceea254c9fa57ba65a29ca70a8",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"17bf1eb3acb04dd6bac7fb6d8bdec015",
                  "label":"",
                  "parentDynamicPanel":"88d701e3850243e5b694047605588fd6",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":130,
                      "height":76}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7ff7221fe36242c4bb81b4ca2e947029",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"88d701e3850243e5b694047605588fd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":130,
                          "height":76}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/买时间/u61.png"}},
{
                  "id":"1bcbb38f0b8f4052abc8bbd50a705dda",
                  "label":"",
                  "parentDynamicPanel":"88d701e3850243e5b694047605588fd6",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0",
                    "location":{
                      "x":0,
                      "y":1},
                    "size":{
                      "width":130,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"54666c95e5d548d9906ba1a6bdf94a90",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"88d701e3850243e5b694047605588fd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0",
                        "location":{
                          "x":0,
                          "y":1},
                        "size":{
                          "width":130,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 发布出售信息",
                              "target":{
                                "targetType":"page",
                                "url":"发布出售信息.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6db9282b0b4c48f0be94238c694c49ab",
                  "label":"",
                  "parentDynamicPanel":"88d701e3850243e5b694047605588fd6",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0",
                    "location":{
                      "x":0,
                      "y":41},
                    "size":{
                      "width":130,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4344969bf8bf439eafc873deb52d2b1f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"88d701e3850243e5b694047605588fd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0",
                        "location":{
                          "x":0,
                          "y":41},
                        "size":{
                          "width":130,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 发布求购信息",
                              "target":{
                                "targetType":"page",
                                "url":"发布求购信息.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"d682f57dcce84dbbba16f72088613417",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":272,
              "y":5},
            "size":{
              "width":43,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a982b996bb6d46489146ca1b69e4a74d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":272,
                  "y":5},
                "size":{
                  "width":43,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (Image) 向下滑动 500 毫秒,<br>买卖时间 向下滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["17bf1eb3acb04dd6bac7fb6d8bdec015"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}},
{
                          "objectPath":["88d701e3850243e5b694047605588fd6"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "86fd98f661bd40b0b83a6ee04e273d49":{
      "scriptId":"u0"},
    "88cc6aaf6f9f46bda7415bceced61531":{
      "scriptId":"u1"},
    "642e5a6bc0d64ff194fda52c2205dceb":{
      "scriptId":"u2"},
    "80ae692a2b254947804f212cc35c2237":{
      "scriptId":"u3"},
    "746fce3b26c9498aa458c2d9b1882064":{
      "scriptId":"u4"},
    "a94e5b6675fd4f40a99d9c540e4a3cb3":{
      "scriptId":"u5"},
    "1331bcd5e1d54b458b95c346ad01334b":{
      "scriptId":"u6"},
    "a6209b54b0ce4347812942021878150c":{
      "scriptId":"u7"},
    "8af379f631064cf1abafeb0d9e25d5d8":{
      "scriptId":"u8"},
    "a35a2202216e4861a3e04a36eba7bec9":{
      "scriptId":"u9"},
    "f5e55cca7cc945d8ad4583c378eb954b":{
      "scriptId":"u10"},
    "68283619229846aab1f3affa0e11a951":{
      "scriptId":"u11"},
    "540790bbe5f243cca0e18d5113d1ffb2":{
      "scriptId":"u12"},
    "0f61aea485134ad690df3a1bfa68e171":{
      "scriptId":"u13"},
    "eb02735562334ff4ad29d1303b66f22d":{
      "scriptId":"u14"},
    "645b6ead5ae248349c2efbd3abfd34a6":{
      "scriptId":"u15"},
    "c74c62e32c3a49c3a67828f0ad385bc8":{
      "scriptId":"u16"},
    "5676a9b8090546519f1d1f1259a75a49":{
      "scriptId":"u17"},
    "35c8bffd93e94e03a43c5790a77a0979":{
      "scriptId":"u18"},
    "318aa3afa3324a1bb78472c4b5d46694":{
      "scriptId":"u19"},
    "a13976f288164cf58b0c25f7acb5074e":{
      "scriptId":"u20"},
    "74105493ffdd49cbb0905d2ba8a51960":{
      "scriptId":"u21"},
    "70cb4c129ca143a3b303405d07ee1101":{
      "scriptId":"u22"},
    "19afc94a94f54759aee07419674c0d74":{
      "scriptId":"u23"},
    "8bd1995b785c492f9419c82ec3709a40":{
      "scriptId":"u24"},
    "358e2ef577d44bfca62f43c7eb62b7db":{
      "scriptId":"u25"},
    "5469d540505943e7b6d0ff368e17ea9b":{
      "scriptId":"u26"},
    "94a10fa0262f43679d6ae82d207eed14":{
      "scriptId":"u27"},
    "d88be63c2367433593591df2dc70c930":{
      "scriptId":"u28"},
    "66ae303b9459437787cafcf41536687e":{
      "scriptId":"u29"},
    "a1930ac14ff64ea99db89993515121c3":{
      "scriptId":"u30"},
    "45fcd895819b492bb7bb5f0e65bac9f6":{
      "scriptId":"u31"},
    "c144734f1f494f1da7e5088845a51ae1":{
      "scriptId":"u32"},
    "7da5e37283da469f81cbea0e065f1c12":{
      "scriptId":"u33"},
    "12bc8fa470aa47c28c01bd1e1fdc6318":{
      "scriptId":"u34"},
    "b11bbf658fad410e895c4e9233d3cef3":{
      "scriptId":"u35"},
    "ab160376d0a543259a4f41bf7d55a079":{
      "scriptId":"u36"},
    "149a72e9cf18463f8e12a06696fcb268":{
      "scriptId":"u37"},
    "49a587c505994ff09a4ed4319f11c24f":{
      "scriptId":"u38"},
    "c570147cd91f46a5a6d8966f3ebf59b9":{
      "scriptId":"u39"},
    "b472f6954ab84e07956c33c463ded98d":{
      "scriptId":"u40"},
    "ab321b8ece1d4d9f8a097ad35e3182df":{
      "scriptId":"u41"},
    "88d701e3850243e5b694047605588fd6":{
      "scriptId":"u42"},
    "17bf1eb3acb04dd6bac7fb6d8bdec015":{
      "scriptId":"u43"},
    "7ff7221fe36242c4bb81b4ca2e947029":{
      "scriptId":"u44"},
    "1bcbb38f0b8f4052abc8bbd50a705dda":{
      "scriptId":"u45"},
    "54666c95e5d548d9906ba1a6bdf94a90":{
      "scriptId":"u46"},
    "6db9282b0b4c48f0be94238c694c49ab":{
      "scriptId":"u47"},
    "4344969bf8bf439eafc873deb52d2b1f":{
      "scriptId":"u48"},
    "d682f57dcce84dbbba16f72088613417":{
      "scriptId":"u49"},
    "a982b996bb6d46489146ca1b69e4a74d":{
      "scriptId":"u50"}}});