$axure.loadCurrentPage({
  "url":"搜索页_切换城市.html",
  "generationDate":new Date(1430845023627.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"615b62a8e1ef4e35ab6b0834dc9f3546",
    "type":"Axure:Page",
    "name":"搜索页&切换城市",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"815a70196ee7428087961fa04ad13887",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e68a3a0880f4564850b797d97881e9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索页_切换城市/u0.png"}},
{
          "id":"8cd51e71cb4d4483b6692223050ab4f6",
          "label":"ButtonBigSecondary",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontSize":"18px",
            "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
            "opacity":"0.6",
            "location":{
              "x":233,
              "y":108},
            "size":{
              "width":87,
              "height":102},
            "visible":false,
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86484046599543d8851ab46b97f2cbd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"18px",
                "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
                "opacity":"0.6",
                "location":{
                  "x":233,
                  "y":108},
                "size":{
                  "width":87,
                  "height":102},
                "visible":false,
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索页_切换城市/buttonbigsecondary_u2.png"}},
{
          "id":"76e1a5c5ccec430fbeeeb6ef7c4d87d8",
          "label":"城市列表",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":233,
              "y":108},
            "size":{
              "width":87,
              "height":102},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"c3bf00cc7e5a414c9c18612dad30de79",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"32c31e9b25374240a0fd51942c3c292a",
                  "label":"",
                  "parentDynamicPanel":"76e1a5c5ccec430fbeeeb6ef7c4d87d8",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":87,
                      "height":102}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7560af9c66c4455eb946170b2954f436",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"76e1a5c5ccec430fbeeeb6ef7c4d87d8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":87,
                          "height":102}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市列表,<br>(Image)",
                              "objectsToFades":[{
                                  "objectPath":["76e1a5c5ccec430fbeeeb6ef7c4d87d8"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["32c31e9b25374240a0fd51942c3c292a"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/搜索页_切换城市/u5.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"2500ac93a0334a638c1cd7eff8990da1",
          "label":"键盘",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":0,
              "y":352},
            "size":{
              "width":320,
              "height":216},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"d61ef1394d8c469998c3e1c9cb857c06",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"90a2b00e86b64a5ea96c385954b2cffb",
                  "label":"",
                  "parentDynamicPanel":"2500ac93a0334a638c1cd7eff8990da1",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":216}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2af93e0429f742578b3c1ebb8a67b7e2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2500ac93a0334a638c1cd7eff8990da1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":216}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 键盘,<br>隐藏 (Image) 向下滑动 500 毫秒 收起 部件 向下",
                              "objectsToFades":[{
                                  "objectPath":["2500ac93a0334a638c1cd7eff8990da1"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["90a2b00e86b64a5ea96c385954b2cffb"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"slideDown",
                                      "duration":500,
                                      "showType":"compress",
                                      "vertical":true,
                                      "compressEasing":"none",
                                      "compressDuration":500}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/搜索页_切换城市/u8.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"9e20e65c989146fa9439113112e92a2b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":71},
            "size":{
              "width":245,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16c6a0f85b734a409e3cd7f59b8a2b17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":71},
                "size":{
                  "width":245,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 键盘 向上滑动 500 毫秒,<br>(Image) 向上滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["2500ac93a0334a638c1cd7eff8990da1"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideUp",
                              "duration":500,
                              "showType":"none"}}},
{
                          "objectPath":["90a2b00e86b64a5ea96c385954b2cffb"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideUp",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/搜索页_切换城市/u10.png"}},
{
          "id":"c1b8a668bbde44aba49f089ecd3c44a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":261,
              "y":71},
            "size":{
              "width":49,
              "height":27},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9a3284e85c74b45819986052b83c4bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":261,
                  "y":71},
                "size":{
                  "width":49,
                  "height":27},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 城市列表 向下滑动 500 毫秒,<br>(Image) 向下滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["76e1a5c5ccec430fbeeeb6ef7c4d87d8"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}},
{
                          "objectPath":["32c31e9b25374240a0fd51942c3c292a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1777a51542304c76827ea7fef6f9c086",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":41,
              "y":262},
            "size":{
              "width":39,
              "height":37},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"282341bd7e7b46b09e0519922546b20c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":41,
                  "y":262},
                "size":{
                  "width":39,
                  "height":37},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 地图导航页",
                      "target":{
                        "targetType":"page",
                        "url":"地图导航页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45e8e6497d274138ba383ba1088cea0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":86,
              "y":262},
            "size":{
              "width":124,
              "height":37},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13fdeb01b31c4bd6aa13a7b436aa73d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":86,
                  "y":262},
                "size":{
                  "width":124,
                  "height":37},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商户详情页（交易中）",
                      "target":{
                        "targetType":"page",
                        "url":"商户详情页（交易中）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc97975ab13d457aa9c3d609d9655267",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":36},
            "size":{
              "width":22,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f82403f600144cb792d28b1129bd0ef4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":36},
                "size":{
                  "width":22,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 左侧边栏",
                      "target":{
                        "targetType":"page",
                        "url":"左侧边栏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/左侧边栏/u2.png"}},
{
          "id":"cfe99356d8e5443a8ceb4153b44afe2b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":289,
              "y":35},
            "size":{
              "width":16,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"560446d3c30f4ed295f83a47234c9492",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":289,
                  "y":35},
                "size":{
                  "width":16,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u2.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "815a70196ee7428087961fa04ad13887":{
      "scriptId":"u0"},
    "9e68a3a0880f4564850b797d97881e9d":{
      "scriptId":"u1"},
    "8cd51e71cb4d4483b6692223050ab4f6":{
      "scriptId":"u2"},
    "86484046599543d8851ab46b97f2cbd1":{
      "scriptId":"u3"},
    "76e1a5c5ccec430fbeeeb6ef7c4d87d8":{
      "scriptId":"u4"},
    "32c31e9b25374240a0fd51942c3c292a":{
      "scriptId":"u5"},
    "7560af9c66c4455eb946170b2954f436":{
      "scriptId":"u6"},
    "2500ac93a0334a638c1cd7eff8990da1":{
      "scriptId":"u7"},
    "90a2b00e86b64a5ea96c385954b2cffb":{
      "scriptId":"u8"},
    "2af93e0429f742578b3c1ebb8a67b7e2":{
      "scriptId":"u9"},
    "9e20e65c989146fa9439113112e92a2b":{
      "scriptId":"u10"},
    "16c6a0f85b734a409e3cd7f59b8a2b17":{
      "scriptId":"u11"},
    "c1b8a668bbde44aba49f089ecd3c44a2":{
      "scriptId":"u12"},
    "f9a3284e85c74b45819986052b83c4bc":{
      "scriptId":"u13"},
    "1777a51542304c76827ea7fef6f9c086":{
      "scriptId":"u14"},
    "282341bd7e7b46b09e0519922546b20c":{
      "scriptId":"u15"},
    "45e8e6497d274138ba383ba1088cea0a":{
      "scriptId":"u16"},
    "13fdeb01b31c4bd6aa13a7b436aa73d6":{
      "scriptId":"u17"},
    "cc97975ab13d457aa9c3d609d9655267":{
      "scriptId":"u18"},
    "f82403f600144cb792d28b1129bd0ef4":{
      "scriptId":"u19"},
    "cfe99356d8e5443a8ceb4153b44afe2b":{
      "scriptId":"u20"},
    "560446d3c30f4ed295f83a47234c9492":{
      "scriptId":"u21"}}});