$axure.loadCurrentPage({
  "url":"卖时间.html",
  "generationDate":new Date(1432921474851.2),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d8e1490d665e458d8170bffe890848f5",
    "type":"Axure:Page",
    "name":"卖时间",
    "notes":{
      "默认":"<p><span>1.【回应】成立之后，出售信息会在30分钟内保持PRIVITE私有，仅求购方可见。30分钟后系统置为PUBLIC，并且在出售列表顶部新插入一条信息。</span></p>"},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b88192fc94e94ec88b9e5833939fcc29",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":44},
            "size":{
              "width":320,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dc2fd16462c40f38702c474d18070df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":44},
                "size":{
                  "width":320,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/卖时间/u0.png"}},
{
          "id":"91b45c65d2cd4bb985076e722bcc3196",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF4175B9,
              "opacity":1},
            "location":{
              "x":87,
              "y":53},
            "size":{
              "width":70,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1ef8eb36e1a486993b28e486bca1618",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF4175B9,
                  "opacity":1},
                "location":{
                  "x":87,
                  "y":53},
                "size":{
                  "width":70,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 买时间",
                      "target":{
                        "targetType":"page",
                        "url":"买时间.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d09a11b5626e4de8b3f9006ebeb4fe38",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":162,
              "y":53},
            "size":{
              "width":70,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90e94385eec54b85b03c1d4ede66841d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":162,
                  "y":53},
                "size":{
                  "width":70,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3be71dedafa44e12a5064ca33f990c89",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f0f55afb6ef44f2b9c2c8a0ce50c066",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/u0.png"}},
{
          "id":"3db2b4ae87594b0293a3f9eb797bfb6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":118,
              "y":4},
            "size":{
              "width":84,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0e8f2e87e6549f7954f7e4067ccd413",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":118,
                  "y":4},
                "size":{
                  "width":84,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a98f993e023d4583933e73ee12d44f39",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":6,
              "y":4},
            "size":{
              "width":44,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07bf9e3f35a946f9a9c48639459104e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":6,
                  "y":4},
                "size":{
                  "width":44,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 左侧边栏",
                      "target":{
                        "targetType":"page",
                        "url":"左侧边栏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8aadff2894a34e46bd9e5aedf1d215bf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":89},
            "size":{
              "width":320,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8129dd1e18384317b88047854c345c19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":89},
                "size":{
                  "width":320,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/u12.png"}},
{
          "id":"4c7c69cd681a432e8090374b1cb7119f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":177},
            "size":{
              "width":320,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67aed8c8f7fd4b6c9596e0a8896b672f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":177},
                "size":{
                  "width":320,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/u14.png"}},
{
          "id":"45fa001e7f5543a3b6fa9f49968bc236",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":92,
              "y":90},
            "size":{
              "width":178,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7fe4cb6f4b246d6a13dda544b70f183",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":92,
                  "y":90},
                "size":{
                  "width":178,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b84416ad78774dd2999a8fc2f6089f0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":92,
              "y":109},
            "size":{
              "width":188,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e4cf4c1594f4711855b8b9a8c5be66b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":92,
                  "y":109},
                "size":{
                  "width":188,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"431026f6d3ab411e8875bafabbcab752",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":92,
              "y":181},
            "size":{
              "width":178,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"668486ef6c2343f3a67dafd2702c8fdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":92,
                  "y":181},
                "size":{
                  "width":178,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c9e13dccfc648438124d2921013c885",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":92,
              "y":200},
            "size":{
              "width":188,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8044816cc6e641fba43a670d1fe4609f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":92,
                  "y":200},
                "size":{
                  "width":188,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02a99544620a44c09ff9a61fde8bebc6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":265},
            "size":{
              "width":320,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecd1a582b1e4431daceb10a3b9270a29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":265},
                "size":{
                  "width":320,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/u24.png"}},
{
          "id":"d0131658fb2942ecb92bc1259d4e38ce",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":357},
            "size":{
              "width":320,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af6eaf44d6564685aff54a458b439f8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":357},
                "size":{
                  "width":320,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/u26.png"}},
{
          "id":"2470c2c733e54a7c9686357e7a5d5a13",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":25,
              "y":267},
            "size":{
              "width":178,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ef16f4347f64e62b5e38dfd66568d93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":25,
                  "y":267},
                "size":{
                  "width":178,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a58606ad618d425ba18258c8298e0e49",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":25,
              "y":286},
            "size":{
              "width":185,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7749b486e1e4740abf57cdccae79962",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":25,
                  "y":286},
                "size":{
                  "width":185,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 求购详情页",
                      "target":{
                        "targetType":"page",
                        "url":"求购详情页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8be8086a22ff4ec591238d8eb4deab05",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":247,
              "y":266},
            "size":{
              "width":70,
              "height":88}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0b8c6b47107485e99030aa6fd73bc92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":247,
                  "y":266},
                "size":{
                  "width":70,
                  "height":88}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 求购详情页",
                      "target":{
                        "targetType":"page",
                        "url":"求购详情页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"398742263c504166bd76c45e2bbdfb03",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":25,
              "y":359},
            "size":{
              "width":178,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"927c648a84634982b9dbbf2f5bd57757",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":25,
                  "y":359},
                "size":{
                  "width":178,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2abade750d95432694be3d1c7008e672",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":25,
              "y":378},
            "size":{
              "width":185,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b0242ddc5f14d739673f699b7c9a8ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":25,
                  "y":378},
                "size":{
                  "width":185,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 撤销提示",
                      "target":{
                        "targetType":"page",
                        "url":"撤销提示.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"350eb10f36ac4b8bb8a0e17f4f08d0ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":247,
              "y":358},
            "size":{
              "width":70,
              "height":88}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3be5f163c7445188366652f6b1b05d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":247,
                  "y":358},
                "size":{
                  "width":70,
                  "height":88}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 撤销提示",
                      "target":{
                        "targetType":"page",
                        "url":"撤销提示.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f2df367472c40b58fae6b31682162f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF6F5F6},
            "location":{
              "x":0,
              "y":445},
            "size":{
              "width":320,
              "height":86},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF6F5F6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98103152b6fc4e359c567c24b8e73652",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF6F5F6},
                "location":{
                  "x":0,
                  "y":445},
                "size":{
                  "width":320,
                  "height":86},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF6F5F6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/u40.png"}},
{
          "id":"f71a32bb8ab74e5da2b4dc1ba32a0df3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":458},
            "size":{
              "width":65,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5820ab58d6494296b8dfe86c7122199f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":458},
                "size":{
                  "width":65,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/u42.png"}},
{
          "id":"558f1f75bc124680a4f6c18a00868f8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":92,
              "y":446},
            "size":{
              "width":178,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"358fd6c4ef9647f78c965e903936fb25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":92,
                  "y":446},
                "size":{
                  "width":178,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2b62ef44be1480eb52cc594f2533c6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":92,
              "y":465},
            "size":{
              "width":182,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ab0338c830e41cb9cd443ce9fded4e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":92,
                  "y":465},
                "size":{
                  "width":182,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a5835187e6248da9a50646367e01a89",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":284,
              "y":474},
            "size":{
              "width":26,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07e0c66042714f298339f5f169d4889a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":284,
                  "y":474},
                "size":{
                  "width":26,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/u48.png"}},
{
          "id":"31c7f5408e444408bc6fcaa2bbd977ab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":227},
            "size":{
              "width":24,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b7aa97deddd4034ba425bd8a66aeb41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":227},
                "size":{
                  "width":24,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/卖时间/u50.png"}},
{
          "id":"9597dadfa4a44ef9b588725eb46cf4b2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":139},
            "size":{
              "width":24,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8f1f6637cc74b04a8bb8384d94434d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":139},
                "size":{
                  "width":24,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/卖时间/u50.png"}},
{
          "id":"ec7be63fc9d24bc3a6c2689c13f76d9d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":496},
            "size":{
              "width":24,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd34867b34724b38b8140fdc49965b82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":496},
                "size":{
                  "width":24,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/卖时间/u50.png"}},
{
          "id":"35a03985c88d4648b30928f4d2253073",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":3,
              "y":181},
            "size":{
              "width":309,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1afb2af88794c5595105d2c23de0539",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":3,
                  "y":181},
                "size":{
                  "width":309,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 求购详情页",
                      "target":{
                        "targetType":"page",
                        "url":"求购详情页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6c8fe28ba0d447781cf3ecd437c3112",
          "label":"ButtonBigSecondary",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontSize":"18px",
            "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
            "opacity":"0.6",
            "location":{
              "x":192,
              "y":44},
            "size":{
              "width":130,
              "height":76},
            "visible":false,
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6a0c7afb6c14a25a9132e670543e912",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"18px",
                "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
                "opacity":"0.6",
                "location":{
                  "x":192,
                  "y":44},
                "size":{
                  "width":130,
                  "height":76},
                "visible":false,
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/buttonbigsecondary_u58.png"}},
{
          "id":"b8dc29c50320437a9b722318861f77ad",
          "label":"买卖时间",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":192,
              "y":44},
            "size":{
              "width":130,
              "height":76},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"b869de66a7044d2abc6c3f6e07940d26",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"47342b2bb54a4ee2ad4642aab66e7549",
                  "label":"",
                  "parentDynamicPanel":"b8dc29c50320437a9b722318861f77ad",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":130,
                      "height":76}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"029aa3d0064748e5b903f951de9bd012",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b8dc29c50320437a9b722318861f77ad",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":130,
                          "height":76}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/买时间/u61.png"}},
{
                  "id":"96a50f3cb88d41be93eca11a9b538b49",
                  "label":"",
                  "parentDynamicPanel":"b8dc29c50320437a9b722318861f77ad",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0",
                    "location":{
                      "x":0,
                      "y":1},
                    "size":{
                      "width":130,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d0e45eb8b992442095f2361781d5bb66",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b8dc29c50320437a9b722318861f77ad",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0",
                        "location":{
                          "x":0,
                          "y":1},
                        "size":{
                          "width":130,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 发布出售信息",
                              "target":{
                                "targetType":"page",
                                "url":"发布出售信息.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c9fbe72225744519a3e53e67d11b6be5",
                  "label":"",
                  "parentDynamicPanel":"b8dc29c50320437a9b722318861f77ad",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0",
                    "location":{
                      "x":0,
                      "y":41},
                    "size":{
                      "width":130,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"303cdd66fd5149dea8c1c5dc1eea9e75",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b8dc29c50320437a9b722318861f77ad",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0",
                        "location":{
                          "x":0,
                          "y":41},
                        "size":{
                          "width":130,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 发布求购信息",
                              "target":{
                                "targetType":"page",
                                "url":"发布求购信息.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"1571b480f3d54fa29a4a9a24cd7c240a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":272,
              "y":5},
            "size":{
              "width":43,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22c11d1d004940aeaafb9a08c73bc11a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":272,
                  "y":5},
                "size":{
                  "width":43,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (Image) 向下滑动 500 毫秒,<br>买卖时间 向下滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["47342b2bb54a4ee2ad4642aab66e7549"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}},
{
                          "objectPath":["b8dc29c50320437a9b722318861f77ad"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "b88192fc94e94ec88b9e5833939fcc29":{
      "scriptId":"u0"},
    "8dc2fd16462c40f38702c474d18070df":{
      "scriptId":"u1"},
    "91b45c65d2cd4bb985076e722bcc3196":{
      "scriptId":"u2"},
    "c1ef8eb36e1a486993b28e486bca1618":{
      "scriptId":"u3"},
    "d09a11b5626e4de8b3f9006ebeb4fe38":{
      "scriptId":"u4"},
    "90e94385eec54b85b03c1d4ede66841d":{
      "scriptId":"u5"},
    "3be71dedafa44e12a5064ca33f990c89":{
      "scriptId":"u6"},
    "0f0f55afb6ef44f2b9c2c8a0ce50c066":{
      "scriptId":"u7"},
    "3db2b4ae87594b0293a3f9eb797bfb6d":{
      "scriptId":"u8"},
    "a0e8f2e87e6549f7954f7e4067ccd413":{
      "scriptId":"u9"},
    "a98f993e023d4583933e73ee12d44f39":{
      "scriptId":"u10"},
    "07bf9e3f35a946f9a9c48639459104e2":{
      "scriptId":"u11"},
    "8aadff2894a34e46bd9e5aedf1d215bf":{
      "scriptId":"u12"},
    "8129dd1e18384317b88047854c345c19":{
      "scriptId":"u13"},
    "4c7c69cd681a432e8090374b1cb7119f":{
      "scriptId":"u14"},
    "67aed8c8f7fd4b6c9596e0a8896b672f":{
      "scriptId":"u15"},
    "45fa001e7f5543a3b6fa9f49968bc236":{
      "scriptId":"u16"},
    "e7fe4cb6f4b246d6a13dda544b70f183":{
      "scriptId":"u17"},
    "b84416ad78774dd2999a8fc2f6089f0a":{
      "scriptId":"u18"},
    "3e4cf4c1594f4711855b8b9a8c5be66b":{
      "scriptId":"u19"},
    "431026f6d3ab411e8875bafabbcab752":{
      "scriptId":"u20"},
    "668486ef6c2343f3a67dafd2702c8fdd":{
      "scriptId":"u21"},
    "5c9e13dccfc648438124d2921013c885":{
      "scriptId":"u22"},
    "8044816cc6e641fba43a670d1fe4609f":{
      "scriptId":"u23"},
    "02a99544620a44c09ff9a61fde8bebc6":{
      "scriptId":"u24"},
    "ecd1a582b1e4431daceb10a3b9270a29":{
      "scriptId":"u25"},
    "d0131658fb2942ecb92bc1259d4e38ce":{
      "scriptId":"u26"},
    "af6eaf44d6564685aff54a458b439f8e":{
      "scriptId":"u27"},
    "2470c2c733e54a7c9686357e7a5d5a13":{
      "scriptId":"u28"},
    "5ef16f4347f64e62b5e38dfd66568d93":{
      "scriptId":"u29"},
    "a58606ad618d425ba18258c8298e0e49":{
      "scriptId":"u30"},
    "e7749b486e1e4740abf57cdccae79962":{
      "scriptId":"u31"},
    "8be8086a22ff4ec591238d8eb4deab05":{
      "scriptId":"u32"},
    "b0b8c6b47107485e99030aa6fd73bc92":{
      "scriptId":"u33"},
    "398742263c504166bd76c45e2bbdfb03":{
      "scriptId":"u34"},
    "927c648a84634982b9dbbf2f5bd57757":{
      "scriptId":"u35"},
    "2abade750d95432694be3d1c7008e672":{
      "scriptId":"u36"},
    "8b0242ddc5f14d739673f699b7c9a8ed":{
      "scriptId":"u37"},
    "350eb10f36ac4b8bb8a0e17f4f08d0ad":{
      "scriptId":"u38"},
    "c3be5f163c7445188366652f6b1b05d7":{
      "scriptId":"u39"},
    "8f2df367472c40b58fae6b31682162f0":{
      "scriptId":"u40"},
    "98103152b6fc4e359c567c24b8e73652":{
      "scriptId":"u41"},
    "f71a32bb8ab74e5da2b4dc1ba32a0df3":{
      "scriptId":"u42"},
    "5820ab58d6494296b8dfe86c7122199f":{
      "scriptId":"u43"},
    "558f1f75bc124680a4f6c18a00868f8c":{
      "scriptId":"u44"},
    "358fd6c4ef9647f78c965e903936fb25":{
      "scriptId":"u45"},
    "c2b62ef44be1480eb52cc594f2533c6d":{
      "scriptId":"u46"},
    "2ab0338c830e41cb9cd443ce9fded4e1":{
      "scriptId":"u47"},
    "8a5835187e6248da9a50646367e01a89":{
      "scriptId":"u48"},
    "07e0c66042714f298339f5f169d4889a":{
      "scriptId":"u49"},
    "31c7f5408e444408bc6fcaa2bbd977ab":{
      "scriptId":"u50"},
    "2b7aa97deddd4034ba425bd8a66aeb41":{
      "scriptId":"u51"},
    "9597dadfa4a44ef9b588725eb46cf4b2":{
      "scriptId":"u52"},
    "f8f1f6637cc74b04a8bb8384d94434d1":{
      "scriptId":"u53"},
    "ec7be63fc9d24bc3a6c2689c13f76d9d":{
      "scriptId":"u54"},
    "fd34867b34724b38b8140fdc49965b82":{
      "scriptId":"u55"},
    "35a03985c88d4648b30928f4d2253073":{
      "scriptId":"u56"},
    "e1afb2af88794c5595105d2c23de0539":{
      "scriptId":"u57"},
    "d6c8fe28ba0d447781cf3ecd437c3112":{
      "scriptId":"u58"},
    "b6a0c7afb6c14a25a9132e670543e912":{
      "scriptId":"u59"},
    "b8dc29c50320437a9b722318861f77ad":{
      "scriptId":"u60"},
    "47342b2bb54a4ee2ad4642aab66e7549":{
      "scriptId":"u61"},
    "029aa3d0064748e5b903f951de9bd012":{
      "scriptId":"u62"},
    "96a50f3cb88d41be93eca11a9b538b49":{
      "scriptId":"u63"},
    "d0e45eb8b992442095f2361781d5bb66":{
      "scriptId":"u64"},
    "c9fbe72225744519a3e53e67d11b6be5":{
      "scriptId":"u65"},
    "303cdd66fd5149dea8c1c5dc1eea9e75":{
      "scriptId":"u66"},
    "1571b480f3d54fa29a4a9a24cd7c240a":{
      "scriptId":"u67"},
    "22c11d1d004940aeaafb9a08c73bc11a":{
      "scriptId":"u68"}}});