$axure.loadCurrentPage({
  "url":"促销优惠信息.html",
  "generationDate":new Date(1432921476032.27),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"56a5d33a183c409692de814eb3d626fb",
    "type":"Axure:Page",
    "name":"促销优惠信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dcf801248f194612846fa0e4b5f2e2b6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a02f8d1b9fa43109f67e2e81fb660a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户详情页（交易中）/u2.png"}},
{
          "id":"b57e3f8f68c44baba9c6e5943460e1fc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":44},
            "size":{
              "width":320,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f5e865548474486a38dfb0444fbc5eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":44},
                "size":{
                  "width":320,
                  "height":106}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户详情页（交易中）/u4.png"}},
{
          "id":"64bf0007749f47b5abcbefcfef4c436b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":8,
              "y":4},
            "size":{
              "width":44,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65cf3f5ed6514a17ae98463231cf32e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":8,
                  "y":4},
                "size":{
                  "width":44,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 左侧边栏",
                      "target":{
                        "targetType":"page",
                        "url":"左侧边栏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a2da63535e1948f7bba59c71cd926aac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":122,
              "y":5},
            "size":{
              "width":76,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f022a47967294757a5ddf4302a671750",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":122,
                  "y":5},
                "size":{
                  "width":76,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54b02aa55c3b479593d0704d254162ab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":159},
            "size":{
              "width":61,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb272336ae104c15842789fc65cffe9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":159},
                "size":{
                  "width":61,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 通知页面",
                      "target":{
                        "targetType":"page",
                        "url":"通知页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商户详情页（交易中）/u14.png"}},
{
          "id":"a94c9064bd0b4901b93b5375b570596a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":98,
              "y":159},
            "size":{
              "width":61,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a1071f191f3442c91bab41485bbed06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":98,
                  "y":159},
                "size":{
                  "width":61,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课程页面",
                      "target":{
                        "targetType":"page",
                        "url":"课程页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商户详情页（交易中）/u16.png"}},
{
          "id":"e08fda59c09c424599665e331069edb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":130,
              "y":60},
            "size":{
              "width":160,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bf36bd6099a47d7ae8060d9a0c036af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":130,
                  "y":60},
                "size":{
                  "width":160,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f5963f1761a412b803b8d134e05e620",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":146,
              "y":105},
            "size":{
              "width":160,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3eea490c79647fe83a2abdd520cac95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":146,
                  "y":105},
                "size":{
                  "width":160,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1eed3f3e517f4db2b86f7486772d91fb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":147},
            "size":{
              "width":312,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户详情页（交易中）/u22_line.png"}},
{
          "id":"61660051438d43049a5a46f826432261",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":227},
            "size":{
              "width":312,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商户详情页（交易中）/u22_line.png"}},
{
          "id":"58dd4452823748a8941618f032d43f32",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":177,
              "y":159},
            "size":{
              "width":61,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7000d70f69ac446dbc27408da61fdc1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":177,
                  "y":159},
                "size":{
                  "width":61,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 促销优惠信息",
                      "target":{
                        "targetType":"page",
                        "url":"促销优惠信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/促销优惠信息/u18.png"}},
{
          "id":"86074c6f51404794b361d302785fa9f0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":254,
              "y":159},
            "size":{
              "width":61,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8356139bc11d4f4bbac51837b70408fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":254,
                  "y":159},
                "size":{
                  "width":61,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 评价页面",
                      "target":{
                        "targetType":"page",
                        "url":"评价页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/促销优惠信息/u20.png"}},
{
          "id":"4cd4ac64c5b94c13a3e1a4a4e9756f95",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":223},
            "size":{
              "width":320,
              "height":326}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"757086e99b9f43dbb1cc1408f769e59f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":223},
                "size":{
                  "width":320,
                  "height":326}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/促销优惠信息/u22.png"}},
{
          "id":"e41616dfe2674bb289ceb4becb239f89",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":12,
              "y":221},
            "size":{
              "width":36,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be0a75e4c1ce4c5781a1f7b19ecac21b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":12,
                  "y":221},
                "size":{
                  "width":36,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5af42acaf3a4a73b0a0a5cfdfa12046",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF67C7BB,
              "opacity":1},
            "location":{
              "x":13,
              "y":252},
            "size":{
              "width":300,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ae1ddef66754dd19b852e543826d651",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF67C7BB,
                  "opacity":1},
                "location":{
                  "x":13,
                  "y":252},
                "size":{
                  "width":300,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b2a875feac04b74a5e5e514812e62cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF67C7BB,
              "opacity":1},
            "location":{
              "x":13,
              "y":329},
            "size":{
              "width":300,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7af147931584ef9bc59e49b41fa03d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF67C7BB,
                  "opacity":1},
                "location":{
                  "x":13,
                  "y":329},
                "size":{
                  "width":300,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa449abe4e0c4a5ca01122dff6e8adbc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF67C7BB,
              "opacity":1},
            "location":{
              "x":13,
              "y":404},
            "size":{
              "width":300,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee8668a28be24926bd480b5aa2843d5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF67C7BB,
                  "opacity":1},
                "location":{
                  "x":13,
                  "y":404},
                "size":{
                  "width":300,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4fb19c12966d44aab8d7b1ef0cb837e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF67C7BB,
              "opacity":1},
            "location":{
              "x":13,
              "y":481},
            "size":{
              "width":300,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fce9e7f15f6a4782a630b5c8da37eec8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF67C7BB,
                  "opacity":1},
                "location":{
                  "x":13,
                  "y":481},
                "size":{
                  "width":300,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4bcf8950b1724726b3d0cdc8e5529133",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":297,
              "y":266},
            "size":{
              "width":16,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa1d4c89119f46eba36f7ca1f1fe250a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":297,
                  "y":266},
                "size":{
                  "width":16,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户详情页（交易中）/u64.png"}},
{
          "id":"49f0a42f1266420a9b9551725d8fd802",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":297,
              "y":347},
            "size":{
              "width":16,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d93b85f39c574a02a710a397b25eefd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":297,
                  "y":347},
                "size":{
                  "width":16,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户详情页（交易中）/u64.png"}},
{
          "id":"0200bd2b10d24d569c307f189a45a74e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":297,
              "y":423},
            "size":{
              "width":16,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6000c714d9145478280dba084e4db1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":297,
                  "y":423},
                "size":{
                  "width":16,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户详情页（交易中）/u64.png"}},
{
          "id":"c7daa563fde24e7db43c31ab8d258145",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":297,
              "y":497},
            "size":{
              "width":16,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6486542b2e6d4e20add310c2400b0d47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":297,
                  "y":497},
                "size":{
                  "width":16,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户详情页（交易中）/u64.png"}},
{
          "id":"a39daed5728d45ffbc1c4b31f3d557e8",
          "label":"ButtonBigSecondary",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontSize":"18px",
            "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
            "opacity":"0.6",
            "location":{
              "x":192,
              "y":44},
            "size":{
              "width":130,
              "height":76},
            "visible":false,
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0acb11a2193d4c5d9b10883ff3bca3f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"18px",
                "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
                "opacity":"0.6",
                "location":{
                  "x":192,
                  "y":44},
                "size":{
                  "width":130,
                  "height":76},
                "visible":false,
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/buttonbigsecondary_u58.png"}},
{
          "id":"247aa01bb4f3449a826aa4347195d8ab",
          "label":"买卖时间",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":192,
              "y":44},
            "size":{
              "width":130,
              "height":76},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"2c502e7a84914e508fb295d3e2fc407b",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"363cfc0e2000434b82b0510848f1f4ff",
                  "label":"",
                  "parentDynamicPanel":"247aa01bb4f3449a826aa4347195d8ab",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":130,
                      "height":76}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"908057bd3bdc4362bf43fd5089ffa22a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"247aa01bb4f3449a826aa4347195d8ab",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":130,
                          "height":76}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/买时间/u61.png"}},
{
                  "id":"64e6aeb8bb2541a3a11ecb3d44c14ff7",
                  "label":"",
                  "parentDynamicPanel":"247aa01bb4f3449a826aa4347195d8ab",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0",
                    "location":{
                      "x":0,
                      "y":1},
                    "size":{
                      "width":130,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"00fffdcb30be47689edcec8dedc028e1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"247aa01bb4f3449a826aa4347195d8ab",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0",
                        "location":{
                          "x":0,
                          "y":1},
                        "size":{
                          "width":130,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 发布出售信息",
                              "target":{
                                "targetType":"page",
                                "url":"发布出售信息.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bc8d4c35954d4bafbb824d530032c96f",
                  "label":"",
                  "parentDynamicPanel":"247aa01bb4f3449a826aa4347195d8ab",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0",
                    "location":{
                      "x":0,
                      "y":41},
                    "size":{
                      "width":130,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2f239dad91cf4ec1bb6870b9f894f335",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"247aa01bb4f3449a826aa4347195d8ab",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0",
                        "location":{
                          "x":0,
                          "y":41},
                        "size":{
                          "width":130,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 发布求购信息",
                              "target":{
                                "targetType":"page",
                                "url":"发布求购信息.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"dbb9c3c7343f4257b364ec1bcea05891",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":272,
              "y":5},
            "size":{
              "width":43,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72bdf24bc5f9442e845fdd95dc807b6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":272,
                  "y":5},
                "size":{
                  "width":43,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (Image) 向下滑动 500 毫秒,<br>买卖时间 向下滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["363cfc0e2000434b82b0510848f1f4ff"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}},
{
                          "objectPath":["247aa01bb4f3449a826aa4347195d8ab"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "dcf801248f194612846fa0e4b5f2e2b6":{
      "scriptId":"u0"},
    "3a02f8d1b9fa43109f67e2e81fb660a9":{
      "scriptId":"u1"},
    "b57e3f8f68c44baba9c6e5943460e1fc":{
      "scriptId":"u2"},
    "2f5e865548474486a38dfb0444fbc5eb":{
      "scriptId":"u3"},
    "64bf0007749f47b5abcbefcfef4c436b":{
      "scriptId":"u4"},
    "65cf3f5ed6514a17ae98463231cf32e4":{
      "scriptId":"u5"},
    "a2da63535e1948f7bba59c71cd926aac":{
      "scriptId":"u6"},
    "f022a47967294757a5ddf4302a671750":{
      "scriptId":"u7"},
    "54b02aa55c3b479593d0704d254162ab":{
      "scriptId":"u8"},
    "cb272336ae104c15842789fc65cffe9b":{
      "scriptId":"u9"},
    "a94c9064bd0b4901b93b5375b570596a":{
      "scriptId":"u10"},
    "5a1071f191f3442c91bab41485bbed06":{
      "scriptId":"u11"},
    "e08fda59c09c424599665e331069edb3":{
      "scriptId":"u12"},
    "3bf36bd6099a47d7ae8060d9a0c036af":{
      "scriptId":"u13"},
    "5f5963f1761a412b803b8d134e05e620":{
      "scriptId":"u14"},
    "f3eea490c79647fe83a2abdd520cac95":{
      "scriptId":"u15"},
    "1eed3f3e517f4db2b86f7486772d91fb":{
      "scriptId":"u16"},
    "61660051438d43049a5a46f826432261":{
      "scriptId":"u17"},
    "58dd4452823748a8941618f032d43f32":{
      "scriptId":"u18"},
    "7000d70f69ac446dbc27408da61fdc1e":{
      "scriptId":"u19"},
    "86074c6f51404794b361d302785fa9f0":{
      "scriptId":"u20"},
    "8356139bc11d4f4bbac51837b70408fa":{
      "scriptId":"u21"},
    "4cd4ac64c5b94c13a3e1a4a4e9756f95":{
      "scriptId":"u22"},
    "757086e99b9f43dbb1cc1408f769e59f":{
      "scriptId":"u23"},
    "e41616dfe2674bb289ceb4becb239f89":{
      "scriptId":"u24"},
    "be0a75e4c1ce4c5781a1f7b19ecac21b":{
      "scriptId":"u25"},
    "d5af42acaf3a4a73b0a0a5cfdfa12046":{
      "scriptId":"u26"},
    "2ae1ddef66754dd19b852e543826d651":{
      "scriptId":"u27"},
    "1b2a875feac04b74a5e5e514812e62cd":{
      "scriptId":"u28"},
    "e7af147931584ef9bc59e49b41fa03d1":{
      "scriptId":"u29"},
    "fa449abe4e0c4a5ca01122dff6e8adbc":{
      "scriptId":"u30"},
    "ee8668a28be24926bd480b5aa2843d5c":{
      "scriptId":"u31"},
    "4fb19c12966d44aab8d7b1ef0cb837e8":{
      "scriptId":"u32"},
    "fce9e7f15f6a4782a630b5c8da37eec8":{
      "scriptId":"u33"},
    "4bcf8950b1724726b3d0cdc8e5529133":{
      "scriptId":"u34"},
    "aa1d4c89119f46eba36f7ca1f1fe250a":{
      "scriptId":"u35"},
    "49f0a42f1266420a9b9551725d8fd802":{
      "scriptId":"u36"},
    "d93b85f39c574a02a710a397b25eefd2":{
      "scriptId":"u37"},
    "0200bd2b10d24d569c307f189a45a74e":{
      "scriptId":"u38"},
    "f6000c714d9145478280dba084e4db1e":{
      "scriptId":"u39"},
    "c7daa563fde24e7db43c31ab8d258145":{
      "scriptId":"u40"},
    "6486542b2e6d4e20add310c2400b0d47":{
      "scriptId":"u41"},
    "a39daed5728d45ffbc1c4b31f3d557e8":{
      "scriptId":"u42"},
    "0acb11a2193d4c5d9b10883ff3bca3f8":{
      "scriptId":"u43"},
    "247aa01bb4f3449a826aa4347195d8ab":{
      "scriptId":"u44"},
    "363cfc0e2000434b82b0510848f1f4ff":{
      "scriptId":"u45"},
    "908057bd3bdc4362bf43fd5089ffa22a":{
      "scriptId":"u46"},
    "64e6aeb8bb2541a3a11ecb3d44c14ff7":{
      "scriptId":"u47"},
    "00fffdcb30be47689edcec8dedc028e1":{
      "scriptId":"u48"},
    "bc8d4c35954d4bafbb824d530032c96f":{
      "scriptId":"u49"},
    "2f239dad91cf4ec1bb6870b9f894f335":{
      "scriptId":"u50"},
    "dbb9c3c7343f4257b364ec1bcea05891":{
      "scriptId":"u51"},
    "72bdf24bc5f9442e845fdd95dc807b6a":{
      "scriptId":"u52"}}});