$axure.loadCurrentPage({
  "url":"清除缓存.html",
  "generationDate":new Date(1430845026379.54),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"80c656c25c8b4d6abb9c1f783a893efa",
    "type":"Axure:Page",
    "name":"清除缓存",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"76a25da52de5478dbce87ff0999e6811",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e86fd461aed44f79227fe75d7f1a281",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/清除缓存/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "76a25da52de5478dbce87ff0999e6811":{
      "scriptId":"u0"},
    "9e86fd461aed44f79227fe75d7f1a281":{
      "scriptId":"u1"}}});