$axure.loadCurrentPage({
  "url":"商户信息介绍.html",
  "generationDate":new Date(1430066322826.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"65005bc613da451aa1c269a9542a92d4",
    "type":"Axure:Page",
    "name":"商户信息介绍",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"952f363043904cb49eae12856a5d7a31",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5321b2b6acaa4e3ea0b04b7894293436",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户信息介绍/u0.png"}},
{
          "id":"7aa11d98338c430d8f7be8cfa054b7ec",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":37},
            "size":{
              "width":22,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33c6ad654a824c60bfb8762b968c790d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":37},
                "size":{
                  "width":22,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 左侧边栏",
                      "target":{
                        "targetType":"page",
                        "url":"左侧边栏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/左侧边栏/u2.png"}},
{
          "id":"ff18c823222e4f548146e557236b8d6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":269,
              "y":26},
            "size":{
              "width":43,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01f04f5ef277464caa28bfd9e1c86119",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":269,
                  "y":26},
                "size":{
                  "width":43,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 买卖时间 向下滑动 500 毫秒,<br>(Image) 向下滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["687393d718c34c52929de0591a93340e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}},
{
                          "objectPath":["d7842bfcf5e944e4940c11f7059a2223"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f2fa544493141dfa80c9f045b7d9519",
          "label":"ButtonBigSecondary",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontSize":"18px",
            "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
            "opacity":"0.6",
            "location":{
              "x":188,
              "y":65},
            "size":{
              "width":130,
              "height":76},
            "visible":false,
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dfd77405a38496ea3032109a46edbe9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"18px",
                "baseStyle":"75622e06d7204397b5590f0ada6b0c32",
                "opacity":"0.6",
                "location":{
                  "x":188,
                  "y":65},
                "size":{
                  "width":130,
                  "height":76},
                "visible":false,
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/买时间/buttonbigsecondary_u6.png"}},
{
          "id":"687393d718c34c52929de0591a93340e",
          "label":"买卖时间",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":188,
              "y":65},
            "size":{
              "width":130,
              "height":76},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"e62a3c09fee94de4bddb58fa15e5c5d3",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d7842bfcf5e944e4940c11f7059a2223",
                  "label":"",
                  "parentDynamicPanel":"687393d718c34c52929de0591a93340e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":130,
                      "height":76}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4fdccf2bd9f4458a9ce08ce2c5f58b05",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"687393d718c34c52929de0591a93340e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":130,
                          "height":76}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/买时间/u9.png"}},
{
                  "id":"2550777cccd14eada0789c5230a6672b",
                  "label":"",
                  "parentDynamicPanel":"687393d718c34c52929de0591a93340e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0",
                    "location":{
                      "x":0,
                      "y":1},
                    "size":{
                      "width":130,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6ae1884c97f14f38aca16590e52fd8b0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"687393d718c34c52929de0591a93340e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0",
                        "location":{
                          "x":0,
                          "y":1},
                        "size":{
                          "width":130,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 发起出售请求页",
                              "target":{
                                "targetType":"page",
                                "url":"发起出售请求页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e508f7c3603946d4bbb71fefe8ee30c3",
                  "label":"",
                  "parentDynamicPanel":"687393d718c34c52929de0591a93340e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0",
                    "location":{
                      "x":0,
                      "y":41},
                    "size":{
                      "width":130,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"aa8163e1b56e450d820a24da2c24f3e9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"687393d718c34c52929de0591a93340e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0",
                        "location":{
                          "x":0,
                          "y":41},
                        "size":{
                          "width":130,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 发起购买请求页",
                              "target":{
                                "targetType":"page",
                                "url":"发起购买请求页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"9502e2053f944709a0ed6b23ccfed4d3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":198},
            "size":{
              "width":61,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ae535e01fbb48e395ac7ee651b7731e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":198},
                "size":{
                  "width":61,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商户信息介绍",
                      "target":{
                        "targetType":"page",
                        "url":"商户信息介绍.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商户详情页（交易中）/u19.png"}},
{
          "id":"559bef06a526499fb78516d0049a5063",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":197},
            "size":{
              "width":61,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6314ea79ff74bb0ac4f388f16c1db4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":88,
                  "y":197},
                "size":{
                  "width":61,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商户详情页（交易中）",
                      "target":{
                        "targetType":"page",
                        "url":"商户详情页（交易中）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商户详情页（交易中）/u21.png"}},
{
          "id":"88b6eaae2b784941b83131e950b8b415",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":163,
              "y":197},
            "size":{
              "width":60,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e391d691c304ea2ab3fb0e4d0230d3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":163,
                  "y":197},
                "size":{
                  "width":60,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 通知页面",
                      "target":{
                        "targetType":"page",
                        "url":"通知页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"67f612adc0ff43769b1a5bba5c29d46f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":236,
              "y":197},
            "size":{
              "width":61,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4695d0a1eef495881a159227631f174",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":236,
                  "y":197},
                "size":{
                  "width":61,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课程页面",
                      "target":{
                        "targetType":"page",
                        "url":"课程页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商户详情页（交易中）/u25.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "952f363043904cb49eae12856a5d7a31":{
      "scriptId":"u0"},
    "5321b2b6acaa4e3ea0b04b7894293436":{
      "scriptId":"u1"},
    "7aa11d98338c430d8f7be8cfa054b7ec":{
      "scriptId":"u2"},
    "33c6ad654a824c60bfb8762b968c790d":{
      "scriptId":"u3"},
    "ff18c823222e4f548146e557236b8d6b":{
      "scriptId":"u4"},
    "01f04f5ef277464caa28bfd9e1c86119":{
      "scriptId":"u5"},
    "1f2fa544493141dfa80c9f045b7d9519":{
      "scriptId":"u6"},
    "2dfd77405a38496ea3032109a46edbe9":{
      "scriptId":"u7"},
    "687393d718c34c52929de0591a93340e":{
      "scriptId":"u8"},
    "d7842bfcf5e944e4940c11f7059a2223":{
      "scriptId":"u9"},
    "4fdccf2bd9f4458a9ce08ce2c5f58b05":{
      "scriptId":"u10"},
    "2550777cccd14eada0789c5230a6672b":{
      "scriptId":"u11"},
    "6ae1884c97f14f38aca16590e52fd8b0":{
      "scriptId":"u12"},
    "e508f7c3603946d4bbb71fefe8ee30c3":{
      "scriptId":"u13"},
    "aa8163e1b56e450d820a24da2c24f3e9":{
      "scriptId":"u14"},
    "9502e2053f944709a0ed6b23ccfed4d3":{
      "scriptId":"u15"},
    "2ae535e01fbb48e395ac7ee651b7731e":{
      "scriptId":"u16"},
    "559bef06a526499fb78516d0049a5063":{
      "scriptId":"u17"},
    "e6314ea79ff74bb0ac4f388f16c1db4b":{
      "scriptId":"u18"},
    "88b6eaae2b784941b83131e950b8b415":{
      "scriptId":"u19"},
    "3e391d691c304ea2ab3fb0e4d0230d3f":{
      "scriptId":"u20"},
    "67f612adc0ff43769b1a5bba5c29d46f":{
      "scriptId":"u21"},
    "b4695d0a1eef495881a159227631f174":{
      "scriptId":"u22"}}});