$axure.loadCurrentPage({
  "url":"意见反馈.html",
  "generationDate":new Date(1432237668175.68),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"101b7f5a4d6047feae245690c0b688f5",
    "type":"Axure:Page",
    "name":"意见反馈",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"228340be19734fab953c29c30dc7286b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac91b2477e6143e58cfe24c729568c90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/意见反馈/u0.png"}},
{
          "id":"31962d144b5148e19d8e86416a16fee5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "location":{
              "x":125,
              "y":12},
            "size":{
              "width":70,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75cf15eb1c24470fb441490f40a73bcf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "location":{
                  "x":125,
                  "y":12},
                "size":{
                  "width":70,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"09ef6bc48d6948da836e47ccaa9e42cd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":3},
            "size":{
              "width":45,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d765e53a2a9848d08c97a57f9f606949",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":4,
                  "y":3},
                "size":{
                  "width":45,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设置",
                      "target":{
                        "targetType":"page",
                        "url":"设置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/意见反馈/u4.png"}},
{
          "id":"1f9bd7a318254fdb9b5b4862382d93ea",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":44},
            "size":{
              "width":320,
              "height":496}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"848416a69c754aa7b48eea1d98bc1c9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":44},
                "size":{
                  "width":320,
                  "height":496}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u0.png"}},
{
          "id":"0bb9f985a20c4c64b022de7dd6b7f9c4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":44},
            "size":{
              "width":320,
              "height":496}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6051ead3997f437f94ecf12477db6422",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":44},
                "size":{
                  "width":320,
                  "height":496}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/意见反馈/u8.jpg"}},
{
          "id":"3127b03819b04605abe7f62d9be87338",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":59.5,
              "y":490},
            "size":{
              "width":201,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5a0b36b891d4a05a55efbc8a3b7dc7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":59.5,
                  "y":490},
                "size":{
                  "width":201,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/意见反馈/u10.png"}},
{
          "id":"251c83b91d8646b2824ab5d2790be2f0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":178},
            "size":{
              "width":266,
              "height":172}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3aee5ee76a0346b2b97af41251702e3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":178},
                "size":{
                  "width":266,
                  "height":172}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 当前部件 淡入淡出 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["251c83b91d8646b2824ab5d2790be2f0"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/意见反馈/u12.png"}},
{
          "id":"d848ee46461f49b9b4fa16d6ce141ca0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF19A79C,
              "opacity":1},
            "location":{
              "x":28,
              "y":114},
            "size":{
              "width":263,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b48b73dbeb548f29c601a39e441cbc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF19A79C,
                  "opacity":1},
                "location":{
                  "x":28,
                  "y":114},
                "size":{
                  "width":263,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "228340be19734fab953c29c30dc7286b":{
      "scriptId":"u0"},
    "ac91b2477e6143e58cfe24c729568c90":{
      "scriptId":"u1"},
    "31962d144b5148e19d8e86416a16fee5":{
      "scriptId":"u2"},
    "75cf15eb1c24470fb441490f40a73bcf":{
      "scriptId":"u3"},
    "09ef6bc48d6948da836e47ccaa9e42cd":{
      "scriptId":"u4"},
    "d765e53a2a9848d08c97a57f9f606949":{
      "scriptId":"u5"},
    "1f9bd7a318254fdb9b5b4862382d93ea":{
      "scriptId":"u6"},
    "848416a69c754aa7b48eea1d98bc1c9e":{
      "scriptId":"u7"},
    "0bb9f985a20c4c64b022de7dd6b7f9c4":{
      "scriptId":"u8"},
    "6051ead3997f437f94ecf12477db6422":{
      "scriptId":"u9"},
    "3127b03819b04605abe7f62d9be87338":{
      "scriptId":"u10"},
    "b5a0b36b891d4a05a55efbc8a3b7dc7e":{
      "scriptId":"u11"},
    "251c83b91d8646b2824ab5d2790be2f0":{
      "scriptId":"u12"},
    "3aee5ee76a0346b2b97af41251702e3e":{
      "scriptId":"u13"},
    "d848ee46461f49b9b4fa16d6ce141ca0":{
      "scriptId":"u14"},
    "4b48b73dbeb548f29c601a39e441cbc9":{
      "scriptId":"u15"}}});