$axure.loadCurrentPage({
  "url":"意见反馈.html",
  "generationDate":new Date(1429794607685.12),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"101b7f5a4d6047feae245690c0b688f5",
    "type":"Axure:Page",
    "name":"意见反馈",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bc2e4d99661745dab96e9183853bf9e4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":820}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"618018268a4249ffbe446020eba29001",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":820}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u0.png"}},
{
          "id":"15042af4504c415e95a81ef7b0323271",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-1,
              "y":-33},
            "size":{
              "width":321,
              "height":844}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7f896cd512d40a9b62cd11c2b5628a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-1,
                  "y":-33},
                "size":{
                  "width":321,
                  "height":844}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/意见反馈/u2.png"}},
{
          "id":"3127b03819b04605abe7f62d9be87338",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":611},
            "size":{
              "width":201,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5a0b36b891d4a05a55efbc8a3b7dc7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":611},
                "size":{
                  "width":201,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/意见反馈/u4.png"}},
{
          "id":"228340be19734fab953c29c30dc7286b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac91b2477e6143e58cfe24c729568c90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/意见反馈/u6.png"}},
{
          "id":"31962d144b5148e19d8e86416a16fee5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "location":{
              "x":125,
              "y":12},
            "size":{
              "width":70,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75cf15eb1c24470fb441490f40a73bcf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "location":{
                  "x":125,
                  "y":12},
                "size":{
                  "width":70,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"09ef6bc48d6948da836e47ccaa9e42cd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":3},
            "size":{
              "width":45,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d765e53a2a9848d08c97a57f9f606949",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":4,
                  "y":3},
                "size":{
                  "width":45,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设置",
                      "target":{
                        "targetType":"page",
                        "url":"设置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/意见反馈/u10.png"}},
{
          "id":"251c83b91d8646b2824ab5d2790be2f0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":198},
            "size":{
              "width":266,
              "height":172}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3aee5ee76a0346b2b97af41251702e3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":198},
                "size":{
                  "width":266,
                  "height":172}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 当前部件 淡入淡出 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["251c83b91d8646b2824ab5d2790be2f0"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/意见反馈/u12.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "bc2e4d99661745dab96e9183853bf9e4":{
      "scriptId":"u0"},
    "618018268a4249ffbe446020eba29001":{
      "scriptId":"u1"},
    "15042af4504c415e95a81ef7b0323271":{
      "scriptId":"u2"},
    "c7f896cd512d40a9b62cd11c2b5628a2":{
      "scriptId":"u3"},
    "3127b03819b04605abe7f62d9be87338":{
      "scriptId":"u4"},
    "b5a0b36b891d4a05a55efbc8a3b7dc7e":{
      "scriptId":"u5"},
    "228340be19734fab953c29c30dc7286b":{
      "scriptId":"u6"},
    "ac91b2477e6143e58cfe24c729568c90":{
      "scriptId":"u7"},
    "31962d144b5148e19d8e86416a16fee5":{
      "scriptId":"u8"},
    "75cf15eb1c24470fb441490f40a73bcf":{
      "scriptId":"u9"},
    "09ef6bc48d6948da836e47ccaa9e42cd":{
      "scriptId":"u10"},
    "d765e53a2a9848d08c97a57f9f606949":{
      "scriptId":"u11"},
    "251c83b91d8646b2824ab5d2790be2f0":{
      "scriptId":"u12"},
    "3aee5ee76a0346b2b97af41251702e3e":{
      "scriptId":"u13"}}});