$axure.loadCurrentPage({
  "url":"我的消息（未读）.html",
  "generationDate":new Date(1432847391133.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d6d0d89646e04f8fb33e0e422e4a9d86",
    "type":"Axure:Page",
    "name":"我的消息（未读）",
    "notes":{
      "默认":"<p><span>（站内信推送+短信通知）</span></p>"},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2c47110a83a3413ca8986c9bd022018a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":-20},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a53fa6ec5bfc464ab5eee4eaec89b3b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":-20},
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的消息（未读）/u0.png"}},
{
          "id":"19572c675f814dc48ec1926834d488b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":276,
              "y":5},
            "size":{
              "width":43,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ec89f1eb9794de8a4cb6eb6af8f7ee5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":276,
                  "y":5},
                "size":{
                  "width":43,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的健身数据",
                      "target":{
                        "targetType":"page",
                        "url":"我的健身数据.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57873a1a0fb24372bc08f0b05b3dcb2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":240,
              "y":232},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22ea1c5a15b94c96803058b1ea9378f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":240,
                  "y":232},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的评价（持卡人评价我）",
                      "target":{
                        "targetType":"page",
                        "url":"我的评价（持卡人评价我）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9925f76ab2ae4db1adced61f2fe9cde1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":167,
              "y":232},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f47efc6d2b543fc909d55aa370024f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":167,
                  "y":232},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的交易",
                      "target":{
                        "targetType":"page",
                        "url":"我的交易.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"250a4af0c43b484c9dc0ae776381ac5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":93,
              "y":232},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"557f15802d9d458ea4533b2df09fbde7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":93,
                  "y":232},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的劲态（默认关注）",
                      "target":{
                        "targetType":"page",
                        "url":"我的劲态（默认关注）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d678c6e2dd904c34be02e3944932ff70",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":19,
              "y":232},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ebba040429f4c60ae41a160eb352b57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":19,
                  "y":232},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的消息（未读）",
                      "target":{
                        "targetType":"page",
                        "url":"我的消息（未读）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d3d10c68f024e34961c82fffb2359d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":4,
              "y":4},
            "size":{
              "width":44,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbeaa3ba78ee4236bc43d03dd173d211",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":4,
                  "y":4},
                "size":{
                  "width":44,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 左侧边栏",
                      "target":{
                        "targetType":"page",
                        "url":"左侧边栏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e8dd69144f14f43acc1f07a49e8fb9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":270,
              "y":160},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff30550e1b6c44558d0b7a26d7c90a72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":270,
                  "y":160},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的劲态（二维码）",
                      "target":{
                        "targetType":"page",
                        "url":"我的劲态（二维码）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a91c6a3fff74306a2ec99e1581a717c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":299},
            "size":{
              "width":320,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9026b1e7f5fd48cbb71ff18554647402",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":299},
                "size":{
                  "width":320,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的劲态（二维码）/u16.png"}},
{
          "id":"d345ced6b9b34ad2b2c6e57371f61fbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":164,
              "y":303},
            "size":{
              "width":150,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a0b950a44de4beea67d633c64daddec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":164,
                  "y":303},
                "size":{
                  "width":150,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的消息（已读）",
                      "target":{
                        "targetType":"page",
                        "url":"我的消息（已读）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3aea25405b048df89e0887ec16b4a9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":5,
              "y":303},
            "size":{
              "width":150,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f94139ba18cd4a5d9976f376603934a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":5,
                  "y":303},
                "size":{
                  "width":150,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec8e386cee0f46ae8ada3ccedbbecfe1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":337},
            "size":{
              "width":320,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06eb3c971b3645659ff2148480b5e67f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":337},
                "size":{
                  "width":320,
                  "height":63}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的劲态（二维码）/u22.png"}},
{
          "id":"b471a54a272f411287f88edf015906bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":10,
              "y":343},
            "size":{
              "width":280,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3e2d0e7e67d47a1a52bc5986e87a2c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":10,
                  "y":343},
                "size":{
                  "width":280,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 消息详情",
                      "target":{
                        "targetType":"page",
                        "url":"消息详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37ab185e12f245c28f2b870587142b07",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6FCEB6,
              "opacity":1},
            "location":{
              "x":10,
              "y":364},
            "size":{
              "width":280,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cef8a90816344984a5cb49cb8342e301",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6FCEB6,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":364},
                "size":{
                  "width":280,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 消息详情",
                      "target":{
                        "targetType":"page",
                        "url":"消息详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef34dfd66bfa443a8179b2967ead818b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":403},
            "size":{
              "width":320,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"941b7799290d4ceead5823443700ddba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":403},
                "size":{
                  "width":320,
                  "height":63}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的劲态（二维码）/u22.png"}},
{
          "id":"617d1a018ffb4cb19dd2c07ac1cbe79d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":10,
              "y":409},
            "size":{
              "width":280,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07bc7cde4e9f4bdb9009458bcd2a54d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":10,
                  "y":409},
                "size":{
                  "width":280,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 消息详情",
                      "target":{
                        "targetType":"page",
                        "url":"消息详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"219448f3a74642519094874325630e10",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6FCEB6,
              "opacity":1},
            "location":{
              "x":10,
              "y":430},
            "size":{
              "width":280,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b81ee146f7174ec78901c47003ae2c64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6FCEB6,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":430},
                "size":{
                  "width":280,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 消息详情",
                      "target":{
                        "targetType":"page",
                        "url":"消息详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"339bb94ac79849df82ef6d3b3192bfd5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":467},
            "size":{
              "width":320,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d311ec37d204ca2b78f0b987e67d9a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":467},
                "size":{
                  "width":320,
                  "height":63}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的劲态（二维码）/u22.png"}},
{
          "id":"9e99e3ef7410478d951a9f9bff267a32",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":10,
              "y":473},
            "size":{
              "width":280,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd09d3fa566c4385b7940e2165137dcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":10,
                  "y":473},
                "size":{
                  "width":280,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 消息详情",
                      "target":{
                        "targetType":"page",
                        "url":"消息详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07078ac9943348e89a31cf0bcb37596d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6FCEB6,
              "opacity":1},
            "location":{
              "x":10,
              "y":494},
            "size":{
              "width":280,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3a9bdf36e2e47f4a20fcd30c1b1a637",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6FCEB6,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":494},
                "size":{
                  "width":280,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 消息详情",
                      "target":{
                        "targetType":"page",
                        "url":"消息详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "2c47110a83a3413ca8986c9bd022018a":{
      "scriptId":"u0"},
    "a53fa6ec5bfc464ab5eee4eaec89b3b8":{
      "scriptId":"u1"},
    "19572c675f814dc48ec1926834d488b6":{
      "scriptId":"u2"},
    "8ec89f1eb9794de8a4cb6eb6af8f7ee5":{
      "scriptId":"u3"},
    "57873a1a0fb24372bc08f0b05b3dcb2e":{
      "scriptId":"u4"},
    "22ea1c5a15b94c96803058b1ea9378f4":{
      "scriptId":"u5"},
    "9925f76ab2ae4db1adced61f2fe9cde1":{
      "scriptId":"u6"},
    "6f47efc6d2b543fc909d55aa370024f7":{
      "scriptId":"u7"},
    "250a4af0c43b484c9dc0ae776381ac5f":{
      "scriptId":"u8"},
    "557f15802d9d458ea4533b2df09fbde7":{
      "scriptId":"u9"},
    "d678c6e2dd904c34be02e3944932ff70":{
      "scriptId":"u10"},
    "8ebba040429f4c60ae41a160eb352b57":{
      "scriptId":"u11"},
    "9d3d10c68f024e34961c82fffb2359d8":{
      "scriptId":"u12"},
    "fbeaa3ba78ee4236bc43d03dd173d211":{
      "scriptId":"u13"},
    "2e8dd69144f14f43acc1f07a49e8fb9a":{
      "scriptId":"u14"},
    "ff30550e1b6c44558d0b7a26d7c90a72":{
      "scriptId":"u15"},
    "9a91c6a3fff74306a2ec99e1581a717c":{
      "scriptId":"u16"},
    "9026b1e7f5fd48cbb71ff18554647402":{
      "scriptId":"u17"},
    "d345ced6b9b34ad2b2c6e57371f61fbe":{
      "scriptId":"u18"},
    "0a0b950a44de4beea67d633c64daddec":{
      "scriptId":"u19"},
    "f3aea25405b048df89e0887ec16b4a9b":{
      "scriptId":"u20"},
    "f94139ba18cd4a5d9976f376603934a6":{
      "scriptId":"u21"},
    "ec8e386cee0f46ae8ada3ccedbbecfe1":{
      "scriptId":"u22"},
    "06eb3c971b3645659ff2148480b5e67f":{
      "scriptId":"u23"},
    "b471a54a272f411287f88edf015906bb":{
      "scriptId":"u24"},
    "f3e2d0e7e67d47a1a52bc5986e87a2c3":{
      "scriptId":"u25"},
    "37ab185e12f245c28f2b870587142b07":{
      "scriptId":"u26"},
    "cef8a90816344984a5cb49cb8342e301":{
      "scriptId":"u27"},
    "ef34dfd66bfa443a8179b2967ead818b":{
      "scriptId":"u28"},
    "941b7799290d4ceead5823443700ddba":{
      "scriptId":"u29"},
    "617d1a018ffb4cb19dd2c07ac1cbe79d":{
      "scriptId":"u30"},
    "07bc7cde4e9f4bdb9009458bcd2a54d8":{
      "scriptId":"u31"},
    "219448f3a74642519094874325630e10":{
      "scriptId":"u32"},
    "b81ee146f7174ec78901c47003ae2c64":{
      "scriptId":"u33"},
    "339bb94ac79849df82ef6d3b3192bfd5":{
      "scriptId":"u34"},
    "5d311ec37d204ca2b78f0b987e67d9a9":{
      "scriptId":"u35"},
    "9e99e3ef7410478d951a9f9bff267a32":{
      "scriptId":"u36"},
    "dd09d3fa566c4385b7940e2165137dcc":{
      "scriptId":"u37"},
    "07078ac9943348e89a31cf0bcb37596d":{
      "scriptId":"u38"},
    "a3a9bdf36e2e47f4a20fcd30c1b1a637":{
      "scriptId":"u39"}}});