$axure.loadCurrentPage({
  "url":"【我的】页面（已编辑头像）.html",
  "generationDate":new Date(1432847390256.36),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0f1bfcb161784cd382fb505601eec57f",
    "type":"Axure:Page",
    "name":"【我的】页面（已编辑头像）",
    "notes":{
      "默认":"<p><span>1.已经购买的时间到期后会有评论入口：1.对商家的评论。2.对卖方的评论(只显示最近5天的)。</span></p><p><span>2.同一天不允许购买一家以上的机构提供的健身服务。</span></p><p><span>3.消息，回复消息。站内信</span></p><p><span>4.持卡人同时又是买时间者（家里有卡，公司没卡。）</span></p>"},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onClick":{
        "description":"OnClick",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"linkWindow",
                "description":"在 当前窗口 打开 登录页面",
                "target":{
                  "targetType":"page",
                  "url":"登录页面.html",
                  "includeVariables":true},
                "linkType":"current"}]}]}},
    "diagram":{
      "objects":[{
          "id":"d3b963fe831c453197f155d7d2fab42e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":-20},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eef9e5df46424126b3fada27876e6b27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":-20},
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【我的】页面（新注册）/u0.png"}},
{
          "id":"e76de90fd61644dcab6dad84c6fcf005",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "opacity":"0",
            "location":{
              "x":8,
              "y":11},
            "size":{
              "width":72,
              "height":39},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c8b5ba186e24128bf3c4a0dcb0f5ee3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "opacity":"0",
                "location":{
                  "x":8,
                  "y":11},
                "size":{
                  "width":72,
                  "height":39},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的劲态（二维码）",
                      "target":{
                        "targetType":"page",
                        "url":"我的劲态（二维码）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00efd4b0aba04e80acb1e291db8cc30b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "opacity":"0",
            "location":{
              "x":8,
              "y":503},
            "size":{
              "width":302,
              "height":39},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0281698cc9a457aa76e3b56e904cb1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "opacity":"0",
                "location":{
                  "x":8,
                  "y":503},
                "size":{
                  "width":302,
                  "height":39},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的劲态（默认关注）",
                      "target":{
                        "targetType":"page",
                        "url":"我的劲态（默认关注）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"536e21fb2c39406e8a3b8d1f3471dca4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":65},
            "size":{
              "width":107,
              "height":105}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d9c1dafb0854f6793400e902157b3ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":106,
                  "y":65},
                "size":{
                  "width":107,
                  "height":105}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 编辑头像页",
                      "target":{
                        "targetType":"page",
                        "url":"编辑头像页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/左侧边栏/u16.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "d3b963fe831c453197f155d7d2fab42e":{
      "scriptId":"u0"},
    "eef9e5df46424126b3fada27876e6b27":{
      "scriptId":"u1"},
    "e76de90fd61644dcab6dad84c6fcf005":{
      "scriptId":"u2"},
    "0c8b5ba186e24128bf3c4a0dcb0f5ee3":{
      "scriptId":"u3"},
    "00efd4b0aba04e80acb1e291db8cc30b":{
      "scriptId":"u4"},
    "a0281698cc9a457aa76e3b56e904cb1a":{
      "scriptId":"u5"},
    "536e21fb2c39406e8a3b8d1f3471dca4":{
      "scriptId":"u6"},
    "5d9c1dafb0854f6793400e902157b3ad":{
      "scriptId":"u7"}}});