$axure.loadCurrentPage({
  "url":"支付页面.html",
  "generationDate":new Date(1432921474715.19),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"fd844c61480c46959764108ec578a958",
    "type":"Axure:Page",
    "name":"支付页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e41b0c6909ba4adba130a0fa96bf06a5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":0},
            "size":{
              "width":216,
              "height":548}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"380ac4db16184e8eb00dc8f0ff751621",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":106,
                  "y":0},
                "size":{
                  "width":216,
                  "height":548}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 买时间",
                      "target":{
                        "targetType":"page",
                        "url":"买时间.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/支付页面/u0.jpg"}},
{
          "id":"2b67c15b77924fa7b8e42cc2fa37b153",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":106,
              "height":548}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd30debeb0944e7a9e17e3148e66f8a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":106,
                  "height":548}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 买时间",
                      "target":{
                        "targetType":"page",
                        "url":"买时间.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/出售详情页/u0.png"}},
{
          "id":"9f9fd17c60c642d5a399e5bc52b418c1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":470},
            "size":{
              "width":216,
              "height":59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"229da1b43e6644dd8706c489083ce4d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":106,
                  "y":470},
                "size":{
                  "width":216,
                  "height":59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/出售详情页/u18.png"}},
{
          "id":"ac4b2da1c22f45bda58ed3763d32553f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":109,
              "y":475},
            "size":{
              "width":210,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45ddfb8f87a949e484e0b824bcbb60e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":109,
                  "y":475},
                "size":{
                  "width":210,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 买时间",
                      "target":{
                        "targetType":"page",
                        "url":"买时间.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e41b0c6909ba4adba130a0fa96bf06a5":{
      "scriptId":"u0"},
    "380ac4db16184e8eb00dc8f0ff751621":{
      "scriptId":"u1"},
    "2b67c15b77924fa7b8e42cc2fa37b153":{
      "scriptId":"u2"},
    "cd30debeb0944e7a9e17e3148e66f8a4":{
      "scriptId":"u3"},
    "9f9fd17c60c642d5a399e5bc52b418c1":{
      "scriptId":"u4"},
    "229da1b43e6644dd8706c489083ce4d9":{
      "scriptId":"u5"},
    "ac4b2da1c22f45bda58ed3763d32553f":{
      "scriptId":"u6"},
    "45ddfb8f87a949e484e0b824bcbb60e9":{
      "scriptId":"u7"}}});